(function(g){var window=this;'use strict';var o4=function(X){X.publish("cardstatechange",X.Xr()&&X.hc()?1:0)},ed=function(X,c){var V=g.Kj(c),G=V?c:arguments;
for(V=V?0:1;V<G.length;V++){if(X==null)return;X=X[G[V]]}return X},sF_=function(X){var c=g.ZX(X);
X=g.mn(X);return new g.Yv(c.x,c.y,X.width,X.height)},C17=function(X,c,V){var G=G===void 0?{}:G;
var n;return n=g.ol(X,c,function(){g.eP(n);V.apply(X,arguments)},G)},R4=function(X){X=g.DS(X);
delete JY[X];g.bU(JY)&&me&&me.stop()},SWr=function(){me||(me=new g.i_(function(){DJH()},20));
var X=me;X.isActive()||X.start()},DJH=function(){var X=g.Xr();
g.Qv(JY,function(c){idt(c,X)});
g.bU(JY)||SWr()},bJ=function(X,c,V,G){g.ab.call(this);
if(!Array.isArray(X)||!Array.isArray(c))throw Error("Start and end parameters must be arrays");if(X.length!=c.length)throw Error("Start and end points must be the same length");this.G=X;this.D=c;this.duration=V;this.Z=G;this.coords=[];this.progress=this.B=0;this.X=null},idt=function(X,c){c<X.startTime&&(X.endTime=c+X.endTime-X.startTime,X.startTime=c);
X.progress=(c-X.startTime)/(X.endTime-X.startTime);X.progress>1&&(X.progress=1);X.B=1E3/(c-X.X);X.X=c;qWV(X,X.progress);X.progress==1?(X.J=0,R4(X),X.onFinish(),X.TP()):X.isPlaying()&&X.Am()},qWV=function(X,c){typeof X.Z==="function"&&(c=X.Z(c));
X.coords=Array(X.G.length);for(var V=0;V<X.G.length;V++)X.coords[V]=(X.D[V]-X.G[V])*c+X.G[V]},XHH=function(X,c){g.f_.call(this,X);
this.coords=c.coords;this.x=c.coords[0];this.y=c.coords[1];this.z=c.coords[2];this.duration=c.duration;this.progress=c.progress;this.fps=c.B;this.state=c.J},tY=function(X,c,V,G,n){bJ.call(this,c,V,G,n);
this.element=X},cvr=function(X,c,V,G,n){if(c.length!=2||V.length!=2)throw Error("Start and end points must be 2D");
tY.call(this,X,c,V,G,n)},Vvt=function(X){return Math.pow(X,3)},GsV=function(X){return 3*X*X-2*X*X*X},n8U=function(X){g.I.call(this);
this.G=X||window;this.J=[]},OY=function(X){return X.baseUrl||null},lJ=function(X,c){return g.j8(g.mi(X,c),function(V){return!!V})},LCH=function(X,c,V){function G(yl){var Xl=yl.hovercardButton;
if(!Xl)return null;Xl=Xl.subscribeButtonRenderer;if(!Xl)return null;var u=L(Xl.unsubscribedButtonText),q=L(Xl.subscribedButtonText);if(Xl.subscribed){var Q=L(Xl.subscriberCountWithUnsubscribeText);var P=L(Xl.subscriberCountText)}else Q=L(Xl.subscriberCountText),P=L(Xl.subscriberCountWithSubscribeText);var UD=null;if(yl.signinEndpoint){UD=ed(yl,"signinEndpoint","webNavigationEndpointData","url");if(!UD){var Zi,ah;UD=(ah=g.T((Zi=Xl.signInEndpoint)==null?void 0:Zi.commandMetadata,g.wB))==null?void 0:
ah.url}if(!UD)return null}return u&&(q||UD)?{subscribed:Xl.subscribed,subscribeText:u,subscribeCount:Q,unsubscribeText:q,unsubscribeCount:P,enabled:Xl.enabled,signinUrl:UD,classic:yl.useClassicSubscribeButton}:null}
function n(yl){if(yl){var Xl=[],u=yl.videoId;u&&Xl.push("v="+u);(u=yl.playlistId)&&Xl.push("list="+u);(yl=yl.startTimeSeconds)&&Xl.push("t="+yl);return"/watch?"+Xl.join("&")}}
function L(yl){if(!yl)return null;var Xl=yl.simpleText;return Xl?Xl:yl.runs?g.mi(yl.runs,function(u){return u.text}).join(""):null}
c=c.endscreenElementRenderer;if(!c)return null;var d=c.style,h=c.endpoint||{},A=null,Y=null,H=!1,a=null,W=null,w=null,F=null,Z=!1,v=null,e=null,m=null,t=null,f=null,U=null;if(d==="VIDEO")g.T(h,g.TR)?A=g.T(h,g.TR).url:(U=g.T(h,g.ij),A=n(U)),Y=!1,a=X,c.thumbnailOverlays?(H=c.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,W=L(H.text),H=H.style==="LIVE"):W=L(c.videoDuration);else if(d==="PLAYLIST")g.T(h,g.TR)?A=g.T(h,g.TR).url:(U=g.T(h,g.ij),A=n(U)),Y=!1,a=X,w=L(c.playlistLength);else if(d===
"CHANNEL"){if(Z=ed(h,"browseEndpoint","browseId"))F=Z,A="/channel/"+F;Y=!1;a="new";(Z=!!c.isSubscribe)?v=G(c):e=L(c.subscribersText)}else d==="WEBSITE"?((m=ed(h,"urlEndpoint","url"))&&(A=m),Y=!0,a="new",m=c.icon.thumbnails[0].url):d==="CREATOR_MERCHANDISE"&&(c.productPrice&&(t=L(c.productPrice)),c.additionalFeesText&&(f=L(c.additionalFeesText)),(Y=ed(h,"urlEndpoint","url"))&&(A=Y),Y=!0,a="new");X=ed(c,"title","accessibility","accessibilityData","label");var C=c.endpoint?c.endpoint.clickTrackingParams:
null,K="";if(c.metadata){var nj=L(c.metadata);nj&&(K=nj)}return{id:"element-"+V,type:d,title:L(c.title),metadata:K,callToAction:L(c.callToAction),e2:c.image,iconUrl:m,left:Number(c.left),width:Number(c.width),top:Number(c.top),aspectRatio:Number(c.aspectRatio),startMs:Math.floor(Number(c.startMs)),endMs:Math.floor(Number(c.endMs)),videoDuration:W,n4:H,playlistLength:w,channelId:F,subscribeButton:v,subscribersText:e,isSubscribe:Z,targetUrl:A||null,kFy:Y,sessionData:C?{itct:C}:null,TJ_:a,zE:X?X:null,
isPlaceholder:c.isPlaceholder,impressionUrls:lJ(c.impressionUrls||[],OY),y77:lJ(c.hovercardShowUrls||[],OY),clickUrls:lJ(h.loggingUrls||[],OY),visualElement:g.JU(c.trackingParams),productPrice:t,additionalFeesText:f,watchEndpoint:U||null}},doG=function(X,c){var V={startMs:Math.floor(Number(X.startMs)),
impressionUrls:lJ(X.impressionUrls||[],OY),elements:lJ(X.elements||[],function(G,n){return LCH(c,G,n)})};
X.trackingParams&&(V.visualElement=g.JU(X.trackingParams));return V},yvz=function(X){g.wh.call(this,X);
this.X=this.endscreen=null;this.G={};this.B={};this.Z=this.U=null;this.T=[];this.J=null;this.G_=!0;this.D=0;X=X.j();this.C=g.M7(X)||g.fL(X);this.events=new g.N_(this);g.N(this,this.events);this.events.L(this.player,g.Ya("creatorendscreen"),this.onCueRangeEnter);this.events.L(this.player,g.jw("creatorendscreen"),this.onCueRangeExit);this.events.L(this.player,"resize",this.Ky);this.events.L(window,"focus",this.EMR);this.load();var c=g.cW("STYLE");(g.B1("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.dW(c)});
c.sheet&&(c.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),c.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},hOt=function(X){return X.player.getVideoData().O5?"current":X.C?"new":"current"},MF=function(X){return X.player.j().playerStyle==="creator-endscreen-editor"},AvA=function(X){var c=X.player.getVideoData(),V=c.videoId;
X.X&&X.X.abort();V={method:"POST",onFinish:function(n){var L=X.X=null;n.status===200&&(n=n.responseText,n.substring(0,3)===")]}"&&(n=n.substring(3),L=JSON.parse(n),L=doG(L,hOt(X))));go(X,L)},
urlParams:{v:V},withCredentials:!0};X.C&&(V.urlParams.ptype="embedded");var G=c.bG;G&&(V.postParams={ad_tracking:G});if(c=g.HmU(c))if(c=g.l6(c),c=g.b6(c))X.X=g.Ra(c,V)},go=function(X,c,V){V=V===void 0?!0:V;
X.player.EH("creatorendscreen");X.U&&(X.U.dispose(),X.U=null,X.Z.dispose(),X.Z=null);for(var G=g.r(Object.values(X.G)),n=G.next();!n.done;n=G.next())n.value.dispose();X.G={};X.B={};X.T.length>0&&(X.T.forEach(function(h){h.dispose()}),X.T.length=0);
X.J&&(g.YD(X.J,"ytp-ce-element-show"),X.J.setAttribute("aria-hidden","true"));X.D=0;if((X.endscreen=c)&&c.elements){V&&Y9z(X);V=[];G=new g.hC(c.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});V.push(G);X.player.j().G||(X.U=new g.z({N:"div",Y:"ytp-ce-shadow"}),g.lc(X.player,X.U.element,4),X.Z=new g.dR(X.U,200));for(G=0;G<c.elements.length;++G){n=c.elements[G];var L=jcp(X,n);if(L){X.G[n.id]=L;X.B[n.id]=n;g.lc(X.player,L.element,4);var d=new g.hC(n.startMs,n.endMs,{id:"ytp-ce-element-"+
n.id,namespace:"creatorendscreen"});V.push(d);H7A(X,L,n)}else g.Ni(new g.Dh("buildEndscreenElement null",n))}X.player.Gr(V);X.Ky()}},Y9z=function(X){var c=g.RJ(),V=g.bz();
V&&c&&X.endscreen.visualElement&&g.V8(g.iz)(void 0,V,c,X.endscreen.visualElement)},jcp=function(X,c){var V=null;
switch(c.type){case "VIDEO":X={N:"div",xO:["ytp-ce-element","ytp-ce-video"],K:{tabindex:"0","aria-label":c.zE||"","aria-hidden":"true"},V:[{N:"div",Y:"ytp-ce-element-shadow"},{N:"div",Y:"ytp-ce-covering-image",K:f4(c)},{N:"div",Y:"ytp-ce-covering-shadow-top"},{N:"a",Y:"ytp-ce-covering-overlay",K:{href:p4(X,c.targetUrl),tabindex:"-1"},V:[{N:"div",xO:["ytp-ce-video-title","ytp-webkit-ellipsis"],K:{dir:g.Ev(c.title||"")},Uy:c.title},{N:"div",Y:c.n4?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Uy:c.videoDuration||void 0}]}]};V=new g.z(X);break;case "PLAYLIST":X={N:"div",xO:["ytp-ce-element","ytp-ce-playlist"],K:{tabindex:"0","aria-label":c.zE||"","aria-hidden":"true"},V:[{N:"div",Y:"ytp-ce-element-shadow"},{N:"div",Y:"ytp-ce-covering-image",K:f4(c)},{N:"div",Y:"ytp-ce-covering-shadow-top"},{N:"a",Y:"ytp-ce-covering-overlay",K:{href:p4(X,c.targetUrl),tabindex:"-1"},V:[{N:"div",xO:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],K:{dir:g.Ev(c.title||"")},Uy:c.title},{N:"div",Y:"ytp-ce-playlist-count",
V:[{N:"div",Y:"ytp-ce-playlist-icon"},{N:"div",Y:"ytp-ce-playlist-count-text",Uy:c.playlistLength||void 0}]}]}]};V=new g.z(X);break;case "CHANNEL":V={N:"div",xO:["ytp-ce-element","ytp-ce-channel",c.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],K:{tabindex:"0","aria-label":c.zE||"","aria-hidden":"true"},V:[{N:"div",Y:"ytp-ce-element-shadow"},{N:"div",Y:"ytp-ce-expanding-overlay",V:[{N:"div",Y:"ytp-ce-expanding-overlay-hider"},{N:"div",Y:"ytp-ce-expanding-overlay-background"},{N:"div",Y:"ytp-ce-expanding-overlay-content",
V:[{N:"div",Y:"ytp-ce-expanding-overlay-body",V:[{N:"div",Y:"ytp-ce-expanding-overlay-body-padding",V:[{N:"a",xO:["ytp-ce-channel-title","ytp-ce-link"],K:{href:p4(X,c.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ev(c.title||"")},Uy:c.title},c.subscribeButton?{N:"div",Y:"ytp-ce-subscribe-container",V:[{N:"div",Y:"ytp-ce-channel-subscribe"}]}:"",c.subscribersText?{N:"div",Y:"ytp-ce-channel-subscribers-text",Uy:c.subscribersText}:"",c.metadata?{N:"div",xO:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Uy:c.metadata}:""]}]}]}]},{N:"div",Y:"ytp-ce-expanding-image",K:f4(c)}]};V=new g.z(V);var G=g.sz(document,"div","ytp-ce-channel-subscribe",V.element)[0];if(c.subscribeButton&&c.channelId){g.hx(G,"ytp-ce-subscribe-button");if(X.player.j().G){var n=null;var L=c.sessionData.itct}else n="endscreen",L=null;n=new g.DL(c.subscribeButton.subscribeText,c.subscribeButton.subscribeCount,c.subscribeButton.unsubscribeText,c.subscribeButton.unsubscribeCount,!!c.subscribeButton.enabled,!!c.subscribeButton.classic,
c.channelId,!!c.subscribeButton.subscribed,n,L,X.player,!1);G.appendChild(n.element);X.T.push(n)}break;case "WEBSITE":X={N:"div",xO:["ytp-ce-element","ytp-ce-website"],K:{tabindex:"0","aria-label":c.zE||"","aria-hidden":"true"},V:[{N:"div",Y:"ytp-ce-element-shadow"},{N:"div",Y:"ytp-ce-expanding-overlay",V:[{N:"div",Y:"ytp-ce-expanding-overlay-hider"},{N:"div",Y:"ytp-ce-expanding-overlay-background"},{N:"div",Y:"ytp-ce-expanding-overlay-content",V:[{N:"div",Y:"ytp-ce-expanding-overlay-body",V:[{N:"div",
Y:"ytp-ce-expanding-overlay-body-padding",V:[{N:"div",Y:"ytp-ce-website-title",K:{dir:g.Ev(c.title||"")},Uy:c.title},{N:"div",Y:"ytp-ce-website-metadata",Uy:c.metadata},{N:"a",xO:["ytp-ce-website-goto","ytp-ce-link"],K:{href:p4(X,c.targetUrl),target:"_blank",tabindex:"-1"},Uy:c.callToAction}]}]}]}]},{N:"div",Y:"ytp-ce-expanding-image",K:f4(c)},{N:"div",Y:"ytp-ce-expanding-icon",K:a1V(c.iconUrl)}]};V=new g.z(X);break;case "CREATOR_MERCHANDISE":V="",c.productPrice&&(V={N:"div",Y:"ytp-ce-merchandise-price-container",
V:[{N:"div",Y:"ytp-ce-merchandise-price",Uy:c.productPrice}]},c.additionalFeesText&&V.V.push({N:"div",Y:"ytp-ce-merchandise-additional-fees",Uy:c.additionalFeesText})),X={N:"div",xO:["ytp-ce-element","ytp-ce-merchandise"],K:{tabindex:"0","aria-label":c.zE||"","aria-hidden":"true"},V:[{N:"div",Y:"ytp-ce-element-shadow"},{N:"div",Y:"ytp-ce-expanding-overlay",V:[{N:"div",Y:"ytp-ce-expanding-overlay-hider"},{N:"div",Y:"ytp-ce-expanding-overlay-background"},{N:"div",Y:"ytp-ce-expanding-overlay-content",
V:[{N:"div",Y:"ytp-ce-expanding-overlay-body",V:[{N:"div",Y:"ytp-ce-expanding-overlay-body-padding",V:[{N:"div",Y:"ytp-ce-merchandise-title",K:{dir:g.Ev(c.title||"")},Uy:c.title},V,{N:"div",Y:"ytp-ce-merchandise-metadata",Uy:c.metadata},{N:"a",xO:["ytp-ce-merchandise-goto","ytp-ce-link"],K:{href:p4(X,c.targetUrl),target:"_blank",tabindex:"-1"},Uy:c.callToAction}]}]}]}]},{N:"div",Y:"ytp-ce-expanding-image",K:f4(c)},{N:"div",Y:"ytp-ce-merchandise-invideo-cta-container",V:[{N:"div",Y:"ytp-ce-merchandise-invideo-cta",
Uy:c.callToAction||void 0}]}]},V=new g.z(X)}c.isPlaceholder&&g.hx(V.element,"ytp-ce-placeholder");return V},f4=function(X){if(X.e2)var c=X.e2.thumbnails;
return a1V(c?c[c.length-1].url:null)},a1V=function(X){return X?{style:"background-image: url("+X+")"}:{}},H7A=function(X,c,V){function G(A){A&&(c.listen("blur",function(){A.style.display!="none"&&X.G_&&A.focus()}),c.L(A,"focus",L),c.L(A,"blur",d))}
function n(A){X.D+=A;X.D>0?(g.hx(c.element,"ytp-ce-force-expand"),I4(X,V.id,!0)):(g.YD(c.element,"ytp-ce-force-expand"),g.YD(c.element,"ytp-ce-element-hover"),I4(X,V.id,!1))}
function L(){n(1)}
function d(){n(-1)}
c.listen("mouseenter",function(){$ot(X,c,V)});
c.listen("mouseleave",function(){WCi(X,c,V)});
X.player.j().G||c.listen("click",function(){g.hx(c.element,"ytp-ce-element-hover")});
c.listen("click",function(A){wHh(X,V,A)});
c.listen("keypress",function(A){wHh(X,V,A)});
c.listen("focus",function(){$ot(X,c,V)});
c.listen("blur",function(){WCi(X,c,V)});
c.listen("touchstart",function(){$ot(X,c,V)});
var h=g.C0("ytp-ce-expanding-overlay-hider",c.element);h&&c.L(h,"touchstart",function(A){A.stopPropagation();g.YD(c.element,"ytp-ce-element-hover");g.YD(c.element,"ytp-ce-force-expand")});
c.listen("keydown",function(A){X.G_=A.keyCode===9&&!A.shiftKey});
G(g.C0("ytp-sb-subscribe",c.element));G(g.C0("ytp-sb-unsubscribe",c.element));c.listen("focus",L);c.listen("blur",d)},wHh=function(X,c,V){if(c.targetUrl&&(!V||V.type!=="keypress"||V.keyCode===13)){for(var G=V.target;G&&!g.yO(G,"ytp-ce-element");){g.yO(G,"subscribe-label")&&FCk(X,c);
if(g.yO(G,"ytp-ce-channel-subscribe"))return;G=G.parentElement||null}if(!G||g.yO(G,"ytp-ce-element-hover")){V.preventDefault();V.stopPropagation();if(G=X.G[c.id])WCi(X,G,c),G.element.blur();if(V.ctrlKey||V.metaKey||c.TJ_==="new")FCk(X,c),X.player.sendVideoStatsEngageEvent(17,void 0),X.player.pauseVideo(),V=g.l6(p4(X,c.targetUrl)),V=g.b6(V),g.sS(V,void 0,c.sessionData);else{var n=g.Dv(X.player.j())||X.player.getVideoData().O5,L=function(){var d=p4(X,c.targetUrl),h=c.sessionData,A=c.watchEndpoint,Y=
g.h3(d);n&&Y&&(Y.v||Y.list)?X.player.Tf(Y.v,h,Y.list,!1,void 0,A||void 0):g.KZ(d,h)};
FCk(X,c,function(){X.player.sendVideoStatsEngageEvent(17,L)})}}}},p4=function(X,c){X=X.player.j();
if(c){if(c.startsWith("//"))return X.protocol+":"+c;if(c.startsWith("/"))return g.G_(X)+c}else return"";return c},$ot=function(X,c,V){g.yO(c.element,"ytp-ce-element-hover")||(V.type==="VIDEO"||V.type==="PLAYLIST"?g.hx(c.element,"ytp-ce-element-hover"):X.player.j().G?(new g.i_(function(){g.hx(c.element,"ytp-ce-element-hover")},200)).start():g.hx(c.element,"ytp-ce-element-hover"),NF(X,V.y77),I4(X,V.id,!0))},WCi=function(X,c,V){g.YD(c.element,"ytp-ce-element-hover");
g.YD(c.element,"ytp-ce-force-expand");I4(X,V.id,!1)},I4=function(X,c,V){X.U&&(V?X.Z.show():X.Z.hide());
for(var G=g.r(Object.keys(X.G)),n=G.next();!n.done;n=G.next())n=n.value,n!==c&&g.H6(X.G[n].element,"ytp-ce-element-shadow-show",V)},NF=function(X,c,V){function G(){L||(n++,n===c.length&&(d.stop(),V&&V()))}
if(!c||c.length===0||MF(X))V&&V();else{c=E8G(X,c);var n=0,L=!1,d=new g.i_(function(){L=!0;V&&V()},1E3,X);
d.start();for(X=0;X<c.length;X++)g.zM(c[X],G)}},FCk=function(X,c,V){NF(X,c.clickUrls,V);
(X=g.bz())&&c.kFy&&g.Ay(X,c.visualElement)},E8G=function(X,c){var V=X.player.getVideoData().clientPlaybackNonce;
X=X.player.getCurrentTime().toFixed(2);V={CPN:V,AD_CPN:V,MT:X};X=[];for(var G=0;G<c.length;G++)X.push(rvr(c[G],V));return X},rvr=function(X,c){return X.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(V){var G=unescape(V);
G=G.substring(1,G.length-1);return c[G]?escape(c[G]):V})},QcG=function(X){return typeof X==="string"?X:""},UY=function(X,c,V){for(var G in c)if(c[G]===X)return X;
return V},Z7V=function(X,c,V,G){this.value=X;
this.target=c;this.showLinkIcon=V;this.J=G},TU=function(X){return X.value?X.value:null},uJ=function(X){if(!X)return null;
var c=g.l6(QcG(X.value));c=g.b6(c);if(!c)return null;var V=UY(X.target,xoz,"current");if(V==null)X=null;else{var G=X.show_link_icon;X=new Z7V(c,V,G==="true"||G==="false"?G==="true":!0,X.pause_on_navigation!=null?X.pause_on_navigation:!0)}return X},v87=function(X,c,V){this.type=X;
this.trigger=c;this.url=V},eOM=function(X){if(!X)return null;
var c=UY(X.type,ksk),V=UY(X.trigger,o8A);X=X.url;X=Array.isArray(X)&&X.length?X[0]:X;X=uJ(X?X:null);return c?new v87(c,V,X):null},Jv7=function(X,c,V,G,n){this.id=X;
this.type=c;this.style=V;this.data=n;this.action=G||[]},moh=function(X,c){return g.sH(X.action,c)},ROi=function(X,c){this.context=X;
this.J=c},b7k=function(X){return X.customMessage?Pk("div","iv-card-message",X.customMessage):""},zU=function(X,c){X="background-image: url("+X+");";
var V=[];c&&V.push(c);return{N:"div",Y:"iv-card-image",K:{style:X},V:V}},tvp=function(X){if(!X.metaInfo||X.metaInfo.length===0)return"";
var c=[];X=g.r(X.metaInfo);for(var V=X.next();!V.done;V=X.next())c.push(Pk("li","",V.value));return{N:"ul",Y:"iv-card-meta-info",V:c}},Pk=function(X,c,V){c?typeof c==="string"?c={"class":c}:Array.isArray(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Ev(V);return{N:X,K:c,Uy:V}},O7i=function(X){if(!X.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],V={};X.UE&&(c.push("iv-card-action-icon"),V.style="background-image: url("+X.UE+");");V.dir=g.Ev(X.customMessage);var G=[{N:"span",Uy:X.customMessage}];X.showLinkIcon&&(G.push("\u00a0"),G.push({N:"span",Y:"iv-card-link-icon"}));return{N:"div",xO:c,K:V,V:G}},Bk=function(X,c,V,G){if(G){c=g.r(c);
for(var n=c.next();!n.done;n=c.next())X.J(n.value,G,V.id,V.sessionData,V.kR.click,5)}},l1U=function(X,c){this.merchant=X;
this.price=c},Mvz=function(X){var c;
(c=X)&&!(c=X.length>1?X.charAt(0)==="/"&&X.charAt(1)!=="/":X==="/")&&(c=X.replace(/^(https?:)?\/\//,"").split("/",1),c=!c||c.length<1||!c[0]?[]:c[0].toLowerCase().split(".").reverse(),c=c[0]==="com"&&c[1]==="youtube"||c[0]==="be"&&c[1]==="youtu");return c?X.indexOf("/redirect?")===-1:!1},g8V=function(X,c){return c?c:Mvz(X)?"current":"new"},K4=function(X,c){g.I.call(this);
var V=this;this.element=X;this.context=c;this.qE=!1;this.LS=new Map;this.fS=new Map;this.context.W.addEventListener(g.Ya("annotations_module"),function(G){(G=V.LS.get(G))&&G.apply(V)});
this.context.W.addEventListener(g.jw("annotations_module"),function(G){(G=V.fS.get(G))&&G.apply(V)})},sY=function(X,c,V,G,n,L,d){X.context.J.listen(c,"click",function(h){X.hm(V,G,n,L||[],d||0,h)});
X.context.J.listen(c,"touchstart",function(){X.qE=!1});
X.context.J.listen(c,"touchmove",function(){X.qE=!0})},f1z=function(X){var c;
return((c=g.T(X,g.TR))==null?0:c.url)?g.T(X,g.TR).url:(X=g.T(X,g.ij))&&X.videoId?(c="/watch?v="+X.videoId,X.playlistId&&(c+="&list="+X.playlistId),X.index&&(c+="&index="+X.index),X.startTimeSeconds&&(c+="&t="+X.startTimeSeconds),c):null},C4=function(X,c,V){return{kB:(X.impressionLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
click:(V.loggingUrls||[]).map(function(G){return G.baseUrl||""}),
close:(c.dismissLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
NL:(c.impressionLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""}),
PH:(c.clickLoggingUrlsV2s||[]).map(function(G){return G.baseUrl||""})}},pHM=function(X,c,V){K4.call(this,c,V);
var G=this;this.W=X;this.eventId=null;this.HP=this.Hl=this.NE=this.U=this.isInitialized=!1;this.cards=[];this.o2=this.T=this.wy=this.Z=this.YO=this.J=null;this.G_=[];this.A7=this.D=this.CJ=this.Pl=null;this.B=0;this.NW=new g.i_(function(){},V.qW.AZ?4E3:3E3);
g.N(this,this.NW);this.yK=new g.i_(function(){});
g.N(this,this.yK);this.kO=new ROi(V,function(n,L,d,h,A,Y){sY(G,n,L,d,h,A,Y)});
this.C=new g.z({N:"div",Y:"iv-drawer",K:{id:"iv-drawer"},V:[{N:"div",Y:"iv-drawer-header",K:{"aria-role":"heading"},V:[{N:"span",Y:"iv-drawer-header-text"},{N:"button",xO:["iv-drawer-close-button","ytp-button"],K:{"aria-label":"Hide cards",tabindex:"0"}}]},{N:"div",Y:"iv-drawer-content"}]});g.N(this,this.C);this.X=this.C.element;this.T_=new g.dR(this.C,330);g.N(this,this.T_);this.hX=g.C0("iv-drawer-header-text",this.X);this.G=g.C0("iv-drawer-content",this.X);this.addCueRange(0,V.videoData.lengthSeconds*
1E3,"",function(){G.NE&&D_(G,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(G.NE=G.U)&&Sd(G)});
this.QK=new g.N_(this);g.N(this,this.QK);this.W.addEventListener("videodatachange",this.sQ.bind(this))},I1p=function(X,c){c=c.data;
c.autoOpenMs&&X.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){D_(X,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&X.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){Sd(X)});
var V=c.headerText;g.h5(X.hX,V);X.T&&X.T.setAttribute("title",V);c.eventId&&(X.eventId=c.eventId);X.Pl=g.JU(c.trackingParams);X.D=g.JU(c.closeTrackingParams);X.CJ=g.JU(c.iconTrackingParams)},NDz=function(X,c){var V=c.cardId?c.cardId:"cr:"+X.B,G=X.W.j().experiments.lc("enable_error_corrections_infocard_web_client");
if(!c.content&&c.teaser.simpleCardTeaserRenderer&&G){var n=c.teaser.simpleCardTeaserRenderer,L=c.icon?c.icon.infoCardIconRenderer:null;c={id:V,timestamp:X.B,type:"simple",teaserText:g.Zt(n.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:{},sponsored:!1,kR:{},Xf:null,zZ:n.trackingParams?g.JU(n.trackingParams):null,CJ:L&&L.trackingParams?g.JU(L.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
UE:null,title:"",customMessage:"",url:null,onClickCommand:n.onTapCommand||null};iJ(X,c)}else{var d;if((d=c.content)==null?0:d.simpleCardContentRenderer){if(!c.cueRanges.length)return;L=(n=c.content)==null?void 0:n.simpleCardContentRenderer;n=c.teaser.simpleCardTeaserRenderer;var h=c.icon?c.icon.infoCardIconRenderer:null;c={id:V,timestamp:X.B,type:"simple",teaserText:g.Zt(n.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,
sessionData:qF(X,V,c,L),sponsored:!1,kR:C4(L,n,L.command),Xf:L.trackingParams?g.JU(L.trackingParams):null,zZ:n.trackingParams?g.JU(n.trackingParams):null,CJ:h&&h.trackingParams?g.JU(h.trackingParams):null,imageUrl:Xw(L.image.thumbnails,290).url,displayDomain:L.displayDomain?g.Zt(L.displayDomain):null,showLinkIcon:!!L.showLinkIcon,UE:null,title:L.title?g.Zt(L.title):"",customMessage:L.callToAction?g.Zt(L.callToAction):"",url:g.T(L.command,g.TR).url?uJ({pause_on_navigation:!X.context.videoData.isLivePlayback,
target:"new",value:g.T(L.command,g.TR).url}):null,onClickCommand:null};iJ(X,c)}else{var A;if((A=c.content)==null?0:A.collaboratorInfoCardContentRenderer){if(!c.cueRanges.length)return;n=(L=c.content)==null?void 0:L.collaboratorInfoCardContentRenderer;L=c.teaser.simpleCardTeaserRenderer;h=c.icon?c.icon.infoCardIconRenderer:null;c={id:V,timestamp:X.B,type:"collaborator",teaserText:g.Zt(L.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),startMs:Number(c.cueRanges[0].startCardActiveMs),
autoOpen:!!c.autoOpen,sessionData:qF(X,V,c,n),sponsored:!1,kR:C4(n,L,n.endpoint),Xf:n.trackingParams?g.JU(n.trackingParams):null,zZ:L.trackingParams?g.JU(L.trackingParams):null,CJ:h&&h.trackingParams?g.JU(h.trackingParams):null,channelId:g.T(n.endpoint,g.ov).browseId,customMessage:n.customText?g.Zt(n.customText):null,profileImageUrl:Xw(n.channelAvatar.thumbnails,290).url,title:n.channelName?g.Zt(n.channelName):"",metaInfo:[n.subscriberCountText?g.Zt(n.subscriberCountText):""],url:uJ({pause_on_navigation:!X.context.videoData.isLivePlayback,
target:"new",value:g.T(n.endpoint,g.ov).canonicalBaseUrl?g.T(n.endpoint,g.ov).canonicalBaseUrl:"/channel/"+g.T(n.endpoint,g.ov).browseId}),onClickCommand:null};iJ(X,c)}else{var Y;if((Y=c.content)==null?0:Y.playlistInfoCardContentRenderer){if(!c.cueRanges.length)return;n=(h=c.content)==null?void 0:h.playlistInfoCardContentRenderer;L=c.teaser.simpleCardTeaserRenderer;h=c.icon?c.icon.infoCardIconRenderer:null;c={id:V,timestamp:X.B,type:"playlist",teaserText:g.Zt(L.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),
startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:qF(X,V,c,n),sponsored:!1,kR:C4(n,L,n.action),Xf:n.trackingParams?g.JU(n.trackingParams):null,zZ:L.trackingParams?g.JU(L.trackingParams):null,CJ:h&&h.trackingParams?g.JU(h.trackingParams):null,Rn:Xw(n.playlistThumbnail.thumbnails,258).url,customMessage:n.customMessage?g.Zt(n.customMessage):null,playlistVideoCount:g.Zt(n.playlistVideoCount),title:n.playlistTitle?g.Zt(n.playlistTitle):"",metaInfo:[n.channelName?g.Zt(n.channelName):
"",n.videoCountText?g.Zt(n.videoCountText):""],url:uJ({pause_on_navigation:!X.context.videoData.isLivePlayback,target:"new",value:f1z(n.action)}),onClickCommand:null};iJ(X,c)}else{var H;if((H=c.content)==null?0:H.videoInfoCardContentRenderer){if(!c.cueRanges.length)return;var a;n=(a=c.content)==null?void 0:a.videoInfoCardContentRenderer;L=c.teaser.simpleCardTeaserRenderer;h=c.icon?c.icon.infoCardIconRenderer:null;c={id:V,timestamp:X.B,type:"video",teaserText:g.Zt(L.message),teaserDurationMs:Number(c.cueRanges[0].teaserDurationMs),
startMs:Number(c.cueRanges[0].startCardActiveMs),autoOpen:!!c.autoOpen,sessionData:qF(X,V,c,n),sponsored:!1,kR:C4(n,L,n.action),Xf:n.trackingParams?g.JU(n.trackingParams):null,zZ:L.trackingParams?g.JU(L.trackingParams):null,CJ:h&&h.trackingParams?g.JU(h.trackingParams):null,Rn:Xw(n.videoThumbnail.thumbnails,258).url,videoDuration:n.lengthString?g.Zt(n.lengthString):null,customMessage:n.customMessage?g.Zt(n.customMessage):null,title:n.videoTitle?g.Zt(n.videoTitle):"",metaInfo:[n.channelName?g.Zt(n.channelName):
"",n.viewCountText?g.Zt(n.viewCountText):""],isLiveNow:!!n.badge,url:uJ({pause_on_navigation:!X.context.videoData.isLivePlayback,target:"new",value:f1z(n.action)}),onClickCommand:null};iJ(X,c)}}}}}X.B++},Xw=function(X,c){for(var V=-1,G=-1,n=0;n<X.length;n++){if(X[n].height===c||X[n].width===290)return X[n];
((X[n].height||0)<c||(X[n].width||0)<290)&&(V<0||(X[V].height||0)<(X[n].height||0)||(X[V].width||0)<(X[n].width||0))?V=n:((X[n].height||0)>=c||(X[n].width||0)>=290)&&(G<0||(X[G].height||0)>(X[n].height||0)||(X[G].width||0)>(X[n].width||0))&&(G=n)}return X[G>=0?G:V]},qF=function(X,c,V,G){return{feature:V.feature?V.feature:"cards",
src_vid:X.context.videoData.videoId,annotation_id:c,ei:X.context.videoData.eventId||"",itct:G.trackingParams||""}},TDi=function(X,c){if(c=Uok(X,c))c===X.J&&(X.J=null),X.W.removeCueRange(c.MN.id),g.dW(c.Zx),g.iA(X.cards,c),X.rq(),cm(X)},D_=function(X,c,V){if(!X.U){X.T_.show();
X.YO=new g.i_(function(){g.hx(X.context.W.getRootNode(),g.BV.IV_DRAWER_OPEN)},0);
X.YO.start();X.QK.L(X.G,"mousewheel",function(d){X.NW.start();d.preventDefault();d=d||window.event;var h=0;d.type=="MozMousePixelScroll"?h=0==(d.axis==d.HORIZONTAL_AXIS)?d.detail:0:window.opera?h=d.detail:h=d.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?d.wheelDeltaY/-30:d.wheelDeltaY/-1.2:d.wheelDelta/-1.6:d.wheelDeltaY/-3;if(d=h)X.G.scrollTop+=d});
X.U=!0;var G=g.bz();G&&X.Pl&&X.D&&g.y0(G,[X.Pl,X.D]);c={TRIGGER_TYPE:c};for(var n=g.r(X.cards),L=n.next();!L.done;L=n.next())L=L.value,L.Fk||(L.Fk=!0,utU(X.context.logger,L.MN.kR.kB,c)),G&&g.y0(G,[L.MN.Xf]);o4(X.W);V&&(X.Z=new g.i_(function(){X.wy=X.T;X.o2.focus()},330),X.Z.start())}},Sd=function(X){X.U&&(X.T_.hide(),g.O1(X.QK),g.YD(X.context.W.getRootNode(),g.BV.IV_DRAWER_OPEN),X.U=!1,o4(X.W),X.Z&&X.Z.stop(),X.Z=new g.i_(function(){X.wy&&(X.wy.focus(),X.wy=null)},330),X.Z.start())},P6z=function(X){g.Ax(X.WP(),
[g.BV.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.lc(X.W,X.X,5);X.uD();X.T=g.C0("ytp-cards-button",X.W.getRootNode());X.o2=g.C0("iv-drawer-close-button",X.X);X.isInitialized=!0},zOH=function(X){X.G_.push(g.AI("iv-teaser-shown",X.qp,X));
X.G_.push(g.AI("iv-teaser-hidden",X.eoR,X));X.G_.push(g.AI("iv-teaser-clicked",X.o_,X));X.HP=!0},BDA=function(X,c){var V;
return c.onClickCommand&&((V=g.T(c.onClickCommand,g.rEz))==null?void 0:V.targetId)==="engagement-panel-error-corrections"?(X.A7=c,!0):!1},KCi=function(X,c){X.A7=c;
var V=X.W.getVideoData();if(!V)return!1;V=g.ez(V);if(V==null?0:V.markersMap)for(var G,n=0;((G=V)==null?void 0:G.markersMap.length)>n;n++){var L=void 0,d=(L=V)==null?void 0:L.markersMap[n];if(d.key==="ERROR_CORRECTION_MARKERS"&&(L=void 0,(d=(L=d.value)==null?void 0:L.markers)&&d.length>0))return G=void 0,c.startMs=((G=g.T(d[0],g.n6l))==null?void 0:G.timeRangeStartMillis)||0,X.A7=null,!0}return!1},iJ=function(X,c){if(!BDA(X,c)||KCi(X,c)){var V=scA(X,c);
if(V){var G={MN:c,Zx:V.element,Fk:!1};if(c.onClickCommand)X.W.S("web_infocards_teaser_show_logging_fix")&&(X.HP||zOH(X),TDi(X,c.id),V=X.findLastIndex(G),g.LS(X.cards,V,0,G));else{X.isInitialized||P6z(X);TDi(X,c.id);var n=X.findLastIndex(G);g.LS(X.cards,n,0,G);V.uc(X.G,n);X.rq()}c.autoOpen?X.addCueRange(c.startMs,0x8000000000000,c.id,function(){X.U||(X.J=G,cm(X),C6V(X,G),D_(X,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(V=X.context.W.getCurrentTime()*1E3,V<5E3&&V>c.startMs&&DoU(X,G),X.addCueRange(c.startMs,
c.startMs+1,c.id,function(){DoU(X,G)}),cm(X))}}},scA=function(X,c){switch(c.type){case "simple":X=X.kO;
var V=c.displayDomain?{N:"div",Y:"iv-card-image-text",Uy:c.displayDomain}:void 0;var G=O7i(c);V={N:"div",xO:["iv-card"],V:[{N:"a",Y:"iv-click-target",K:{href:c.url?TU(c.url)||"":""},V:[zU(c.imageUrl,V),{N:"div",Y:"iv-card-content",V:[Pk("h2",void 0,c.title),G]}]}]};V=new g.z(V);Bk(X,g.K0("iv-click-target",V.element),c,c.url);c=V;break;case "collaborator":X=X.kO;V={N:"div",xO:["iv-card","iv-card-channel"],V:[{N:"a",xO:["iv-click-target"],K:{href:TU(c.url)||"","data-ytid":c.channelId},V:[zU(c.profileImageUrl),
{N:"div",Y:"iv-card-content",V:[b7k(c),{N:"h2",Y:"iv-card-primary-link",Uy:c.title},tvp(c)]}]}]};V=new g.z(V);Bk(X,g.K0("iv-click-target",V.element),c,c.url);c=V;break;case "playlist":X=X.kO;V={N:"div",xO:["iv-card","iv-card-playlist"],V:[{N:"a",Y:"iv-click-target",K:{href:TU(c.url)||""},V:[zU(c.Rn,{N:"div",Y:"iv-card-image-overlay",V:[{N:"span",Y:"iv-card-playlist-video-count",Uy:c.playlistVideoCount}]}),{N:"div",Y:"iv-card-content",V:[b7k(c),Pk("h2","iv-card-primary-link",c.title),tvp(c)]}]}]};
V=new g.z(V);Bk(X,g.K0("iv-click-target",V.element),c,c.url);c=V;break;case "productListing":X=X.kO;var n=c.offers.length!=0;V=["iv-card"];G="";var L=O7i(c);n&&(V.push("iv-card-product-listing"),G="iv-card-primary-link",L=c.offers[0],n=[],L.price&&n.push({N:"div",Y:"iv-card-offer-price",Uy:L.price}),L.merchant&&n.push({N:"div",Y:"iv-card-offer-merchant",Uy:L.merchant}),L={N:"div",V:n});n=c.url?TU(c.url)||"":"";V={N:"div",xO:V,K:{tabindex:"0"},V:[{N:"a",xO:["iv-card-image","iv-click-target"],K:{style:"background-image: url("+
c.imageUrl+");",href:n,"aria-hidden":"true",tabindex:"-1"}},{N:"div",Y:"iv-card-content",V:[c.sponsored?{N:"div",Y:"iv-card-sponsored",V:["Sponsored",{N:"div",Y:"iv-ad-info-container",V:[{N:"div",Y:"iv-ad-info",Uy:"{{adInfo}}"},{N:"div",Y:"iv-ad-info-icon-container",V:[{N:"div",Y:"iv-ad-info-icon"},{N:"div",Y:"iv-ad-info-callout"}]}]}]}:"",{N:"a",Y:"iv-click-target",K:{href:n},V:[Pk("h2",G,c.title),L]}]}]};V=new g.z(V);G=g.cW("span");g.h5(G,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
V.AT(G,"adInfo");Bk(X,g.K0("iv-click-target",V.element),c,c.url);c=V;break;case "video":X=X.kO;G=c.videoDuration?{N:"span",Y:"iv-card-video-duration",Uy:c.videoDuration}:void 0;L=c.isLiveNow?{N:"span",xO:["yt-badge","yt-badge-live"],Uy:"LIVE NOW"}:null;n={N:"div",xO:["iv-card","iv-card-video"],V:[{N:"a",Y:"iv-click-target",K:{href:((V=c.url)==null?void 0:TU(V))||""},V:[zU(c.Rn,G),{N:"div",Y:"iv-card-content",V:[b7k(c),Pk("h2","iv-card-primary-link",c.title),tvp(c),L]}]}]};V=new g.z(n);Bk(X,g.K0("iv-click-target",
V.element),c,c.url);c=V;break;default:return null}return c},S9G=function(X){if(X.J)return X.J.MN.type==="productListing";
if(X.W.S("enable_wn_infocards")){var c;return!((c=X.cards)==null||!c.length)&&g.Rt(X.cards,function(V){return V.MN.type==="productListing"})}return g.Rt(X.cards,function(V){return V.MN.type==="productListing"})},cm=function(X){g.H6(X.W.getRootNode(),"ytp-cards-shopping-active",S9G(X))},DoU=function(X,c){if(!g.yO(X.W.getRootNode(),"ytp-cards-teaser-shown")){if(X.J!==c){var V=g.bz(),G=X.J?X.J.MN.CJ:X.CJ;
V&&G&&g.hy(V,[G]);X.J=c;cm(X)}(V=X.isInitialized&&X.WP().style.display=="none")||(V=X.context.W.getPlayerState(),G=V===0&&X.context.W.getCurrentTime()===0,V=!(V===1||V===3||G));V||c.MN.teaserDurationMs&&X.W.b2(!0,{teaserText:c.MN.teaserText,durationMs:c.MN.teaserDurationMs,onClickCommand:c.MN.onClickCommand});X.yK.isActive()||((!X.U||!X.NW.isActive()&&X.Hl)&&C6V(X,c),X.yK.start(910+c.MN.teaserDurationMs))}},C6V=function(X,c){X.C.aZ?(c=new bJ([0,
X.G.scrollTop],[0,c.Zx.offsetTop],600,GsV),X.context.U.listen(c,"animate",function(V){X.G.scrollTop=V.y}),X.context.U.listen(c,"finish",function(V){X.G.scrollTop=V.y}),c.play()):(X.C.Ry(!0),X.G.scrollTop=c.Zx.offsetTop,X.C.Ry(!1))},VL=function(X){return X.J&&X.J.MN?X.J.MN:X.cards[0]&&X.cards[0].MN?X.cards[0].MN:null},Uok=function(X,c){return g.sH(X.cards,function(V){return V.MN.id===c})},GN=function(X,c,V){K4.call(this,X,c);
this.annotation=V;this.isActive=!1},i7h=function(X){var c=X.annotation.data;
"start_ms"in c&&"end_ms"in c&&X.addCueRange(Number(c.start_ms),Number(c.end_ms),X.annotation.id,function(){X.show()},function(){X.hide()})},nI=function(X,c,V){GN.call(this,X,c,V);
this.G=null;this.D=!1;this.U=null;this.X=!1;this.J=this.B=this.Z=null},q9i=function(X,c){var V=V===void 0?0:V;
var G=sF_(c).width;g.rS(c,G);V=new cvr(c,[G,c.offsetTop],[G-G-V,c.offsetTop],200,Vvt);g.N(X,V);X.context.U.listen(V,"begin",function(){g.Ro(c,!0)});
V.play()},V9p=function(X,c){if(c.channel_name){var V=X.createElement({N:"div",
xO:["iv-branding-context-name"],Uy:c.channel_name}),G=X.createElement({N:"div",xO:["iv-branding-context-subscribe"]}),n=c.standalone_subscribe_button_data;n&&(X.J=new g.DL(n.subscribeText,n.subscribeCount,n.unsubscribeText,n.unsubscribeCount,!!n.enabled,!!n.classic,c.channel_id,!!n.subscribed,n.feature,c.session_data.itct,X.context.W,!1),X.J.uc(G));var L=X.createElement({N:"div",xO:["iv-branding-context-subscribe-caret"]}),d=X.createElement({N:"div",xO:["branding-context-container-inner"]});d.appendChild(L);
d.appendChild(V);d.appendChild(G);g.Ro(d,!1);var h=X.createElement({N:"div",xO:["branding-context-container-outer"]});h.appendChild(d);g.ao(h,"right",c.image_width+"px");g.Gv(X.WP(),h);X.U=new g.i_(function(){X1k(X,d,h)},500);
g.N(X,X.U);X.context.J.listen(X.WP(),"mouseover",function(){cNG(X,d,h,L,c.image_height)});
X.context.J.listen(X.WP(),"mouseout",function(){X.U.start()})}},cNG=function(X,c,V,G,n){X.U.stop();
if(!X.X){var L=g.mn(c);X.J||(c.style.width=g.Eh(L.width,!0),V.style.width=g.Eh(L.width,!0));g.ao(G,"top",L.height-Math.max(Math.min(L.height,n)/2+10,20)+"px");g.ao(G,"right","1px");X.X=!0;g.Ro(c,!0);X.Z=new g.i_(function(){g.hx(this.WP(),"iv-branding-active")},0,X);
X.Z.start()}},X1k=function(X,c,V){g.YD(X.WP(),"iv-branding-active");
X.B=new g.i_(function(){g.Ro(c,!1);X.J||(V.style.width=g.Eh(0,!0))},250);
X.B.start();X.X=!1},GVk=function(X,c,V,G,n,L,d){this.J=X;
this.U=c;this.qW=V;this.videoData=G;this.logger=n;this.W=L;this.G=d},nbA=function(X,c,V){GN.call(this,X,c,V);
var G=this;this.T=this.isCollapsed=this.C=!1;this.B=5E3;this.G=this.U=this.J=this.X=null;this.D=this.createElement({N:"div",xO:["iv-promo-contents"]});this.Z=new g.i_(function(){G.J.setAttribute("aria-hidden","true");g.Ro(G.U,!1);g.Ro(G.G,!0)},700,this);
g.N(this,this.Z)},d5H=function(X){var c=X.annotation.data;
if(X.annotation.style==="cta")var V=6;else if(X.annotation.style==="video"||X.annotation.style==="playlist")V=7;X.B=c.collapsedelay_ms||X.B;var G=["iv-promo","iv-promo-inactive"];X.WP().setAttribute("aria-hidden","true");X.WP().setAttribute("aria-label","Promotion");X.WP().tabIndex=0;var n=X.annotation.Yc(),L=c.image_url;if(L){var d=X.createElement({N:"div",xO:["iv-promo-img","iv-click-target"]});L=X.createElement({N:"img",K:{src:L,"aria-hidden":"true"}});d.appendChild(L);c.video_duration&&!c.is_live?
(L=X.createElement({N:"span",Y:"iv-promo-video-duration",Uy:c.video_duration}),d.appendChild(L)):c.playlist_length&&(L=X.createElement({N:"span",Y:"iv-promo-playlist-length",Uy:c.playlist_length.toString()}),d.appendChild(L));n&&sY(X,d,n,X.annotation.id,c.session_data,void 0,V)}n?(L=X.createElement({N:"a",Y:"iv-promo-txt"}),g.gD(L,TU(n)),X.J=L):X.J=X.createElement({N:"div",Y:"iv-promo-txt"});switch(X.annotation.style){case "cta":case "website":var h=X.createElement({N:"p",V:[{N:"strong",Uy:c.text_line_1}]});
var A=X.createElement({N:"p",V:[{N:"span",Y:"iv-promo-link",Uy:c.text_line_2}]});if(L=c.text_line_3){G.push("iv-promo-website-card-cta-redesign");var Y=X.createElement({N:"button",xO:["iv-promo-round-expand-icon","ytp-button"]});L=X.createElement({N:"button",xO:["iv-button","iv-promo-button"],V:[{N:"span",Y:"iv-button-content",Uy:L}]});var H=X.createElement({N:"div",Y:"iv-promo-button-container"});H.appendChild(L);n&&sY(X,X.WP(),n,X.annotation.id,c.session_data,void 0,V)}g.hx(X.J,"iv-click-target");
n&&sY(X,X.J,n,X.annotation.id,c.session_data,void 0,V);break;case "playlist":case "video":h=X.createElement({N:"p",V:[{N:"span",Uy:c.text_line_1}]}),A=X.createElement({N:"p",V:[{N:"strong",Uy:c.text_line_2}]}),c.is_live&&(h=A,A=X.createElement({N:"span",xO:["yt-badge","iv-promo-badge-live"],Uy:"LIVE NOW"})),g.hx(X.J,"iv-click-target"),n&&sY(X,X.J,n,X.annotation.id,c.session_data,void 0,V),G.push("iv-promo-video")}h&&X.J.appendChild(h);A&&X.J.appendChild(A);X.D.appendChild(X.J);H&&X.D.appendChild(H);
V=X.createElement({N:"div",Y:"iv-promo-actions"});X.G=X.createElement({N:"button",xO:["iv-promo-expand","ytp-button"]});X.G.title="Expand";X.context.J.listen(X.G,"click",function(a){LHM(X,5E3,a)});
V.appendChild(X.G);g.Ro(X.G,!1);X.context.J.listen(X.WP(),"mouseover",X.ZS_,X);X.context.J.listen(X.WP(),"mouseout",X.Q27,X);X.context.J.listen(X.WP(),"touchend",function(a){LHM(X,5E3,a)});
X.U=X.createElement({N:"button",xO:["iv-promo-close","ytp-button"]});X.U.title="Close";X.context.J.listen(X.U,"click",X.annotation.style==="cta"&&c.text_line_3?X.By7:X.vOO,X);V.appendChild(X.U);g.Ax(X.WP(),G);d&&(g.Gv(X.WP(),d),Y&&d.appendChild(Y));g.Gv(X.WP(),X.D);g.Gv(X.WP(),V)},LHM=function(X,c,V){V.stopPropagation();
yNV(X);hrU(X,c);X.J.focus()},ANh=function(X){X.isCollapsed||X.T||X.X||(g.hx(X.WP(),"iv-promo-collapsed"),X.isCollapsed=!0,X.Z.start())},yNV=function(X){X.Z.stop();
X.isCollapsed&&(g.jk(X.WP(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),X.isCollapsed=!1,X.J&&X.J.removeAttribute("aria-hidden"),g.Ro(X.G,!1),g.Ro(X.U,!0))},hrU=function(X,c){X.X||(X.X=g.em(function(){Yzk(this);
ANh(this)},c,X))},Yzk=function(X){X.X&&(g.NL.clearTimeout(X.X),X.X=null)},jmr=function(X){this.W=X},utU=function(X,c,V){c&&(V?LI(X,c.map(function(G){return g.OV(G,V)})):LI(X,c))},LI=function(X,c,V,G){var n=1,L=void 0,d=-1;
if(V){var h=!1;L=function(){n--;n||h||(clearTimeout(d),h=!0,V())};
d=setTimeout(function(){h=!0;V()},1E3)}c=g.r(c||[]);
for(var A=c.next();!A.done;A=c.next())A=A.value,n++,g.zM(A,L);G&&(n++,G!==0&&X.W.sendVideoStatsEngageEvent(G,L))},H0p=function(X){g.wh.call(this,X);
var c=this;this.G_=this.T=!1;this.loadNumber=0;this.B={};this.logger=new jmr(this.player);this.X=new g.N_(this);this.Z=this.D=null;this.events=new g.N_(this);this.uj=this.C=this.J=null;this.A7=[];g.N(this,this.X);this.X.L(this.player,"onVideoAreaChange",function(){c.publish("onVideoAreaChange")});
this.X.L(this.player,"onHideControls",function(){c.publish("onHideControls")});
this.X.L(this.player,"onShowControls",function(){c.publish("onShowControls")});
this.X.L(this.player,"resize",function(G){c.publish("resize",G)});
this.X.L(this.player,"presentingplayerstatechange",function(G){c.publish("presentingplayerstatechange",G)});
this.subscribe("presentingplayerstatechange",this.Jt,this);this.subscribe("resize",this.gI,this);this.player.j().wy.subscribe("vast_info_card_add",this.QN,this);g.N(this,this.events);this.kO=this.createElement({N:"div",Y:"video-custom-annotations"});this.G=new g.z({N:"div",xO:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.G);g.lc(this.player,this.G.element,4);this.G.hide();this.U=new g.z({N:"div",xO:["ytp-iv-video-content"]});g.N(this,this.U);X=this.createElement({N:"div",Y:"video-annotations"});
X.appendChild(this.kO);this.U.element.appendChild(X);this.Ym()&&this.load();var V=this.createElement({N:"style"});(g.B1("HEAD")[0]||document.body).appendChild(V);this.addOnDisposeCallback(function(){g.dW(V)});
if(X=V.sheet)X.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),X.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),X.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),X.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),X.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),X.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),X.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),X.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),X.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),X.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},auV=function(X){X=X.createElement({N:"div",
xO:["annotation","annotation-type-custom"]});g.Ro(X,!1);return X},$5M=function(X,c){c=!c.isCued()&&!g.B(c,1024);
X.G.Ry(c);X.U.Ry(c)},WHz=function(X,c,V){X.T=!0;
X.Z=g.Ra(c,V)},w1z=function(X,c){for(var V={},G=g.r(c.attributes),n=G.next();!n.done;n=G.next())n=n.value,V[n.name]=n.nodeValue;
for(G=0;G<c.childNodes.length;G++)if(n=c.childNodes[G],g.sD(n)&&n.nodeType==1){if(V[n.tagName])var L=V[n.tagName];else if(n.tagName==="data"){n.childNodes.length>0&&(L=n.childNodes[0].nodeValue,V[n.tagName]=typeof L==="string"?L.trim():L);continue}else L=[],V[n.tagName]=L;n&&n.tagName==="TEXT"?n.childNodes.length===1&&n.childNodes[0].nodeType===3?L.push(n.childNodes[0].nodeValue):L.push(""):n&&L.push(w1z(X,n))}return V},Qm_=function(X){var c=X.player.getVideoData();
if(c.fS){var V=X.player.j().wy.get(c.videoId);if(V){var G={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(n,L,d){n=X.loadNumber;L=c.videoId;X.loaded&&X.loadNumber===n&&X.player.getVideoData().videoId===L&&(d=g.EE(d)&&d.responseXML?d.responseXML:null)&&FHH(X,d)}};
g.n$()&&(G.onFinish=EbU(X,G.onFinish));G.postParams={ic_only:"1"};rNA(G,V);X.T=!0;g.Ra(c.fS,G)}}},rNA=function(X,c){X.method="POST";
X.postParams=X.postParams||{};c.iD&&(X.postParams.ic_coll=c.iD);c.Sd&&(X.postParams.ic_xml=c.Sd);c.w9&&(X.postParams.ic_track=c.w9)},Z0H=function(X){var c=new g.z({N:"div"});
g.Ro(c.element,!1);var V=new pHM(X.player,c.element,d9(X));g.N(V,c);c.uc(X.G.element);V.dA();return V},vbp=function(X,c){var V,G;
if(c=(V=c.getWatchNextResponse())==null?void 0:(G=V.cards)==null?void 0:G.cardCollectionRenderer)X.G_=!0,x5M(X,c),c.headerText&&X.uj&&(V=g.Zt(c.headerText),X.uj.setAttribute("title",V))},d9=function(X){if(!X.C){var c=new n8U(X);
g.N(X,c);var V=new g.eG(X);g.N(X,V);X.C=new GVk(c,V,X.player.j(),X.player.getVideoData(),X.logger,X.player,X.dW)}return X.C},FHH=function(X,c){var V=!1,G=c.getElementsByTagName("annotations");
if(G&&!(G.length<1)&&(G=G[0].getAttribute("itct"))){var n=g.bz();if(n){var L=g.RJ();L&&g.V8(g.Sa)(void 0,n,L,[g.JU(G)])}}c=c.getElementsByTagName("annotation");for(G=0;G<c.length;G++){L=w1z(X,c[G]);n=null;try{if(L){var d=L.id,h=/.+/;var A=typeof d==="string"&&h!=null&&d!=null&&d.match(h)?d:"";var Y=UY(L.type,kVr),H=UY(L.style,obA),a=QcG(L.data),W=a.length!==0?JSON.parse(a):{};var w=L.action;L=eOM;if(w==null)var F=null;else if(g.Kj(w)){h=[];for(var Z=g.r(w),v=Z.next();!v.done;v=Z.next()){var e=L(v.value);
e&&h.push(e)}F=h}else{var m=L(w);F=m?[m]:[]}n=A&&Y?new Jv7(A,Y,H,F,W):null}else n=null}catch(nj){}if(n)if(n.type==="branding"||n.type==="promotion"){L=X;h=n;var t=auV(L),f=null;switch(h.type){case "branding":if(L.player.j().z2)break;L.G.element.appendChild(t);f=new nI(t,d9(L),h);break;case "promotion":g.lc(L.player,t,4),f=new nbA(t,d9(L),h)}f&&f.dA();if(L=f)g.N(X,L),X.B[n.id]=L}else if(n.type==="card"||n.type==="drawer"){X.J||(X.J=Z0H(X),g.N(X,X.J));if(n.type==="card"){t=X.J;var U=(V=n)&&V.data&&
V.data.card_type;n=V.data;if(U)switch(L=n.tracking||{},L={kB:L.impression,click:L.click,close:L.close,NL:L.teaser_impression,PH:L.teaser_click},h=n.tracking_params||{},f=null,U){case "collaborator":V={id:V.id,timestamp:n.timestamp||0,type:n.card_type,teaserText:n.teaser_text,teaserDurationMs:n.teaser_duration_ms,startMs:n.start_ms,autoOpen:n.auto_open||!1,sessionData:n.session_data||{},sponsored:n.sponsored||!1,kR:L,Xf:h.card?g.JU(h.card):null,zZ:h.teaser?g.JU(h.teaser):null,CJ:h.icon?g.JU(h.icon):
null,channelId:n.channel_id,customMessage:n.custom_message?n.custom_message:null,profileImageUrl:n.image_url,title:n.title,metaInfo:n.meta_info,url:uJ({pause_on_navigation:n.pause_on_navigation,target:n.target||"new",value:n.url}),onClickCommand:null};iJ(t,V);break;case "playlist":V={id:V.id,timestamp:n.timestamp||0,type:n.card_type,teaserText:n.teaser_text,teaserDurationMs:n.teaser_duration_ms,startMs:n.start_ms,autoOpen:n.auto_open||!1,sessionData:n.session_data||{},sponsored:n.sponsored||!1,kR:L,
Xf:h.card?g.JU(h.card):null,zZ:h.teaser?g.JU(h.teaser):null,CJ:h.icon?g.JU(h.icon):null,Rn:n.image_url,playlistVideoCount:n.playlist_video_count,customMessage:n.custom_message?n.custom_message:null,title:n.title,metaInfo:n.meta_info,url:uJ({pause_on_navigation:n.pause_on_navigation,target:n.target||"new",value:n.url}),onClickCommand:null};iJ(t,V);break;case "productListing":n.signin_url&&(f=uJ({target:"current",value:n.signin_url}));U=[];for(var C=n.offers||[],K=0;K<C.length;K++)U.push(new l1U(g.XJ(C[K].merchant),
g.XJ(C[K].price)));V={id:V.id,timestamp:n.timestamp||0,type:n.card_type,teaserText:n.teaser_text,teaserDurationMs:n.teaser_duration_ms,startMs:n.start_ms,autoOpen:n.auto_open||!1,sessionData:n.session_data||{},sponsored:n.sponsored||!1,kR:L,Xf:h.card?g.JU(h.card):null,zZ:h.teaser?g.JU(h.teaser):null,CJ:h.icon?g.JU(h.icon):null,imageUrl:n.image_url,displayDomain:n.display_domain?n.display_domain:null,showLinkIcon:!!n.show_link_icon,UE:n.button_icon_url?n.button_icon_url:null,title:n.title,customMessage:n.custom_message?
n.custom_message:null,url:uJ({pause_on_navigation:n.pause_on_navigation,target:n.target||"new",value:n.url}),zz7:f,lDc:n.signin_title?n.signin_title:void 0,Mev:n.signin_message?n.signin_message:void 0,offers:U,onClickCommand:null};iJ(t,V);break;case "simple":V={id:V.id,timestamp:n.timestamp||0,type:n.card_type,teaserText:n.teaser_text,teaserDurationMs:n.teaser_duration_ms,startMs:n.start_ms,autoOpen:n.auto_open||!1,sessionData:n.session_data||{},sponsored:n.sponsored||!1,kR:L,Xf:h.card?g.JU(h.card):
null,zZ:h.teaser?g.JU(h.teaser):null,CJ:h.icon?g.JU(h.icon):null,imageUrl:n.image_url,displayDomain:n.display_domain?n.display_domain:null,showLinkIcon:!!n.show_link_icon,UE:n.button_icon_url?n.button_icon_url:null,title:n.title,customMessage:n.custom_message?n.custom_message:null,url:uJ({pause_on_navigation:n.pause_on_navigation,target:n.target||"new",value:n.url}),onClickCommand:null};iJ(t,V);break;case "video":V={id:V.id,timestamp:n.timestamp||0,type:n.card_type,teaserText:n.teaser_text,teaserDurationMs:n.teaser_duration_ms,
startMs:n.start_ms,autoOpen:n.auto_open||!1,sessionData:n.session_data||{},sponsored:n.sponsored||!1,kR:L,Xf:h.card?g.JU(h.card):null,zZ:h.teaser?g.JU(h.teaser):null,CJ:h.icon?g.JU(h.icon):null,Rn:n.image_url,videoDuration:n.video_duration||null,customMessage:n.custom_message?n.custom_message:null,title:n.title,metaInfo:n.meta_info,isLiveNow:!!n.is_live_now,url:uJ({pause_on_navigation:n.pause_on_navigation,target:n.target||"new",value:n.url}),onClickCommand:null},iJ(t,V)}}else I1p(X.J,n);V=!0}}V&&
(o4(X.player),X.gI())},x5M=function(X,c){var V=!1;
X.J||(X.J=Z0H(X),g.N(X,X.J));for(var G=g.r(c.cards||[]),n=G.next();!n.done;n=G.next())n=n.value,n.cardRenderer&&(NDz(X.J,n.cardRenderer),V=!0);if(V){var L;(L=X.player.getVideoData())!=null&&g.Oq(L)||(V=X.J,G=c.headerText?g.Zt(c.headerText):"",g.h5(V.hX,G),V.T&&V.T.setAttribute("title",G),V.context.videoData.eventId&&(V.eventId=V.context.videoData.eventId),V.Pl=c.trackingParams?g.JU(c.trackingParams):null,V.D=c.closeButton.infoCardIconRenderer.trackingParams?g.JU(c.closeButton.infoCardIconRenderer.trackingParams):
null,V.CJ=c.icon.infoCardIconRenderer.trackingParams?g.JU(c.icon.infoCardIconRenderer.trackingParams):null,X.gI());o4(X.player)}},eri=function(X,c,V,G,n){if(!X.player.j().z2){var L=[];
c.navigationEndpoint&&g.T(c.navigationEndpoint,g.ov)&&g.T(c.navigationEndpoint,g.ov).browseId&&L.push(new v87("openUrl","click",new Z7V("/channel/"+g.T(c.navigationEndpoint,g.ov).browseId,"new",!0,!0)));var d=c.watermark.thumbnails[0];G={channel_name:c.channelName,end_ms:c.endTimeMs,image_height:d.height,image_type:1,image_url:d.url,image_width:d.width,is_mobile:!1,session_data:{annotation_id:V,ei:n,feature:"iv",itct:c.trackingParams,src_vid:G},start_ms:c.startTimeMs};if(c.subscribeButton&&g.T(c.subscribeButton,
g.ej)){G.channel_id=g.T(c.subscribeButton,g.ej).channelId;var h;c=g.T(c.subscribeButton,g.ej);d=n=null;c.subscribed?(c.subscriberCountWithUnsubscribeText&&(n=g.Zt(c.subscriberCountWithUnsubscribeText)),c.subscriberCountText&&(d=g.Zt(c.subscriberCountText))):(c.subscriberCountText&&(n=g.Zt(c.subscriberCountText)),c.subscriberCountWithSubscribeText&&(d=g.Zt(c.subscriberCountWithSubscribeText)));var A,Y=((A=g.T((h=c.signInEndpoint)==null?void 0:h.commandMetadata,g.wB))==null?void 0:A.url)||"";h={subscribeText:g.Zt(c.unsubscribedButtonText),
subscribeCount:n||"",unsubscribeText:g.Zt(c.subscribedButtonText),unsubscribeCount:d||"",enabled:c.enabled||!1,classic:!1,subscribed:c.subscribed||!1,feature:"iv",signInUrl:Y};G.standalone_subscribe_button_data=h}L=new Jv7(V,"branding","branding",L,G);h=auV(X);X.G.element.appendChild(h);L=new nI(h,d9(X),L);L.dA();g.N(L,L);X.B[V]=L}},EbU=function(X,c){return function(){var V=g.bO.apply(0,arguments);
X.vl()||X.A7.push(g.u_.jV(function(){c.apply(null,g.x(V))}))}},JNA=function(X){return X==="annotation-editor"||X==="live-dashboard"};
g.ox.prototype.b2=g.Gt(45,function(X,c){var V=g.bV(this.X2());V&&V.b2(X,c)});
var JY={},me=null;g.VA(bJ,g.ab);g.y=bJ.prototype;g.y.getDuration=function(){return this.duration};
g.y.play=function(X){if(X||this.J==0)this.progress=0,this.coords=this.G;else if(this.isPlaying())return!1;R4(this);this.startTime=X=g.Xr();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.X=this.startTime;this.progress||this.Qh();this.iW("play");this.isPaused()&&this.iW("resume");this.J=1;var c=g.DS(this);c in JY||(JY[c]=this);SWr();idt(this,X);return!0};
g.y.stop=function(X){R4(this);this.J=0;X&&(this.progress=1);qWV(this,this.progress);this.onStop();this.TP()};
g.y.pause=function(){this.isPlaying()&&(R4(this),this.J=-1,this.iW("pause"))};
g.y.R2=function(){this.J==0||this.stop(!1);this.iW("destroy");bJ.IP.R2.call(this)};
g.y.destroy=function(){this.dispose()};
g.y.Am=function(){this.iW("animate")};
g.y.iW=function(X){this.dispatchEvent(new XHH(X,this))};
g.VA(XHH,g.f_);g.VA(tY,bJ);tY.prototype.U=function(){};
tY.prototype.Am=function(){this.U();tY.IP.Am.call(this)};
tY.prototype.TP=function(){this.U();tY.IP.TP.call(this)};
tY.prototype.Qh=function(){this.U();tY.IP.Qh.call(this)};
g.VA(cvr,tY);cvr.prototype.U=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.E(n8U,g.I);g.y=n8U.prototype;g.y.listen=function(X,c,V,G){V=(0,g.iO)(V,G||this.G);X=g.ol(X,c,V);this.J.push(X);return X};
g.y.OC=function(X,c,V,G){V=(0,g.iO)(V,G||this.G);X=C17(X,c,V);this.J.push(X);return X};
g.y.Hd=function(X){g.eP(X);g.iA(this.J,X)};
g.y.removeAll=function(){g.eP(this.J);this.J.length=0};
g.y.R2=function(){this.removeAll();g.I.prototype.R2.call(this)};g.E(yvz,g.wh);g.y=yvz.prototype;g.y.load=function(){g.wh.prototype.load.call(this);if(!MF(this)){var X=g.ayw(this.player.getVideoData());X?(X=doG(X,hOt(this)),go(this,X,!1)):AvA(this)}};
g.y.unload=function(){go(this,null);this.X&&(this.X.abort(),this.X=null);g.wh.prototype.unload.call(this)};
g.y.AC=function(X,c){return MF(this)?X==="loadCustomEndscreenRenderer"?(X=doG(c,"new"),go(this,X),!0):null:null};
g.y.getOptions=function(){return MF(this)?["loadCustomEndscreenRenderer"]:[]};
g.y.Ky=function(){if(this.endscreen&&this.endscreen.elements){var X=this.player.getVideoContentRect();if(X&&X.width!==0&&X.height!==0){var c=this.player.getPlayerSize();if(c&&c.width!==0&&c.height!==0){var V=X.width/X.height;var G=0;for(var n=-1,L=0;L<m5A.length;L++){var d=Math.abs(c.width-m5A[L]);if(n===-1||G>=d)n=L,G=d}G=Rrp[n];this.U&&g.ao(this.U.element,"outline-width",Math.max(c.width,c.height)+"px");for(c=0;c<this.endscreen.elements.length;++c)if(L=this.endscreen.elements[c].id,n=this.G[L],
d=this.B[L],n&&d){var h=d.width*V/d.aspectRatio,A=Math.round(d.width*X.width);L=Math.round(h*X.height);var Y=X.left+Math.round(d.left*X.width),H=X.top+Math.round(d.top*X.height);g.JS(n.element,A,L);g.rS(n.element,Y,H);g.jk(n.element,b0A);A>256||L>256?g.hx(n.element,"ytp-ce-large-round"):A>96||L>96?g.hx(n.element,"ytp-ce-medium-round"):g.hx(n.element,"ytp-ce-small-round");g.jk(n.element,t9r);A=d.left+d.width/2;d=d.top+h/2;g.hx(n.element,A<=.5&&d<=.5?"ytp-ce-top-left-quad":A>.5&&d<=.5?"ytp-ce-top-right-quad":
A<=.5&&d>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.jk(n.element,Rrp);g.hx(n.element,G);(n=g.sz(document,"div","ytp-ce-expanding-overlay-body",n.element)[0])&&g.ao(n,"height",L+"px")}}}}};
g.y.onCueRangeEnter=function(X){if(this.endscreen)if(X.getId()==="ytp-ce-in-endscreen")NF(this,this.endscreen.impressionUrls),(X=g.bz())&&this.endscreen.visualElement&&g.dP(X,this.endscreen.visualElement),this.J&&(g.hx(this.J,"ytp-ce-element-show"),this.J.removeAttribute("aria-hidden"),this.player.Xr()?g.hx(this.J,"ytp-ce-hide-button-lower"):g.YD(this.J,"ytp-ce-hide-button-lower"));else{X=X.getId().substring(15);var c=this.G[X],V=this.B[X];g.hx(c.element,"ytp-ce-element-show");c.element.removeAttribute("aria-hidden");
c=this.player.getRootNode();g.hx(c,"ytp-ce-shown");NF(this,V.impressionUrls);(c=g.bz())&&g.dP(c,V.visualElement);this.player.j().D&&this.player.z_("endscreenelementshown",X)}};
g.y.onCueRangeExit=function(X){if(X.getId()==="ytp-ce-in-endscreen")this.J&&(g.YD(this.J,"ytp-ce-element-show"),this.J.setAttribute("aria-hidden","true"));else{X=X.getId().substring(15);var c=this.G[X];g.YD(c.element,"ytp-ce-element-show");c.element.setAttribute("aria-hidden","true");c=this.player.getRootNode();g.YD(c,"ytp-ce-shown");this.player.j().D&&this.player.z_("endscreenelementhidden",X)}};
g.y.EMR=function(X){var c=this;X.target===window&&(new g.i_(function(){for(var V=g.r(Object.values(c.G)),G=V.next();!G.done;G=V.next())g.jk(G.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.y.Ry=function(X){for(var c=g.r(Object.values(this.G)),V=c.next();!V.done;V=c.next())V=V.value,X?V.element.setAttribute("hidden",""):V.element.removeAttribute("hidden")};
g.y.APO=function(X){this.J&&this.player.getRootNode().removeChild(this.J);X&&(g.hx(X,"ytp-ce-hide-button-container"),this.J=X,g.lc(this.player,this.J,4))};
var m5A=[346,426,470,506,570,640,853,1280,1920],Rrp="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),t9r=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],b0A=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var xoz={Ul2:"current",To7:"new"};var ksk={CLOSE:"close",M_y:"openUrl",SUBSCRIBE:"subscribe"},o8A={gR_:"click",CLOSE:"close",FuR:"hidden",p5y:"rollOut",Yty:"rollOver",jCh:"shown"};Jv7.prototype.Yc=function(){var X=moh(this,function(c){return c.type==="openUrl"&&c.url!=null});
return X?X.url:null};
var obA={qcv:"anchored",tI:"branding",CHANNEL:"channel",RE7:"cta",Nu2:"highlightText",Jvl:"label",PLAYLIST:"playlist",POPUP:"popup",oqR:"speech",SUBSCRIBE:"subscribe",FhW:"title",VIDEO:"video",Ms2:"website"},kVr={tI:"branding",eyK:"card",HrK:"drawer",a_K:"highlight",xbK:"marker",WEW:"promotion",TEXT:"text",ws7:"widget"};g.E(K4,g.I);g.y=K4.prototype;g.y.addCueRange=function(X,c,V,G,n){X=new g.hC(X,c,{id:V,namespace:"annotations_module"});G&&this.LS.set(X,G);n&&this.fS.set(X,n);this.context.W.Gr([X],1)};
g.y.dA=function(){this.context.G.subscribe("resize",this.rq,this)};
g.y.WP=function(){return this.element};
g.y.hm=function(X,c,V,G,n,L){if(this.qE)return!1;L&&(L.stopPropagation(),L.preventDefault());this.navigate(X,V,G,n);return!1};
g.y.show=function(){};
g.y.hide=function(){};
g.y.destroy=function(){g.dW(this.WP())};
g.y.rq=function(){};
g.y.navigate=function(X,c,V,G){var n=this,L=TU(X);if(L){var d=g8V(L,X.target),h=function(){X.J&&n.context.W.pauseVideo();var A=n.context.videoData.O5||!1,Y=g.h3(L||"");A&&Y&&(Y.v||Y.list)?n.context.W.Tf(Y.v,c,Y.list,!1):g.sS(L||"",d==="current"?"_top":void 0,c)};
d==="new"&&(h(),h=null);LI(this.context.logger,V,h,G);Mvz(L)||(V=g.bz(),G=c.itct,V&&G&&g.Ay(V,g.JU(G)))}};
g.y.R2=function(){this.LS.clear();this.fS.clear();g.I.prototype.R2.call(this)};
g.y.createElement=function(X){X=new g.z(X);g.N(this,X);return X.element};g.E(pHM,K4);g.y=pHM.prototype;g.y.sQ=function(){this.A7&&iJ(this,this.A7)};
g.y.isAvailable=function(){var X;if(X=!!this.cards.length)(X=this.W.getRootNode())?(X=g.mn(X),X=173<X.width&&173<X.height):X=!1;return X};
g.y.rq=function(){var X=this.isAvailable();g.Ro(this.WP(),X);g.H6(this.context.W.getRootNode(),g.BV.IV_DRAWER_ENABLED,X);o4(this.W)};
g.y.destroy=function(){this.W.b2(!1);try{this.W.getRootNode().removeChild(this.X)}catch(X){}g.Y_(this.G_);g.O1(this.QK);this.YO&&this.YO.dispose();this.Z&&this.Z.dispose();K4.prototype.destroy.call(this)};
g.y.uD=function(){var X=this;this.context.J.listen(g.C0("iv-drawer-close-button",this.X),"click",this.uO,this);this.context.J.listen(this.G,"touchend",function(){X.NW.start()});
this.context.J.listen(this.G,"scroll",this.lO,this);this.context.G.subscribe("onHideControls",function(){X.Hl=!0});
this.context.G.subscribe("onShowControls",function(){X.Hl=!1});
this.context.G.subscribe("onVideoAreaChange",function(){X.Hl=g.yO(X.W.getRootNode(),"ytp-autohide")});
this.G_.push(g.AI("iv-button-shown",this.DEc,this));this.G_.push(g.AI("iv-button-hidden",this.SMS,this));zOH(this)};
g.y.findLastIndex=function(X){if(this.cards.length===0)return 0;var c=g.Ct(this.cards,function(V){return X.MN.startMs>V.MN.startMs||X.MN.startMs===V.MN.startMs&&X.MN.timestamp>=V.MN.timestamp?!0:!1});
return c===-1?0:c+1};
g.y.uO=function(){if(this.U){LI(this.context.logger,VL(this).kR.close);var X=g.bz();X&&this.D&&g.Ay(X,this.D);Sd(this)}};
g.y.lO=function(){g.H6(this.X,"iv-drawer-scrolled",this.G.scrollTop>0)};
g.y.DEc=function(){var X=g.bz(),c=VL(this);c=c?c.CJ:this.CJ;X&&c&&g.y0(X,[c])};
g.y.SMS=function(){var X=g.bz(),c=VL(this);c=c?c.CJ:this.CJ;X&&c&&g.hy(X,[c])};
g.y.qp=function(){var X=VL(this);LI(this.context.logger,X.kR.NL);var c=g.bz();if(c&&X)if(this.W.S("web_infocards_teaser_show_logging_fix")){var V=[];X.zZ&&V.push(X.zZ);X.CJ&&V.push(X.CJ);V.length>0&&g.y0(c,V)}else g.y0(c,[X.zZ,X.CJ])};
g.y.eoR=function(){var X=g.bz(),c=VL(this);X&&c&&g.hy(X,[c.zZ])};
g.y.o_=function(X){var c=VL(this),V=g.bz();this.J?X?(X=this.context.logger,LI(X,c.kR.PH),X.W.sendVideoStatsEngageEvent(4,void 0),V&&c.zZ&&g.Ay(V,c.zZ)):(X=this.context.logger,LI(X,c.kR.PH),X.W.sendVideoStatsEngageEvent(4,void 0),V&&c.CJ&&g.Ay(V,c.CJ)):(X=this.context.logger,LI(X,c.kR.PH),X.W.sendVideoStatsEngageEvent(4,void 0),V&&this.CJ&&g.Ay(V,this.CJ))};g.E(GN,K4);GN.prototype.dA=function(){K4.prototype.dA.call(this);i7h(this)};
GN.prototype.show=function(){K4.prototype.show.call(this);var X=g.bz(),c=this.annotation.data;X&&c&&(c=c.session_data)&&g.y0(X,[g.JU(c.itct)])};
GN.prototype.hide=function(){K4.prototype.hide.call(this);var X=g.bz(),c=this.annotation.data;X&&c&&(c=c.session_data)&&g.hy(X,[g.JU(c.itct)])};g.E(nI,GN);
nI.prototype.show=function(){if(!this.isActive){GN.prototype.show.call(this);if(!this.D){g.hx(this.WP(),"iv-branding");var X=this.annotation.data;this.G=this.createElement({N:"img",xO:["branding-img","iv-click-target"],K:{"aria-label":"Channel watermark",src:X.image_url,width:X.image_width,height:X.image_height}});g.Ro(this.G,!1);var c=this.createElement({N:"button",xO:["branding-img-container","ytp-button"]});c.appendChild(this.G);this.WP().appendChild(c);var V=this.annotation.Yc();V&&sY(this,c,
V,this.annotation.id,X.session_data);this.context.W.S("disable_branding_context")||V9p(this,X);this.D=!0}g.Ro(this.WP(),!0);this.isActive=!0;if(this.G){try{q9i(this,this.G)}catch(G){}g.hx(this.context.W.getRootNode(),"ytp-branding-shown");this.context.W.getRootNode().style.setProperty("--branding-image-width",this.G.getAttribute("width")+"px")}}};
nI.prototype.hide=function(){this.isActive&&(GN.prototype.hide.call(this),g.Ro(this.WP(),!1),this.isActive=!1,g.YD(this.context.W.getRootNode(),"ytp-branding-shown"))};
nI.prototype.destroy=function(){this.J&&(this.J.dispose(),this.J=null);g.YD(this.context.W.getRootNode(),"ytp-branding-shown");GN.prototype.destroy.call(this)};g.E(nbA,GN);g.y=nbA.prototype;g.y.show=function(){this.isActive||(GN.prototype.show.call(this),this.C||(d5H(this),this.C=!0),g.Ro(this.WP(),!0),g.em(function(){g.YD(this.WP(),"iv-promo-inactive")},100,this),this.WP().removeAttribute("aria-hidden"),this.isActive=!0,Yzk(this),yNV(this),hrU(this,this.B))};
g.y.hide=function(){this.isActive&&(g.hx(this.WP(),"iv-promo-inactive"),this.isActive=!1,this.WP().setAttribute("aria-hidden","true"))};
g.y.hm=function(X,c,V,G,n,L){return this.isCollapsed?!1:GN.prototype.hm.call(this,X,c,V,G,n,L)};
g.y.ZS_=function(X){this.T=!0;LHM(this,500,X)};
g.y.Q27=function(){this.T=!1;ANh(this)};
g.y.vOO=function(X){X.stopPropagation();this.hide()};
g.y.By7=function(X){X.stopPropagation();Yzk(this);this.isCollapsed=!0;g.hx(this.WP(),"iv-promo-collapsed-no-delay");this.Z.start()};
g.y.destroy=function(){this.Z.dispose();GN.prototype.destroy.call(this)};g.E(H0p,g.wh);g.y=H0p.prototype;g.y.AC=function(X,c){if(!JNA(this.player.j().playerStyle))return null;switch(X){case "loadCustomAnnotationsXml":return(X=g.Bx(c))&&FHH(this,X),!0;case "removeCustomAnnotationById":return c&&this.J&&(TDi(this.J,c),o4(this.player)),!0}return null};
g.y.getOptions=function(){return JNA(this.player.j().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.y.Ym=function(){var X=this.player.j(),c=this.player.getVideoData(),V=X.annotationsLoadPolicy||c.annotationsLoadPolicy;return g.cO(c)||this.player.isMutedByEmbedsMutedAutoplay()?!1:V===1&&!c.I_||X.wy.get(c.videoId)||g.lN(c)||g.MO(c)?!0:!1};
g.y.gI=function(){if(this.U){var X=this.player.CS().getVideoContentRect(!0);g.JS(this.U.element,X.width,X.height);g.rS(this.U.element,X.left,X.top)}if(this.J){var c=this.player.i4();X=this.J;c=c.width;g.H6(X.X,"iv-drawer-small",c<=426);g.H6(X.X,"iv-drawer-big",c>=1280)}};
g.y.Jt=function(X){$5M(this,X.state);g.B(X.state,2)&&(this.Xr()&&this.hc()&&this.player.getPresentingPlayerType()!==2&&this.LG(!1),this.b2(!1))};
g.y.load=function(){function X(d){var h=c.loadNumber;c.Z=null;c.loaded&&c.loadNumber===h&&c.player.getVideoData().videoId===G&&(d=g.EE(d)&&d.responseXML?d.responseXML:null)&&(FHH(c,d),g.hx(c.player.getRootNode(),"iv-module-loaded"))}
var c=this;g.wh.prototype.load.call(this);$5M(this,this.player.getPlayerStateObject());this.loadNumber++;var V=this.player.getVideoData(),G=V.videoId;g.n$()&&(X=EbU(this,X));var n={format:"XML",onFinish:X,onError:function(){c.Z=null},
urlParams:{}};V.isPharma&&(n.urlParams.pharma="1");n.method="POST";n.withCredentials=!0;var L=this.player.j().wy.get(G);L&&rNA(n,L);L=L&&(L.Sd||L.iD);if(!V.w7||L)V.fS?WHz(this,V.fS,n):(this.D=function(){if(!c.T)c.onVideoDataChange(n);var d=c.player.getVideoData();(d==null?0:g.Oq(d))&&!c.G_&&vbp(c,d)},this.player.addEventListener("videodatachange",this.D));
g.lc(this.player,this.U.element,4);this.gI();(L=g.lN(V))&&x5M(this,L);(L=g.MO(V))&&L.featuredChannel&&eri(this,L.featuredChannel,L.annotationId||"branding",V.videoId||null,V.eventId||null);this.uj=g.C0("ytp-cards-button",this.player.getRootNode());g.Oq(V)&&vbp(this,V)};
g.y.onVideoDataChange=function(X){var c=this.player.getVideoData();c.fS&&WHz(this,c.fS,X)};
g.y.unload=function(){this.player.EH("annotations_module");for(var X=g.r(Object.keys(this.B)),c=X.next();!c.done;c=X.next())this.B[c.value].destroy();this.C=null;this.J&&(this.J.destroy(),this.J=null,o4(this.player));this.T=!1;this.Z&&(this.Z.abort(),this.Z=null);this.G_=!1;this.B={};this.G.hide();g.wh.prototype.unload.call(this);this.U.detach();this.D&&(this.player.removeEventListener("videodatachange",this.D),this.D=null)};
g.y.QN=function(X){X===this.player.getVideoData().videoId&&(this.loaded?Qm_(this):this.load())};
g.y.Xr=function(){var X;return((X=this.J)==null?void 0:X.isAvailable())||this.G_};
g.y.hc=function(){return!!this.J&&this.J.U};
g.y.LG=function(X,c,V){c=c===void 0?!1:c;this.Xr();this.J&&(X?V?D_(this.J,V,c):D_(this.J,"YOUTUBE_DRAWER_AUTO_OPEN",c):Sd(this.J))};
g.y.b2=function(X,c){this.player.publish(X?"cardsteasershow":"cardsteaserhide",c)};
g.y.R2=function(){this.player.j().wy.unsubscribe("vast_info_card_add",this.QN,this);g.YD(this.player.getRootNode(),g.BV.IV_DRAWER_OPEN);for(var X=this.A7,c=g.u_,V=0,G=X.length;V<G;V++)c.IT(X[V]);this.A7.length=0;g.wh.prototype.R2.call(this)};
g.y.createElement=function(X){X=new g.z(X);g.N(this,X);return X.element};g.Wr("annotations_module",H0p);g.Wr("creatorendscreen",yvz);})(_yt_player);
