(function(g){var window=this;'use strict';var M9G=function(X,c,V){g.O(function(G){X.J=g.Ra(c,V);g.Ql(G)})},yL=function(X){X.isActive()||X.start()},gbV=function(X,c){return c?X.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},fuU=function(X){return g.Dv(X)||X.S("web_enable_caption_language_preference_stickiness")},p1k=function(X,c){var V=new g.a6;
V.languageCode=X.languageCode;V.languageName=X.languageName;V.name=X.name;V.displayName=X.displayName;V.kind=X.kind;V.isDefault=!1;V.J=X.J;V.isTranslateable=X.isTranslateable;V.vssId=X.vssId;V.url=X.url;V.translationLanguage=c;X.xtags&&(V.xtags=X.xtags);X.captionId&&(V.captionId=X.captionId);return V},Iuh=function(X,c){var V,G,n;
return g.O(function(L){if(L.J==1)return V=X+"|"+c,g.b(L,g.V5(),2);if(L.J!=3){G=L.G;if(!G)throw g.ku("gct");return g.b(L,g.t4(G),3)}n=L.G;return L.return(n.get("captions",V))})},Nnp=function(X,c,V){Iuh(X,c).then(function(G){G&&V(G.trackData,new g.a6(G.metadata))})},uJM=function(X){if(!U57.test(X))throw Error("'"+X+"' is not a valid hex color");
X.length==4&&(X=X.replace(Tnk,"#$1$1$2$2$3$3"));X=X.toLowerCase();X=parseInt(X.slice(1),16);return[X>>16,X>>8&255,X&255]},PUp=function(){var X=void 0;
X=X===void 0?{}:X;var c="suggest_correction"in g.jAz?g.jAz.suggest_correction:"Edit caption";c=c||"";var V={},G;for(G in X){V={zQ:V.zQ};V.zQ=G;var n=function(L){return function(){return String(X[L.zQ])}}(V);
c=c.replace(new RegExp("\\$\\{"+V.zQ+"\\}","gi"),n);c=c.replace(new RegExp("\\$"+V.zQ,"gi"),n)}return c},zrr=function(){return g.pv("yt-player-caption-display-settings")},h1=function(){this.segments=[]},BnU=function(X,c){var V=g.yk(X.segments,c);
V>=0||V<0&&(-V-1)%2===1||(V=-V-1,V>0&&c-X.segments[V-1]===1&&V<X.segments.length&&X.segments[V]-c===1?(g.SV(X.segments,V),g.SV(X.segments,V-1)):V>0&&c-X.segments[V-1]===1?X.segments[V-1]=c:V<X.segments.length&&X.segments[V]-c===1?X.segments[V]=c:(g.LS(X.segments,V,0,c),g.LS(X.segments,V+1,0,c)))},KHz=function(X,c,V,G,n,L){g.I.call(this);
this.policy=X;this.player=c;this.G_=V;this.T=G;this.Z=n;this.C=L;this.X=new h1;this.B=-1;this.U=this.G=this.J=null;this.A7=0;this.D=new g.i_(this.O1,1E3,this);this.events=new g.N_(this);g.N(this,this.D);g.N(this,this.events);this.events.L(c,"SEEK_COMPLETE",this.A8);this.A8();this.O1()},smA=function(X){return X.J&&X.J.B?X.J.B+X.player.h1()<X.player.getCurrentTime():!1},CUU=function(X,c){if(X.policy.B5&&X.player.Cj()){var V=g.u$(c,X.policy,{});
V.set("pot",X.player.Cj());V=V.Yc()}else V=g.u$(c,X.policy,{}).Yc();var G={format:"RAW",withCredentials:!0};if(X.policy.wy){G.method="POST";var n=c.X;n&&Object.keys(n).length>0?G.postBody=g.Yw(n,g.XT):G.postBody=(0,g.Zl)([120,0])}X.Z&&(G.responseType="arraybuffer");var L=++X.A7,d=(0,g.bE)();X.U=g.l9(V,G,3,100).then(function(h){if(X.policy.iU&&L%100===1){var A=(0,g.bE)();X.player.Oy("caprsp",{rn:L,ms:A-d,kb:(h.xhr.responseText.length/1024).toFixed()})}a:{h=h.xhr;X.vl();if(X.G){var Y=!(X.Z?h.response:
h.responseText)||h.status>=400;if(A=g.fGU(h)){h=g.u$(X.G,X.policy,{});X.G.tZ(h,A);CUU(X,X.G);break a}Y?X.player.Oy("capfail",{status:h.status}):(X.player.X9().vD("fcb_r"),A=X.G.KS[0].Bl,X.T!=null&&X.B!==A&&(Y=X.G.KS[0],X.Z?X.T(h.response,(Y.startTime+X.player.h1())*1E3):X.T(h.responseText,(Y.startTime+X.player.h1())*1E3),X.B=A))}X.G=null;X.U=null}}).Vr(function(h){X.G=null;
X.U=null;var A;X.player.Oy("capfail",{rn:L,status:(A=h.xhr)==null?void 0:A.status})});
X.G=c;BnU(X.X,X.G.KS[0].Bl)},A1=function(X,c){g.Eb.call(this,c);
this.J=X;this.W=c;this.U=null;this.B=!1;this.logger=new g.LD("caps");this.D=g.RX(this.W.j())&&!this.J.isManifestless},Sz_=function(X,c){var V=[],G;
for(G in X.J.J)if(X.J.J.hasOwnProperty(G)){var n=X.J.J[G];if(g.QD(n,c||null)){var L=n.info.id,d=L,h="."+L,A="",Y="";if(n=n.info.captionTrack)L=n.languageCode,d=n.displayName,h=n.vssId,A=n.kind,Y=n.id;else{n=L;var H=g.gdt.get(n);H==null&&(H=D5V[n]||D5V[n.replace(/-/g,"_")],g.gdt.set(n,H));n=H;d=n||d}V.push(new g.a6({id:G,languageCode:L,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:A,captionId:Y}))}}return V},i0G=function(X,c){return c!=null&&c in X.J.J?X.J.J[c]:null},
qzr=function(X,c,V){var G=[],n;
for(n in X.J.J)if(X.J.J.hasOwnProperty(n)){var L=X.J.J[n];if(g.QD(L,V||null)){var d=L.info.captionTrack;d&&d.languageCode===c&&G.push(L)}}return G.length?G[0]:null},Yh=function(X,c,V,G,n,L,d,h,A,Y){var H=Y.isInline()&&!0,a={};
Object.assign(a,c);Object.assign(a,X.params);Object.assign(a,V);var W={};Object.assign(W,c.F4);X.params.F4&&Object.assign(W,X.params.F4);Object.assign(W,V.F4);H&&(a.windowOpacity=.6,W.backgroundOpacity=0);a.F4=W;var w=a.d1===1,F=[{N:"span",Y:"captions-text",K:{style:"word-wrap: normal; display: block;"}}],Z,v,e;(h=h.lc("caption_edit_on_hover")&&((Z=Y.getVideoData().getPlayerResponse())==null?void 0:(v=Z.captions)==null?void 0:(e=v.playerCaptionsTracklistRenderer)==null?void 0:e.openTranscriptCommand))&&
F.unshift({N:"button",Y:"caption-edit",K:{tabindex:"0","aria-label":PUp()},V:[{N:"svg",K:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{N:"path",K:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.z.call(this,{N:"div",Y:"caption-window",K:{id:"caption-window-"+X.id,dir:w?"rtl":"ltr",tabindex:"0",lang:a.lang},V:F});var m=
this;this.D=[];this.Pl=!1;this.G=X;this.Hl=this.wy=null;this.playerWidth=L;this.playerHeight=d;this.T=null;this.maxWidth=L*.96;this.maxHeight=d*.96;this.J=a;this.G2=V;this.A7=c;this.X=this.I2("captions-text");this.Ly=this.X.style.getPropertyValue("box-decoration-break")!==""||this.X.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.YO=XWA(G,n,L,d);this.Od=A;h&&(this.B=this.I2("caption-edit"),this.L(this.B,"click",function(){m.Od()}));
this.type=0;this.T_=this.YO*c57(W);this.NE=H;X=new g.T5(this.element,!0);g.N(this,X);X.subscribe("dragstart",this.At,this);X.subscribe("dragmove",this.GR,this);X.subscribe("dragend",this.OJ,this);this.qE=this.yK=this.hX=this.o2=0;X="";this.J.windowOpacity&&(X=uJM(this.J.windowColor),X="rgba("+X[0]+","+X[1]+","+X[2]+","+this.J.windowOpacity+")");c={"background-color":X,display:this.J.isVisible===!1?"none":"","text-align":V6M[this.J.textAlign]};this.Ly&&(c["border-radius"]=X?this.T_/8+"px":"");(this.U=
this.G.params.d1===2||this.G.params.d1===3)&&GvV(this,this.element);g.ao(this.element,c);if(H){var t;(t=this.element.parentElement)==null||t.style.setProperty("--caption-window-color",X)}switch(this.J.xA){case 0:case 1:case 2:g.hx(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.hx(this.element,"ytp-caption-window-bottom")}},GvV=function(X,c){var V="vertical-rl";
X.J.pZ===1&&(V="vertical-lr");g.wI&&(V=V==="vertical-lr"?"tb-lr":"tb-rl");g.ao(c,"-o-writing-mode",V);g.ao(c,"-webkit-writing-mode",V);g.ao(c,"writing-mode",V);g.ao(c,"text-orientation","upright");g.hx(c,"ytp-vertical-caption");X.G.params.d1===3&&(g.ao(c,"text-orientation",""),g.ao(c,"transform","rotate(180deg)"))},c57=function(X){var c=1+.25*(X.fontSizeIncrement||0);
if(X.offset===0||X.offset===2)c*=.8;return c},nEH=function(X,c){var V={},G=c.background?c.background:X.J.F4.background;
if(c.backgroundOpacity!=null||c.background){var n=c.backgroundOpacity!=null?c.backgroundOpacity:X.J.F4.backgroundOpacity;G=uJM(G);V.background="rgba("+G[0]+","+G[1]+","+G[2]+","+n+")";X.Ly&&(V["box-decoration-break"]="clone",V["border-radius"]=X.T_/8+"px")}if(c.fontSizeIncrement!=null||c.offset!=null)V["font-size"]=X.YO*c57(c)+"px";G=1;n=c.color||X.J.F4.color;if(c.color||c.textOpacity!=null)n=uJM(n),G=c.textOpacity==null?X.J.F4.textOpacity:c.textOpacity,n="rgba("+n[0]+","+n[1]+","+n[2]+","+G+")",
V.color=n,V.fill=n;var L=c.charEdgeStyle;L===0&&(L=void 0);if(L){n="rgba(34, 34, 34, "+G+")";var d="rgba(204, 204, 204, "+G+")";c.Dx&&(d=n=c.Dx);var h=X.YO/16/2,A=Math.max(h,1),Y=Math.max(2*h,1),H=Math.max(3*h,1),a=Math.max(5*h,1);G=[];switch(L){case 4:for(;H<=a;H+=h)G.push(Y+"px "+Y+"px "+H+"px "+n);break;case 1:Y=window.devicePixelRatio>=2?.5:1;for(L=A;L<=H;L+=Y)G.push(L+"px "+L+"px "+n);break;case 2:G.push(A+"px "+A+"px "+d);G.push("-"+A+"px -"+A+"px "+n);break;case 3:for(H=0;H<5;H++)G.push("0 0 "+
Y+"px "+n)}V["text-shadow"]=G.join(", ")}n="";switch(c.fontFamily){case 1:n='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:n='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:n='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:n='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:n='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:n=g.sE()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:n='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}n&&(V["font-family"]=n);n=c.offset;n==null&&(n=X.J.F4.offset);switch(n){case 0:V["vertical-align"]="sub";break;case 2:V["vertical-align"]="super"}c.fontFamily===7&&(V["font-variant"]="small-caps");c.bold&&(V["font-weight"]="bold");c.italic&&(V["font-style"]="italic");c.underline&&(V["text-decoration"]=
"underline");c.zRO&&(V.visibility="hidden");c.Uj===1&&X.U&&(V["text-combine-upright"]="all",V["text-orientation"]="mixed",n=g.q7||g.xu,X.G.params.d1===3?V.transform=n?"rotate(90deg)":"rotate(180deg)":n&&(V.transform="rotate(-90deg)"));if(c.DG===1||c.DG===2||c.DG===3||c.DG===4||c.DG===5)if(g.q7)V["font-weight"]="bold";else switch(V["text-emphasis-style"]="filled circle",V["text-emphasis-color"]="currentcolor",V["webkit-text-emphasis"]="filled circle",c.DG){case 4:case 3:V["text-emphasis-position"]=
"under left";V["webkit-text-emphasis-position"]="under left";break;case 5:case 2:V["text-emphasis-position"]="over right",V["webkit-text-emphasis-position"]="over right"}return V},jl=function(X){X=X.split("px");
return X.length>0?(X=Number(X[0]))?X:0:0},L6_=function(X){X.T=g.cW("SPAN");
g.ao(X.T,{display:"block"});g.hx(X.T,"caption-visual-line");X.X.appendChild(X.T)},djM=function(X,c){var V=g.cW("SPAN");
g.ao(V,{display:"inline-block","white-space":"pre-wrap"});g.ao(V,nEH(X,c));V.classList.add("ytp-caption-segment");X.T.appendChild(V);V.previousElementSibling&&(g.ao(V.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ao(V,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return V},y5t=function(X,c,V){X.Pl=X.Pl||!!V;
var G={};Object.assign(G,X.J.F4);Object.assign(G,V||c.J);Object.assign(G,X.G2.F4);(V=!X.T)&&L6_(X);for(var n=X.wy&&X.Hl&&g.Oz(G,X.Hl)?X.wy:djM(X,G),L=typeof c.text==="string",d=L?c.text.split("\n"):[c.text],h=0;h<d.length;h++){var A=h>0||!c.append,Y=d[h];A&&!V?(L6_(X),n=djM(X,G)):A&&V&&(V=!1);Y&&(n.appendChild(L?g.Vj(Y):Y),L||Y.tagName!=="RUBY"||Y.childElementCount!==4||g.q7||!g.WE(Y.children[2],"text-emphasis")||(A=X.U?"padding-right":"padding-top",g.WE(Y.children[2],"text-emphasis-position")&&(A=
X.U?"padding-left":"padding-bottom"),g.S9?g.ao(n,A,"1em"):g.ao(n,A,"0.5em")))}X.Hl=G;X.wy=n;X.D.push(c)},XWA=function(X,c,V,G){var n=c/360*16;
c>=X&&(X=640,G>V*1.3&&(X=480),n=V/X*16);return n},A5A=function(){this.U=this.time=this.mode=this.G=0;
this.X=new hTz(this);this.Z=new hTz(this);this.J=[];this.clear()},jNA=function(X,c,V){if(X===255&&c===255||!X&&!c)return{T5:X,
TX:c,result:0};X=Y_M[X];c=Y_M[c];if(X&128){var G;if(G=!(c&128))G=c,G=V.d$()&&V.TX===G;if(G)return{T5:X,TX:c,result:1}}else if(c&128&&1<=X&&X<=31)return{T5:X,TX:c,result:2};return{T5:X,TX:c,result:3}},ach=function(X,c,V,G){c===255&&V===255||!c&&!V?(++X.U===45&&X.reset(),X.X.G.clear(),X.Z.G.clear()):(X.U=0,H_V(X.X,c,V,G))},$j7=function(X,c){X.J.sort(function(n,L){var d=n.time-L.time;
return d===0?n.order-L.order:d});
for(var V=g.r(X.J),G=V.next();!G.done;G=V.next())G=G.value,X.time=G.time,G.type===0?ach(X,G.yU,G.KR,c):G.type===1&&X.G&496&&H_V(X.Z,G.yU,G.KR,c);X.J.length=0},Hm=function(){this.type=0},ae=function(){this.state=this.TX=this.T5=0},W6t=function(){this.timestamp=this.J=0},$h=function(X){this.Z=X;
this.U=[];this.J=this.G=this.row=0;this.style=new Hm;for(X=this.X=0;X<=15;X++){this.U[X]=[];for(var c=0;c<=32;c++)this.U[X][c]=new W6t}},Wm=function(X,c){if(X.style.type===3){for(var V=0,G=0,n=X.Z.time+0,L="",d="",h=n,A=1;A<=15;++A){for(var Y=!1,H=G?G:1;H<=32;++H){var a=X.U[A][H];
if(a.J!==0){V===0&&(V=A,G=H);Y=String.fromCharCode(a.J);var W=a.timestamp;W<n&&(n=W);a.timestamp=h;d&&(L+=d,d="");L+=Y;Y=!0}if((a.J===0||H===32)&&Y){d="\n";break}else if(G&&!Y)break}if(V&&!Y)break}L&&c.X(V,G,n,h,L)}else for(G=V=0,L=n=X.Z.time+0,d=1;d<=15;++d)for(h="",A=1;A<=32;++A)if(H=X.U[d][A],a=H.J,a!==0&&(V===0&&(V=d,G=A),Y=String.fromCharCode(a),W=H.timestamp,W<=n&&(n=W),h+=Y,H.reset()),A===32||a===0)h&&c.X(V,G,n,L,h),n=L,h="",G=V=0},QNh=function(X,c){switch(X){case 0:return wWA[(c&127)-32];
case 1:return F6r[c&15];case 2:return EE7[c&31];case 3:return r5A[c&31]}return 0},w9=function(X){return X.U[X.row][X.G]},Fw=function(X,c,V){c>=2&&X.G>1&&(--X.G,w9(X).J=0);
var G=w9(X);G.timestamp=X.Z.time+0;G.J=QNh(c,V);X.G<32&&X.G++},Z_h=function(X,c,V,G){for(var n=0;n<G;n++)for(var L=0;L<=32;L++){var d=X.U[c+n][L],h=X.U[V+n][L];
d.J=h.J;d.timestamp=h.timestamp}},EK=function(X,c,V){for(var G=0;G<V;G++)for(var n=0;n<=32;n++)X.U[c+G][n].reset()},xjA=function(X){X.row=X.J>0?X.J:1;
X.G=1;EK(X,0,15)},vEr=function(X){this.U=X;
this.Z=0;this.style=new Hm;this.B=new $h(this.U);this.D=new $h(this.U);this.text=new $h(this.U);this.G=this.B;this.X=this.D;this.J=this.G},kv_=function(X,c,V){var G=X.G,n=!1;
switch(X.style.get()){case 4:case 1:case 2:X.style.get()===4&&G.J>0||(Wm(G,V),xjA(X.G),xjA(X.X),G.row=15,G.J=c,n=!0)}X.style.set(3);X.J=G;X.J.style=X.style;X.U.mode=1<<G.X;n?G.G=1:G.J!==c&&(G.J>c?(Wm(G,V),EK(G,G.row-G.J,c)):G.row<c&&(c=G.J),G.J=c)},oEp=function(X){X.style.set(1);
X.J=X.X;X.J.J=0;X.J.style=X.style;X.U.mode=1<<X.J.X},eTr=function(X){X.style.set(4);
X.J=X.text;X.J.style=X.style;X.U.mode=1<<X.J.X},hTz=function(X){this.J=X;
this.Z=0;this.U=new vEr(this.J);this.B=new vEr(this.J);this.G=new ae;this.X=this.U},H_V=function(X,c,V,G){X.G.update();
c=jNA(c,V,X.G);switch(c.result){case 0:return;case 1:case 2:return}var n=c.T5;V=c.TX;if(32<=n||!n)X.J.mode&X.J.G&&(c=n,c&128&&(c=127),V&128&&(V=127),X=X.X.J,c&96&&Fw(X,0,c),V&96&&Fw(X,0,V),c!==0&&V!==0&&X.style.type===3&&Wm(X,G));else if(n&16)a:if(!X.G.matches(n,V)&&(c=X.G,c.T5=n,c.TX=V,c.state=2,c=n&8?X.B:X.U,X.X=c,X.J.mode=1<<(X.Z<<2)+(c.Z<<1)+(c.style.type===4?1:0),(X.J.mode|1<<(X.Z<<2)+(c.Z<<1)+(c.style.type!==4?1:0))&X.J.G))if(V&64){G=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(n&7)<<1|V>>5&1];
X=V&16?((V&14)>>1)*4:0;V=c.J;switch(c.style.get()){case 4:G=V.row;break;case 3:if(G!==V.row){if(G<V.J&&(G=V.J,G===V.row))break;var L=1+V.row-V.J,d=1+G-V.J;Z_h(V,d,L,V.J);c=L;n=V.J;d<L?(L=d+n-L,L>0&&(c+=L,n-=L)):(L=L+n-d,L>0&&(n-=L));EK(V,c,n)}}V.row=G;V.G=X+1}else switch(n&7){case 1:switch(V&112){case 32:Fw(c.J,0,32);break a;case 48:V===57?(G=c.J,w9(G).J=0,G.G<32&&G.G++):Fw(c.J,1,V&15)}break;case 2:V&32&&Fw(c.J,2,V&31);break;case 3:V&32&&Fw(c.J,3,V&31);break;case 4:case 5:if(32<=V&&V<=47)switch(V){case 32:oEp(c);
break;case 33:G=c.J;G.G>1&&(--G.G,w9(G).J=0);break;case 36:G=c.J;c=w9(G);for(X=0;X<=15;X++)for(V=0;V<=32;V++)if(G.U[X][V]===c){for(;V<=32;V++)G.U[X][V].reset();break}break;case 37:kv_(c,2,G);break;case 38:kv_(c,3,G);break;case 39:kv_(c,4,G);break;case 40:Fw(c.J,0,32);break;case 41:c.style.set(2);c.J=c.G;c.J.J=0;c.J.style=c.style;c.U.mode=1<<c.J.X;break;case 42:G=c.text;G.J=15;G.style.set(4);xjA(G);eTr(c);break;case 43:eTr(c);break;case 44:X=c.G;switch(c.style.get()){case 1:case 2:case 3:Wm(X,G)}EK(X,
0,15);break;case 45:b:{X=c.J;switch(c.style.get()){default:case 2:case 1:break b;case 4:if(X.row<15){++X.row;X.G=1;break b}break;case 3:}X.J<2&&(X.J=2,X.row<X.J&&(X.row=X.J));c=X.row-X.J+1;Wm(X,G);Z_h(X,c,c+1,X.J-1);EK(X,X.row,1)}break;case 46:EK(c.X,0,15);break;case 47:Wm(c.G,G),c.X.updateTime(c.U.time+0),G=c.X,c.X=c.G,c.G=G,oEp(c)}break;case 7:switch(V){case 33:case 34:case 35:G=c.J,(G.G+=V&3)>32&&(G.G=32)}}},J5G=function(){},r9=function(X,c,V,G,n,L,d){L=L===void 0?!1:L;
d=d===void 0?null:d;g.hC.call(this,X,X+c,{priority:V,namespace:"captions"});this.windowId=G;this.text=n;this.append=L;this.J=d},RTr=function(X,c,V,G,n,L,d){var h=L[0],A=d[h.getAttribute("p")];
if(A.HD===1){var Y=L[1],H=L[2];L=L[3];h.getAttribute("t");Y.getAttribute("t");H.getAttribute("t");L.getAttribute("t");h.getAttribute("p");Y.getAttribute("p");L.getAttribute("p");d=d[H.getAttribute("p")];h=mjt(h.textContent,Y.textContent,H.textContent,L.textContent,d);return new r9(X,c,n,V,h,G,A)}switch(A.HD){case 9:case 10:A.DG=1;break;case 11:A.DG=2;break;case 12:A.DG=3;break;case 13:A.DG=4;break;case 14:A.DG=5}return new r9(X,c,n,V,h.textContent||"",G,A)},mjt=function(X,c,V,G,n){var L=g.sE(),d=
L?g.cW("DIV"):g.cW("RUBY"),h=g.cW("SPAN");
h.textContent=X;d.appendChild(h);X=L?g.cW("DIV"):g.cW("RP");X.textContent=c;d.appendChild(X);c=L?g.cW("DIV"):g.cW("RT");c.textContent=V;d.appendChild(c);V=n.HD;if(V===10||V===11||V===12||V===13||V===14)if(g.ao(c,"text-emphasis-style","filled circle"),g.ao(c,"text-emphasis-color","currentcolor"),g.ao(c,"webkit-text-emphasis","filled circle"),n.HD===11||n.HD===13)g.ao(c,"webkit-text-emphasis-position","under left"),g.ao(c,"text-emphasis-position","under left");V=!0;if(n.HD===4||n.HD===7||n.HD===12||
n.HD===14)g.ao(d,"ruby-position","over"),g.ao(d,"-webkit-ruby-position","before");else if(n.HD===5||n.HD===6||n.HD===11||n.HD===13)g.ao(d,"ruby-position","under"),g.ao(d,"-webkit-ruby-position","after"),V=!1;n=L?g.cW("DIV"):g.cW("RP");n.textContent=G;d.appendChild(n);L&&(G=V,g.ao(d,{display:"inline-block",position:"relative"}),L=d.firstElementChild.nextElementSibling,g.ao(L,"display","none"),L=L.nextElementSibling,g.ao(L,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ao(d.lastElementChild,"display","none"),G?(g.ao(d,"padding-top","0.6em"),g.ao(L,"top","0")):(g.ao(d,"padding-bottom","0.6em"),g.ao(L,"bottom","0")));return d},QL=function(){g.I.apply(this,arguments)},Zk=function(X,c,V,G,n){g.hC.call(this,X,X+c,{priority:V,
namespace:"captions"});this.id=G;this.params=n;this.J=[]},b_h=function(X){var c="_"+xh++;
return new Zk(0,0x8000000000000,0,c,X)},vm=function(X){QL.call(this);
this.U=X;this.pens={};this.D={};this.T={};this.X="_"+xh++;this.B={};this.G=this.J=null;this.Z=!0},kh=function(X,c){X=X.getAttribute(c);
if(X!=null)return Number(X)},oe=function(X,c){X=X.getAttribute(c);
if(X!=null)return X==="1"},el=function(X,c){X=kh(X,c);
return X!==void 0?X:null},mP=function(X,c){X=X.getAttribute(c);
if(X!=null)return J1.test(X),X},t6h=function(X,c){var V={},G=c.getAttribute("ws");
Object.assign(V,G?X.T[G]:X.U);X=el(c,"mh");X!=null&&(V.jI=X);X=el(c,"ju");X!=null&&(V.textAlign=X);X=el(c,"pd");X!=null&&(V.d1=X);X=el(c,"sd");X!=null&&(V.pZ=X);X=mP(c,"wfc");X!=null&&(V.windowColor=X);c=kh(c,"wfo");c!==void 0&&(V.windowOpacity=c/255);return V},O_M=function(X,c){var V={},G=c.getAttribute("wp");
G&&Object.assign(V,X.D[G]);X=el(c,"ap");X!=null&&(V.xA=X);X=kh(c,"cc");X!=null&&(V.je=X);X=kh(c,"ah");X!=null&&(V.Y3=X);X=kh(c,"rc");X!=null&&(V.Al=X);c=kh(c,"av");c!=null&&(V.Y1=c);return V},lcM=function(X,c,V,G){var n={};
Object.assign(n,O_M(X,c));Object.assign(n,t6h(X,c));G?g.Oz(n,X.U)?(G=X.X,n=X.U):G="_"+xh++:G=c.getAttribute("id")||"_"+xh++;X=kh(c,"t")+V;c=kh(c,"d")||0x8000000000000;if(n.d1===2||n.d1===3)V=n.Al,n.Al=n.je,n.je=V;return new Zk(X,c,0,G,n)},Re=function(X){QL.call(this);
this.Z=X;this.J=new Map;this.U=new Map;this.X=new Map;this.G=new Map},bg=function(X){X=g.H1(Math.round(X),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-X.length)+X},M6V=function(X,c,V,G,n){G===0&&(G=0x8000000000000);
var L={};c.wpWinPosId&&Object.assign(L,X.U.get(c.wpWinPosId));c.wsWinStyleId&&Object.assign(L,X.X.get(c.wsWinStyleId));X=c.rcRowCount;X!==void 0&&(L.Al=X);c=c.ccColCount;c!==void 0&&(L.je=c);if(L.d1===2||L.d1===3)c=L.Al,L.Al=L.je,L.je=c;return new Zk(V,G,0,n,L)},t1=function(X,c,V){g.Eb.call(this,X);
this.videoData=c;this.audioTrack=V;this.Z=c.Zw},OK=function(X,c,V,G,n,L,d,h,A,Y){Yh.call(this,X,c,V,G,n,L,d,h,A,Y);
this.type=1},lg=function(X,c,V){this.trackData=X;
this.B=V;this.version=this.Z=this.U=this.byteOffset=0;this.G=[];this.J=new DataView(this.trackData)},MS=function(X){var c=X.byteOffset;
X.byteOffset+=1;return X.J.getUint8(c)},g9=function(X){var c=X.byteOffset;
X.byteOffset+=4;return X.J.getUint32(c)},fI=function(X,c){QL.call(this);
this.G=X;this.U=c;this.track=this.U.languageName==="CC3"?4:0;this.J=new A5A;this.J.G=1<<this.track},fct=function(X){if(typeof X==="string")return!1;
X=new lg(X,8,0);return gEH(X)},gEH=function(X){if(!(X.byteOffset<X.J.byteLength)||g9(X)!==1380139777)return!1;
X.version=MS(X);if(X.version>1)return!1;MS(X);MS(X);MS(X);return!0},pI=function(X,c,V,G,n,L,d,h,A,Y){Yh.call(this,X,c,V,G,n,L,d,h,A,Y);
var H=this;this.type=2;this.kO=[];this.G_=this.C=this.QK=0;this.NW=NaN;this.EM=0;this.oZ=null;this.fS=new g.i_(this.SW,433,this);this.LS=!1;this.B&&(Y.createClientVe(this.B,this,167342),this.L(this.B,"click",function(){Y.logClick(H.B)}),X=new g.T5(this.element,!0),g.N(this,X),X.subscribe("hoverstart",function(){Y.logVisibility(H.B,!0)},this));
g.hx(this.element,"ytp-caption-window-rollup");g.N(this,this.fS);this.LS=h.lc("html5_rollup_caption_window_enable_transition_end_listener");g.ao(this.element,"overflow","hidden")},pW_=function(X,c){if(!c)return"";
X.U&&X.G.params.pZ!==1&&(c*=-1);return"translate"+(X.U?"X":"Y")+"("+c+"px)"},Icp=function(X){X.kO=Array.from(X.element.getElementsByClassName("caption-visual-line"));
for(var c=X.G.params.Al,V=0,G=0,n=X.kO.length-1;V<c&&n>-1;){var L=X.kO[n];G+=X.U?L.offsetWidth:L.offsetHeight;V++;n--}X.C=G;c=Math;V=c.max;isNaN(X.NW)&&((G=X.J.je)?(n=g.cW("SPAN"),g.h5(n,"\u2013".repeat(G)),g.ao(n,nEH(X,X.J.F4)),X.X.appendChild(n),X.NW=n.offsetWidth,X.X.removeChild(n)):X.NW=0);G=X.X;X.G_=V.call(c,X.NW,X.EM,(X.U?G.offsetHeight:G.offsetWidth)+1)},NWr=function(X,c){Icp(X);
var V=X.kO.reduce(function(L,d){return(X.U?d.offsetWidth:d.offsetHeight)+L},0);
V=X.C-V;if(V!==X.QK){var G=V>0&&X.QK===0,n=V<X.QK;c||isNaN(V)||G||!n||(g.hx(X.element,"ytp-rollup-mode"),X.LS?X.L(X.element,"transitionend",X.SW):g.qR(X.fS));g.ao(X.X,"transform",pW_(X,V));X.QK=V}Icp(X)},UjH=function(X,c,V,G){var n=this;
this.W=X;this.G=c;this.logger=V;this.ZQ=G;this.lB=[];this.Cg=[];this.Ru=null;this.F8={hDR:function(){return n.Ru},
q$:function(){return n.lB}};
X=g.F1(this.W.j().experiments,"html5_override_micro_discontinuities_threshold_ms");this.J=X>0?X:10},Ppi=function(X,c){X.Ru=function(V,G){if(V.info.Z){var n=V;
if(X.Cg.length>0){for(n=X.Cg.shift();X.Cg.length>0;)n=g.XY(n,X.Cg.shift());n=g.XY(n,V)}if(n){V=n;try{var L=g.cy(V)*1E3}catch(Y){L=V.info.startTime*1E3}try{var d=g.ebs(V)*1E3}catch(Y){d=V.info.duration*1E3}if(L<0||d<0)L<0&&(L=V.info.startTime*1E3),d<0&&(d=V.info.duration*1E3);V.info.startTime=L/1E3;V.info.X=L/1E3;V.info.duration=d/1E3;V.info.T=d/1E3;L=X.IA(n);d=L.Bl;L={formatId:L.formatId,startTimeMs:L.startTimeMs,durationMs:L.durationMs,JJ:d,Ce:d};d=TWU(X.lB,L.startTimeMs);var h=(V=d>=0?X.lB[d]:null)?
V.startTimeMs+V.durationMs:0,A=L.startTimeMs+L.durationMs;!V||L.startTimeMs-h>X.J?X.lB.splice(d+1,0,L):(V.durationMs=Math.max(h,A)-V.startTimeMs,V.Ce=Math.max(V.Ce,L.Ce));G(X.lB);G=n.Hg();uVM(X.G,G.buffer.slice(G.byteOffset,G.byteLength+G.byteOffset),c,n.info.X)}else X.logger.J(350058965,"Empty slice")}else X.Cg.push(V)};
X.W.addEventListener("sabrCaptionsDataLoaded",X.Ru)},TWU=function(X,c){X=g.yk(X,{startTimeMs:c},function(V,G){return V.startTimeMs-G.startTimeMs});
return X>=0?X:-X-2},zTA=function(X,c){g.Eb.call(this,c);
this.J=X;this.W=c;this.logger=new g.LD("caps");this.U=this.B=null;this.D=new UjH(this.W,this,this.logger,this.J.ZQ)},uVM=function(X,c,V,G){X.logger.debug(function(){return"SABR captions data received for "+G});
X.B?X.U==null?X.logger.J(350058965,"Null loaded track meta data at captions data received"):V.Iu(c,X.U,G*1E3):X.logger.J(350058965,"Null Representation at captions data received")},BWA=function(X,c){var V=[],G;
for(G in X.J.J)if(X.J.J.hasOwnProperty(G)){var n=X.J.J[G];if(g.QD(n,c||null)){var L=n.info.id,d=L,h="."+L,A="",Y="";if(n=n.info.captionTrack)L=n.languageCode,d=n.displayName,h=n.vssId,A=n.kind,Y=n.id;V.push(new g.a6({id:G,languageCode:L,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:h,kind:A,captionId:Y}))}}return V},K6r=function(X,c,V){var G=[],n;
for(n in X.J.J)if(X.J.J.hasOwnProperty(n)){var L=X.J.J[n];if(g.QD(L,V||null)){var d=L.info.captionTrack;d&&d.languageCode===c&&G.push(L)}}return G.length?G[0]:null},sN7=function(X,c){if(!g.wqO(X)||X.J!=null&&g.RX(c.j())&&!X.J.isManifestless&&X.J.J.rawcc!=null)return!1;
c=!!X.J&&X.J.isManifestless&&Object.values(X.J.J).some(function(V){return g.QD(V,"386")});
X=!!X.J&&!X.J.isManifestless&&g.U1L(X.J);return c||X},Ie=function(){QL.call(this)},Cp_=function(X,c,V,G,n,L,d,h,A){switch(d.tagName){case "b":h.bold=!0;
break;case "i":h.italic=!0;break;case "u":h.underline=!0}for(var Y=0;Y<d.childNodes.length;Y++){var H=d.childNodes[Y];if(H.nodeType===3)H=new r9(c,V,G,n.id,H.nodeValue,L||Y>0,g.bU(h)?void 0:h),A.push(H),n.J.push(H);else{var a={};Object.assign(a,h);Cp_(X,c,V,G,n,!0,H,a,A)}}},DjU=function(X){var c=X.split(":");
X=0;c=g.r(c);for(var V=c.next();!V.done;V=c.next())X=X*60+Number(V.value);return X*1E3},S_7=function(X,c,V,G){G=Object.assign({jI:0},G);
return new Zk(X,c,V,"_"+xh++,G)},NS=function(X,c){g.I.call(this);
this.W=X;this.qW=c;this.J=null;this.G=this.W.yR();this.logger=new g.LD("caps")},q_U=function(X,c,V){if(typeof c==="string"||fct(c))return[{trackData:c,
QD:V}];var G=new DataView(c);if(G.byteLength<=8||G.getUint32(4)!==1718909296)return[];var n=g.Ms8(G);if(X.G&&n){var L=g.eBj(n),d=g.JmO(n);n=n.tC;L&&n&&X.G.lZ(n,L,d)}X=g.ct(G,1835295092);if(!X||!X.length||!X[0].size)return[];L=[];for(d=0;d<X.length;d++)n=X[d],n=new Uint8Array(c,n.dataOffset,n.size-(n.dataOffset-n.offset)),n=g.tX(n),L.push({trackData:n,QD:V+d*1E3});i_G(G,L,V);return L=L.filter(function(h){return!!h.trackData})},i_G=function(X,c,V){var G=g.B4(X,0,1836476516),n=9E4;
G&&(n=g.K5(G)||9E4);G=0;for(var L=g.ct(X,1836019558),d=0;d<L.length;d++){var h=L[d];d<c.length&&(h=g.B4(X,h.dataOffset,1953653094))&&(h=g.B4(X,h.dataOffset,1952867444))&&(h=g.q2(h)/n*1E3,d===0&&(G=h),c[d].QD=h-G+V||V*d*1E3)}},XUz=function(X){var c={};
if(X=g.w4(X))c.lang=X,g.urA.test(X)&&(c.d1=1);return c},UK=function(X){g.wh.call(this,X);
var c=this;this.W=X;this.wy=[];this.kO={};this.LS={};this.T=!1;this.X="NONE";this.J=this.C=this.G_=this.YO=this.qE=null;this.NE={s_:function(){c.s_()},
Iu:function(L,d,h,A){c.Iu(L,d,h,A)}};
this.G=null;this.qW=this.W.j();this.videoData=this.W.getVideoData();this.o2=this.W.CS();var V;this.yK=(V=this.W.getVideoData(1))==null?void 0:g.sf(V);this.U={F4:{}};this.B={F4:{}};g.iN(this.videoData)?this.X="OFFLINE":sN7(this.videoData,this.W)?this.X="SABR_LIVE":g.TFs(this.videoData,this.W)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.YM&&(this.X="TTS");this.fS=this.qW.controlsType==="3";this.T_=new NS(this.W,this.qW);this.NW=new g.N_(this);this.D=new g.z({N:"div",
Y:"ytp-caption-window-container",K:{id:"ytp-caption-window-container"}});this.A7={top:0,right:0,bottom:0,left:0,width:1,height:1};V=null;var G=g.Ib("yt-html5-player-modules::subtitlesModuleData");G&&(V=new g.Rb(G));this.storage=V;var n;this.hX=!((n=X.vg())==null||!n.Gp());this.Z=cuA(this);this.Pl=!this.Z&&this.fS&&this.hX&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.N(this,this.T_);this.Z?this.QK=this.Hl=null:(this.Hl=new g.Sn(this.lh,void 0,this),g.N(this,this.Hl),this.QK=new g.i_(this.S5O,2E3,this),
g.N(this,this.QK));g.N(this,this.NW);g.lc(this.player,this.D.element,4);g.N(this,this.D);this.Z||this.NW.L(X,"resize",this.yD);(this.HP=g.lY(this.qW)&&!g.Qe()&&!this.W.isFullscreen()&&!this.Z&&!this.Pl)&&this.NW.L(X,"resize",this.JTc);this.NW.L(X,"onPlaybackAudioChange",this.P3R);this.NW.L(X,g.Ya("captions"),function(L){c.onCueRangeEnter(L)});
this.NW.L(X,g.jw("captions"),function(L){c.onCueRangeExit(L)});
this.yK&&this.NW.L(X,"videodatachange",function(L,d){c.onVideoDataChange(L,d)});
Vmt(this,zrr()||{});this.player.hT("onCaptionsModuleAvailable")},L2_=function(X){if(X.qW.hX===1||X.videoData.Um===1||g.xB(X.videoData,"yt:cc")==="alwayson")return!0;
if(X.videoData.captionTracks.length)var c=X.getAudioTrack().G;if(X.qW.hX===2){if(g.Dv(X.qW))var V=Gd7(X);else if(X.storage)try{V=X.storage.get("module-enabled")}catch(n){X.storage.remove("module-enabled")}else V=null;if(V!=null)return!!V}V=gbV(X.player.getAudioTrack(),g.Dv(X.qW));var G=g.xB(X.videoData,"yt:cc");if(ncA(X)===void 0){if(V==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return G?G==="on":!0;if(V==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return G==="on"}else return G==="on";return c==="ON"||
g.xB(X.videoData,"yt:cc")==="on"},TN=function(X,c){if(X.G&&(c===void 0||!c)||!X.videoData.captionTracks.length)return!1;
X=X.getAudioTrack();return!!X.J||X.G==="FORCED_ON"},ncA=function(X){var c=void 0,V=g.zk(g.Pe(),65);
if(g.Dv(X.qW)&&V!=null){if(Gd7(X)!=null)return!1;c=!V}return c},Pm=function(X,c){if(!X.J)return null;
if(X.C&&X.C.X)return X.C.X;c=dGt(X,c);c=g.G$(X.J.G,c);var V=null;if(fuU(X.qW)){var G=X.W.isInline()?void 0:g.pv("yt-player-caption-sticky-language");for(var n=[G,X.videoData.captionsLanguagePreference,X.qW.captionsLanguagePreference,g.xB(X.videoData,"yt:cc_default_lang")],L=!1,d=0;d<n.length;d++){var h=n[d];if(h){L=!0;for(var A=0;A<c.length;A++)if(g.w4(c[A])===h)return c[A];for(A=0;A<c.length;A++)if(g.w4(c[A]).split("-")[0]===h.split("-")[0])return c[A]}}if(L&&X.J&&(n=X.J.Z,n.length))for(n=g.r(n),
L=n.next();!L.done;L=n.next())if(L=L.value,L.languageCode===G){V=L;break}}else for(G=[X.videoData.captionsLanguagePreference,X.qW.captionsLanguagePreference,g.xB(X.videoData,"yt:cc_default_lang")],n=0;n<G.length;n++)for(L=0;L<c.length;L++)if(g.w4(c[L])===G[n])return c[L];G=null;X.C&&X.C.U&&(G=X.C.U);G||(G=c.find(function(Y){return Y.isDefault})||null);
G||(G=c[0]||ug(X));G&&V&&g.w4(G).split("-")[0]!==V.languageCode.split("-")[0]&&(G=p1k(G,V));return G},ug=function(X){return X.C&&X.C.J},zN=function(X){var c=ug(X);
return!!c&&X.G===c},yup=function(X,c){var V=X.W.vg().WP().textTracks;
X=X.G.toString();for(var G=0;G<V.length;G++){var n=V[G];n.id===X&&(c?n.mode!=="showing"&&(n.mode="showing"):n.mode==="showing"&&(n.mode="disabled"))}},sK=function(X,c,V){X.loaded&&X.unload();
V!=null&&(X.T=V,X.T&&(g.Dv(X.qW)?Bm(X,!!c):KI(X,!!c)));X.qW.S("html5_report_caption_format_change")&&hfh(X,X.G,c,X.T,!1);X.G=c;TN(X)&&(c=ug(X),X.qW.S("html5_report_caption_format_change")&&hfh(X,X.G,c,X.T,!0),X.G=c);var G;Auz(X,(G=X.G)!=null?G:void 0);X.load()},j3M=function(X,c){if(c instanceof Zk){var V=X.kO[c.id];
V&&V.G!==c&&(V.dispose(),delete X.kO[c.id],V=null);V||(V=Yep(X,c))&&(X.kO[c.id]=V)}else V=c.windowId,X.LS[V]||(X.LS[V]=[]),X.LS[V].push(c)},Yep=function(X,c){var V=HBH(X);
if(!V)return null;var G=X.G?g.w4(X.G):null;G&&g.urA.test(G)&&(c.params.d1=1);var n=X.o2.getPlayerSize();G=n.height*X.A7.height;n=n.width*X.A7.width;X.qW.playerStyle!=="google-live"||X.U.isDefault||Object.assign(c.params,X.U);switch(c.params.jI!=null?c.params.jI:c.J.length>1?1:0){case 1:return new OK(c,X.U,X.B,V.width,V.height,n,G,X.qW.experiments,X.Rc.bind(X),X.W);case 2:return new pI(c,X.U,X.B,V.width,V.height,n,G,X.qW.experiments,X.Rc.bind(X),X.W);default:return new Yh(c,X.U,X.B,V.width,V.height,
n,G,X.qW.experiments,X.Rc.bind(X),X.W)}},Vmt=function(X,c,V){V=V===void 0?!1:V;
var G=CI.F4;X.U={};Object.assign(X.U,CI);X.U.F4={};Object.assign(X.U.F4,G);X.B={F4:{}};var n=c.backgroundOverride?X.B:X.U,L=c.background||G.background;J1.test(L);n.F4.background=L;n=c.colorOverride?X.B:X.U;L=c.color||G.color;J1.test(L);n.F4.color=L;n=c.windowColorOverride?X.B:X.U;L=c.windowColor||CI.windowColor;J1.test(L);n.windowColor=L;n=c.backgroundOpacityOverride?X.B:X.U;L=c.backgroundOpacity;L==null&&(L=G.backgroundOpacity);n.F4.backgroundOpacity=L;n=c.fontSizeIncrementOverride?X.B:X.U;L=c.fontSizeIncrement;
L==null&&(L=G.fontSizeIncrement);n.F4.fontSizeIncrement=L;L=c.fontStyleOverride?X.B:X.U;n=c.fontStyle;n==null&&(n=G.bold&&G.italic?3:G.bold?1:G.italic?2:0);L=L.F4;switch(n){case 1:L.bold=!0;delete L.italic;break;case 2:delete L.bold;L.italic=!0;break;case 3:L.bold=!0;L.italic=!0;break;default:delete L.bold,delete L.italic}n=c.textOpacityOverride?X.B:X.U;L=c.textOpacity;L==null&&(L=G.textOpacity);n.F4.textOpacity=L;n=c.windowOpacityOverride?X.B:X.U;L=c.windowOpacity;L==null&&(L=CI.windowOpacity);n.windowOpacity=
L;n=c.charEdgeStyleOverride?X.B:X.U;L=c.charEdgeStyle;L==null&&(L=G.charEdgeStyle);n.F4.charEdgeStyle=L;n=c.fontFamilyOverride?X.B:X.U;L=c.fontFamily;L==null&&(L=G.fontFamily);n.F4.fontFamily=L;X.loaded&&X.yD();V&&g.fv("yt-player-caption-display-settings",c,2592E3)},aer=function(X,c){if(!X.J)return{};
if(c){X.qW.S("html5_report_caption_format_intent")&&!g.bU(c)&&X.Vs(c.vss_id,"m");if(X.Z||!g.sD(c))return;if(g.bU(c)){sK(X,null,!0);return}for(var V,G=g.G$(X.J.G,!0),n=0;n<G.length;n++){var L=G[n];L.languageCode!==c.languageCode||V&&(L.languageName!==c.languageName||(L.captionId||"")!==(c.captionId||"")||g.$J(L)!==c.displayName)||(V=c.translationLanguage?p1k(L,c.translationLanguage):L)}X.ej(c.position);!V||V===X.G&&X.loaded||(c=g.PV(),G=g.w4(V),c.length&&G===c[c.length-1]||(c.push(G),g.fv("yt-player-caption-language-preferences",
c)),fuU(X.qW)&&!X.W.isInline()&&g.fv("yt-player-caption-sticky-language",G,2592E3),sK(X,V,!0))}else return X.loaded&&X.G&&!zN(X)?g.Wp(X.G):{};return""},W2H=function(X,c,V){c&&!X.G_?(c=b_h({d1:0,
lang:"en"}),X.G_=[c,new r9(c.start,c.end-c.start,0,c.id,V!=null?V:"Captions look like this")],X.player.Gr(X.G_)):!c&&X.G_&&($Gi(X,X.G_),X.G_=null)},$Gi=function(X,c){X.player.oT(c);
c=g.r(c);for(var V=c.next();!V.done;V=c.next())g.iA(X.wy,V.value);yL(X.Hl)},Auz=function(X,c){X.qW.S("html5_modify_caption_vss_logging")&&(X.videoData.Lt=c)},HBH=function(X){var c=X.o2.getVideoContentRect(!0).height,V=X.o2.getVideoContentRect(!0).width;
if(!c||!V)return null;c*=X.A7.height;V*=X.A7.width;return{width:V,height:c}},KI=function(X,c){if(X.storage)try{X.storage.set("module-enabled",c)}catch(V){}},Bm=function(X,c){X.W.isInline()||g.fv("yt-player-sticky-caption",c,2592E3)},Gd7=function(X){if(!X.W.isInline())return g.pv("yt-player-sticky-caption")},cuA=function(X){var c,V=!((c=X.W.vg())==null||!c.OX());
return X.fS&&V&&X.X!=="LIVE"&&X.X!=="SABR_LIVE"},dGt=function(X,c){g.fQ(X.videoData)&&(c=!0);
c||(c=X.X==="TTS"?!1:X.X==="INNERTUBE"?!1:!0);return c||X.qW.S("web_deprecate_always_includes_asr_setting")&&g.Dv(X.qW)?!0:!!g.zk(g.Pe(),66)},hfh=function(X,c,V,G,n){n?X.Uq(V,!0,"g"):G?c?X.Uq(V,!!V,"m"):V&&X.Uq(V,!0,"m"):!c&&V&&X.Uq(V,!0,"s")};
g.Eb.prototype.IV=g.Gt(77,function(){return!1});
g.Eb.prototype.Sw=g.Gt(76,function(){});
g.rh.prototype.Sw=g.Gt(75,function(X,c,V){var G=this;this.vl();c=this.mR(X,c);var n=this.DR.j().S("html5_report_captions_ctmp_qoe"),L=(0,g.bE)();this.bb();M9G(this,c,{format:"RAW",onSuccess:function(d){G.J=null;if(n){var h=(d.responseText.length/1024).toFixed(),A=(0,g.bE)();G.videoData.Oy("capresp",{ms:A-L,kb:h})}V.Iu(d.responseText,X)},
onError:n?function(d){var h;d=(h=d==null?void 0:d.status)!=null?h:0;G.videoData.Oy("capfail",{status:d})}:void 0,
withCredentials:!0})});
g.ZL.prototype.Sw=g.Gt(74,function(X,c,V){var G=this;this.vl();c=this.mR(X,c);this.bb();this.J=g.Ra(c,{format:"RAW",onSuccess:function(n){G.J=null;V.Iu(n.responseText,X)},
withCredentials:!0})});
g.DD.prototype.R5=g.Gt(73,function(){for(var X=g.sz(document,"track",void 0,this.J),c=0;c<X.length;c++)g.dW(X[c])});
g.bR.prototype.R5=g.Gt(72,function(){this.mediaElement.R5()});
g.DD.prototype.Gp=g.Gt(71,function(){return!(!this.J.textTracks||!this.J.textTracks.addEventListener)});
g.bR.prototype.Gp=g.Gt(70,function(){return this.mediaElement.Gp()});
g.DD.prototype.OX=g.Gt(69,function(){return!!this.J.textTracks});
g.bR.prototype.OX=g.Gt(68,function(){return this.mediaElement.OX()});
g.DD.prototype.Ct=g.Gt(67,function(X){for(var c=0;c<X.length;c++)this.J.appendChild(X[c])});
g.bR.prototype.Ct=g.Gt(66,function(X){this.mediaElement.Ct(X)});
g.Xa.prototype.lZ=g.Gt(65,function(X,c,V){this.nM.lZ(X,c,V)});
g.Tg.prototype.lZ=g.Gt(64,function(X,c,V){this.G.set(X,{Ai:c,jz:V})});
g.uR.prototype.lZ=g.Gt(63,function(X,c,V){this.Hl.lZ(X,c,V)});
g.Xa.prototype.A6=g.Gt(62,function(X){return this.nM.A6(X)});
g.uR.prototype.A6=g.Gt(61,function(X){var c=2;this.T.has(X)?c=0:g.EVt(this,X)&&(c=1);return c});
g.ox.prototype.LN=g.Gt(49,function(X){var c=this.app.sM();return c?c.LN(X):!1});
g.N$.prototype.LN=g.Gt(48,function(X){return this.J7.R$.LN(X)});
g.fl.prototype.LN=g.Gt(47,function(X){return this.F9().some(function(c){return c.namespace===X})});
g.gF.prototype.LN=g.Gt(46,function(){return!1});
g.ox.prototype.Vs=g.Gt(44,function(X,c){var V;(V=this.app.Ey())==null||V.Vs(X,c)});
g.N$.prototype.Vs=g.Gt(43,function(X,c){this.J7.Vs(X,c)});
g.rK.prototype.Vs=g.Gt(42,function(X,c){X=[X,c];g.E7(this,g.$R(this.provider),"cfi",X)});
g.lt.prototype.Vs=g.Gt(41,function(X,c){this.qoe&&this.qoe.Vs(X,c)});
g.de.prototype.Vs=g.Gt(40,function(X,c){this.bB().Vs(X,c)});
g.gF.prototype.Vs=g.Gt(39,function(){});
g.ox.prototype.Uq=g.Gt(38,function(X,c,V){var G;(G=this.app.Ey())==null||G.Uq(X,c,V)});
g.N$.prototype.Uq=g.Gt(37,function(X,c,V){this.J7.Uq(X,c,V)});
g.rK.prototype.Uq=g.Gt(36,function(X,c,V){if(this.Hl!==X||this.Od!==c)c=c==="rawcc"?"":c,V=[X,c,this.Hl,V],g.E7(this,g.$R(this.provider),"cfs",V),this.Hl=X,this.Od=c});
g.lt.prototype.Uq=g.Gt(35,function(X,c,V){this.qoe&&this.qoe.Uq(X,c,V)});
g.de.prototype.Uq=g.Gt(34,function(X,c,V){this.bB().Uq(X,c,V)});
g.gF.prototype.Uq=g.Gt(33,function(){});
g.ir.prototype.vK=g.Gt(20,function(){return this.T});
g.Wn.prototype.vK=g.Gt(19,function(){var X;return((X=this.Ey())==null?void 0:X.yR())||null});
g.ox.prototype.yR=g.Gt(18,function(){return this.app.vK()});
g.N$.prototype.yR=g.Gt(17,function(){return this.J7.yR()});
g.de.prototype.yR=g.Gt(16,function(){var X;return((X=this.h7)==null?void 0:X.vK())||null});
g.gF.prototype.yR=g.Gt(15,function(){return null});
g.t7.prototype.qZ=g.Gt(1,function(X){return(X=this.dV(X))?X.J:0});
g.Lx.prototype.qZ=g.Gt(0,function(){return 0});
var Tnk=/#(.)(.)(.)/,U57=/^#(?:[0-9a-f]{3}){1,2}$/i,D5V={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};h1.prototype.contains=function(X){X=g.yk(this.segments,X);return X>=0||X<0&&(-X-1)%2===1};
h1.prototype.length=function(){return this.segments.length/2};
g.E(KHz,g.I);g.y=KHz.prototype;g.y.R2=function(){g.I.prototype.R2.call(this);this.U&&this.U.cancel()};
g.y.A8=function(){this.seekTo(this.player.getCurrentTime())};
g.y.seekTo=function(X){X-=this.player.h1();var c=this.J;this.J=g.B7(this.G_.FO(X).KS);c!==this.J&&this.C&&this.C()};
g.y.reset=function(){this.X=new h1;this.B=-1;this.U&&(this.U.cancel(),this.U=null)};
g.y.O1=function(){this.vl();var X;if(X=this.J!=null)X=this.J,X=X.J.bP(X);if(X&&!this.U&&!(this.J&&this.J.startTime-this.player.getCurrentTime()>30)){X=this.J;X=X.J.JN(X);var c=X.KS[0],V;if((V=this.player.getVideoData())==null?0:V.enableServerStitchedDai)if(V=this.player.yR()){var G=c.J.info.id,n=c.Bl,L=X.KS[0].X;if(this.policy.wy){if(V=V.GD(L,n,G,3))X.X=V}else if(G=V.eF(L,n,G,3))if(V=V.A6(n),V===0)G&&(X.J=new g.v4(G));else if(V===2){this.D.start();smA(this)&&this.seekTo(this.player.getCurrentTime());
return}}c.J.index.TJ(c.Bl)?(this.X.contains(X.KS[0].Bl)||CUU(this,X),this.J=g.B7(X.KS)):smA(this)&&this.seekTo(this.player.getCurrentTime())}this.D.start()};
g.E(A1,g.Eb);g.y=A1.prototype;g.y.Sw=function(X,c,V){var G=this;this.bb();c=i0G(this,X.getId());c||(c=X.languageCode,c=this.J.isManifestless?qzr(this,c,"386"):qzr(this,c));if(c){var n=(c.index.qZ(c.index.zC())-c.index.getStartTime(c.index.zC()))*1E3,L=this.W.j(),d=new g.SXD(L),h=function(){G.U&&G.U.reset();G.B=!0};
L.S("html5_keep_caption_data_after_seek")&&(h=null);this.U=new KHz(d,this.W,c,function(A,Y){V.Iu(A,X,Y,n)},this.D||g.cZ(c.info),h)}};
g.y.IV=function(){var X=this.B;this.B=!1;return X};
g.y.kD=function(X){var c=this.W.j().S("html5_fallback_if_rawcc_missing");var V=this.J.J.rawcc!=null;if(!this.D||!V&&c)c=this.J.isManifestless?Sz_(this,"386"):Sz_(this);else{if(!V){this.logger.J(386248249,"rawcc used but unavailable");return}c=[new g.a6({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.a6({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}c=g.r(c);
for(V=c.next();!V.done;V=c.next())g.Fc(this.G,V.value);X.s_()};
g.y.bb=function(){this.U&&(this.U.dispose(),this.U=null)};
g.y.mR=function(){return""};
g.y.Kn=function(){this.U&&(this.U.reset(),this.W.EH("captions"))};
var J1=/^#(?:[0-9a-f]{3}){1,2}$/i;var V6M=["left","right","center","justify"];g.E(Yh,g.z);g.y=Yh.prototype;g.y.At=function(X,c){this.yK=X;this.qE=c;var V=g.xv(this.element,this.element.parentElement);this.o2=X-V.x;this.hX=c-V.y};
g.y.GR=function(X,c){if(X!==this.yK||c!==this.qE){g.yO(this.element,"ytp-dragging")||g.hx(this.element,"ytp-dragging");var V=g.mn(this.element);X=X-this.o2-.02*this.playerWidth;var G=c-this.hX-.02*this.playerHeight,n=(X+V.width/2)/this.maxWidth*3;n=Math.floor(g.H1(n,0,2));var L=(G+V.height/2)/this.maxHeight*3;L=Math.floor(g.H1(L,0,2));c=n+L*3;X=(X+n/2*V.width)/this.maxWidth;X=g.H1(X,0,1)*100;V=(G+L/2*V.height)/this.maxHeight;V=g.H1(V,0,1)*100;this.G.params.xA=c;this.G.params.Y1=V;this.G.params.Y3=
X;this.G.params.isDefault=!1;this.J.xA=c;this.J.Y1=V;this.J.Y3=X;this.J.isDefault=!1;this.A7.xA=c;this.A7.Y1=V;this.A7.Y3=X;this.A7.isDefault=!1;this.HB()}};
g.y.OJ=function(){g.YD(this.element,"ytp-dragging")};
g.y.HB=function(){this.M9(this.D)};
g.y.getType=function(){return this.type};
g.y.M9=function(X){var c=this.NE?0:Math.min(this.XW(),this.maxWidth),V=this.UB(),G=this.NE;if(G){var n=getComputedStyle(this.X.parentNode);n=jl(n.borderLeftWidth)+jl(n.borderRightWidth)+jl(n.paddingLeft)+jl(n.paddingRight)}else n=0;var L=n;n="";this.G.params.d1===3&&(n="rotate(180deg)");var d=G?"calc(96% - "+L+"px)":"96%";g.ao(this.element,{top:0,left:0,right:"",bottom:"",width:c?c+"px":"",height:V?V+"px":"","max-width":d,"max-height":d,margin:"",transform:""});this.hw(X);n={transform:n,top:"",left:"",
width:c?c+"px":"",height:V?V+"px":"","max-width":"","max-height":""};var h=this.J.Y3*.96+2;d=this.J.xA;switch(d){case 0:case 3:case 6:(G=this.J.F4.fontSizeIncrement)&&G>0&&this.J.d1!==2&&this.J.d1!==3&&(h=Math.max(h/(1+G*2),2));n.left=h+"%";break;case 1:case 4:case 7:n.left=h+"%";h=this.X.offsetWidth;c||h?(c=c||h+1,n.width=c+"px",n["margin-left"]=G?c/-2-L/2+"px":c/-2+"px"):n.transform+=" translateX(-50%)";break;case 2:case 5:case 8:n.right=100-h+"%"}G=this.J.Y1*.96+2;switch(d){case 0:case 1:case 2:n.top=
G+"%";break;case 3:case 4:case 5:n.top=G+"%";(V=V||this.element.clientHeight)?(n.height=V+"px",n["margin-top"]=V/-2+"px"):n.transform+=" translateY(-50%)";break;case 6:case 7:case 8:n.bottom=100-G+"%"}g.ao(this.element,n);if(this.B){V=this.X.offsetHeight;G=1;for(c=0;c<X.length;c++)n=X[c],typeof n.text==="string"&&(G+=n.text.split("\n").length-1,n.append||c===0||G++);V/=G;this.B.style.height=V+"px";this.B.style.width=V+"px";this.element.style.paddingLeft=V+5+"px";this.element.style.paddingRight=V+
5+"px";X=Number(this.element.style.marginLeft.replace("px",""))-V-5;V=Number(this.element.style.marginRight.replace("px",""))-V-5;this.element.style.marginLeft=X+"px";this.element.style.marginRight=V+"px"}};
g.y.hw=function(X){var c;for(c=0;c<X.length&&X[c]===this.D[c];c++);if(this.Pl||this.D.length>c)c=0,this.Pl=!1,this.D=[],this.T=this.Hl=this.wy=null,g.n_(this.X);for(;c<X.length;c++)y5t(this,X[c])};
g.y.XW=function(){return 0};
g.y.UB=function(){return 0};
g.y.toString=function(){return g.z.prototype.toString.call(this)};A5A.prototype.clear=function(){this.U=this.time=this.mode=0;this.J=[];this.reset()};
A5A.prototype.reset=function(){this.mode=0;this.X.reset(0);this.Z.reset(1)};
var Y_M=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Hm.prototype.set=function(X){this.type=X};
Hm.prototype.get=function(){return this.type};
ae.prototype.clear=function(){this.state=0};
ae.prototype.update=function(){this.state=this.state===2?1:0};
ae.prototype.d$=function(){return this.state!==0};
ae.prototype.matches=function(X,c){return this.d$()&&X===this.T5&&c===this.TX};
W6t.prototype.reset=function(){this.timestamp=this.J=0};
$h.prototype.updateTime=function(X){for(var c=1;c<=15;++c)for(var V=1;V<=32;++V)this.U[c][V].timestamp=X};
$h.prototype.debugString=function(){for(var X="\n",c=1;c<=15;++c){for(var V=1;V<=32;++V){var G=this.U[c][V];X=G.J===0?X+"_":X+String.fromCharCode(G.J)}X+="\n"}return X};
$h.prototype.reset=function(X){for(var c=0;c<=15;c++)for(var V=0;V<=32;V++)this.U[c][V].reset();this.X=X;this.J=0;this.G=this.row=1};
var wWA=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],F6r=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],EE7=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],r5A=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];vEr.prototype.reset=function(X,c){this.Z=c;this.style.set(2);this.G=this.B;this.X=this.D;this.J=this.G;var V=(X<<2)+(c<<1);this.B.reset(V);this.D.reset(V);this.text.reset((X<<2)+(c<<1)+1)};
hTz.prototype.reset=function(X){this.Z=X;this.G.clear();this.X=this.U;this.U.reset(X,0);this.B.reset(X,1)};J5G.prototype.X=function(){};g.E(r9,g.hC);r9.prototype.toString=function(){return g.hC.prototype.toString.call(this)};g.E(QL,g.I);QL.prototype.ub=function(){return[]};
QL.prototype.reset=function(){};g.E(Zk,g.hC);Zk.prototype.toString=function(){return g.hC.prototype.toString.call(this)};
var xh=0;g.E(vm,QL);vm.prototype.reset=function(){this.B={};this.G=this.J=null;this.Z=!0};
vm.prototype.ub=function(X,c){X=X.firstChild;X.getAttribute("format");c=c||0;Number.isFinite(c);X=Array.from(X.childNodes);X=g.r(X);for(var V=X.next();!V.done;V=X.next())if(V=V.value,V.nodeType===1)switch(V.tagName){case "head":var G=V;break;case "body":var n=V}if(G)for(G=Array.from(G.childNodes),G=g.r(G),X=G.next();!X.done;X=G.next())if(X=X.value,X.nodeType===1)switch(X.tagName){case "pen":V=X.getAttribute("id");var L=this.pens,d={},h=X.getAttribute("p");h&&Object.assign(d,this.pens[h]);h=oe(X,"b");
h!=null&&(d.bold=h);h=oe(X,"i");h!=null&&(d.italic=h);h=oe(X,"u");h!=null&&(d.underline=h);h=el(X,"et");h!=null&&(d.charEdgeStyle=h);h=el(X,"of");h!=null&&(d.offset=h);h=mP(X,"bc");h!=null&&(d.background=h);h=mP(X,"ec");h!=null&&(d.Dx=h);h=mP(X,"fc");h!=null&&(d.color=h);h=el(X,"fs");h!=null&&h!==0&&(d.fontFamily=h);h=kh(X,"sz");h!==void 0&&(d.fontSizeIncrement=h/100-1);h=kh(X,"bo");h!==void 0&&(d.backgroundOpacity=h/255);h=kh(X,"fo");h!==void 0&&(d.textOpacity=h/255);h=el(X,"rb");h!=null&&h!==10&&
h!==0&&(d.HD=h>10?h-1:h);X=el(X,"hg");X!=null&&(d.Uj=X);L[V]=d;break;case "ws":V=X.getAttribute("id");this.T[V]=t6h(this,X);break;case "wp":V=X.getAttribute("id"),this.D[V]=O_M(this,X)}if(n){G=[];n=Array.from(n.childNodes);n=g.r(n);for(X=n.next();!X.done;X=n.next())if(X=X.value,X.nodeType===1)switch(X.tagName){case "w":this.J=lcM(this,X,c,!1);(X=this.B[this.J.id])&&X.end>this.J.start&&(X.end=this.J.start);this.B[this.J.id]=this.J;G.push(this.J);break;case "p":var A=X;h=c;V=[];L=A.getAttribute("w")||
this.X;d=!!oe(A,"a");h=(kh(A,"t")||0)+h;var Y=kh(A,"d")||5E3;d||(!this.Z&&this.G&&this.G.windowId===L&&this.G.end>h&&(this.G.end=h),this.G&&this.G.text==="\n"&&(this.G.text=""));var H=d?6:5,a=A.getAttribute("p");a=a?this.pens[a]:null;var W=Array.from(A.childNodes);W.length&&(this.Z=A.getAttribute("d")!=null);for(A=0;A<W.length;A++){var w=W[A],F=void 0;A>0&&(d=!0);var Z=void 0;w.nodeType===1&&(Z=w);if(Z&&Z.tagName==="s"){if((w=(w=Z.getAttribute("p"))?this.pens[w]:null)&&w.HD&&(w.HD===1?(w=W.slice(A,
A+4),w.length===4&&(F=RTr(h,Y,L,d,H,w,this.pens),A+=3)):F=RTr(h,Y,L,d,H,[Z],this.pens)),!F){var v=Z;F=h;Z=Y;w=L;var e=d,m=H,t=v.textContent?v.textContent:"",f=v.getAttribute("p");f=f?this.pens[f]:null;v=kh(v,"t")||0;F=new r9(F+v,Z-v,m,w,t,e,f)}}else F=new r9(h,Y,H,L,w.textContent||"",d,a);V.push(F);this.G=F}if(V.length>0)for(V[0].windowId===this.X&&(this.J=lcM(this,X,c,!0),G.push(this.J)),X=g.r(V),V=X.next();!V.done;V=X.next())V=V.value,V.windowId=this.J.id,this.J.J.push(V),G.push(V)}c=G}else c=[];
return c};var wU_=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.E(Re,QL);Re.prototype.reset=function(){this.G.clear()};
Re.prototype.ub=function(X,c){var V=JSON.parse(X);if(!V)return[];if(V.pens){X=0;for(var G=g.r(V.pens),n=G.next();!n.done;n=G.next()){n=n.value;var L={},d=n.pParentId;d&&Object.assign(L,this.J.get(d));n.bAttr&&(L.bold=!0);n.iAttr&&(L.italic=!0);n.uAttr&&(L.underline=!0);d=n.ofOffset;d!=null&&(L.offset=d);n.szPenSize!==void 0&&(L.fontSizeIncrement=n.szPenSize/100-1);d=n.etEdgeType;d!=null&&(L.charEdgeStyle=d);n.ecEdgeColor!==void 0&&(L.Dx=bg(n.ecEdgeColor));d=n.fsFontStyle;d!=null&&d!==0&&(L.fontFamily=
d);n.fcForeColor!==void 0&&(L.color=bg(n.fcForeColor));n.foForeAlpha!==void 0&&(L.textOpacity=n.foForeAlpha/255);n.bcBackColor!==void 0&&(L.background=bg(n.bcBackColor));n.boBackAlpha!==void 0&&(L.backgroundOpacity=n.boBackAlpha/255);(d=n.rbRuby)&&d!==10&&(L.HD=d>10?d-1:d,L.DG=wU_.get(L.HD));n.hgHorizGroup&&(L.Uj=n.hgHorizGroup);this.J.set(X++,L)}}if(V.wsWinStyles)for(X=0,G=g.r(V.wsWinStyles),n=G.next();!n.done;n=G.next())n=n.value,L={},(d=n.wsParentId)?Object.assign(L,this.X.get(d)):Object.assign(L,
this.Z),n.mhModeHint!==void 0&&(L.jI=n.mhModeHint),n.juJustifCode!==void 0&&(L.textAlign=n.juJustifCode),n.pdPrintDir!==void 0&&(L.d1=n.pdPrintDir),n.sdScrollDir!==void 0&&(L.pZ=n.sdScrollDir),n.wfcWinFillColor!==void 0&&(L.windowColor=bg(n.wfcWinFillColor)),n.wfoWinFillAlpha!==void 0&&(L.windowOpacity=n.wfoWinFillAlpha/255),this.X.set(X++,L);if(V.wpWinPositions)for(X=0,G=g.r(V.wpWinPositions),n=G.next();!n.done;n=G.next())n=n.value,L={},(d=n.wpParentId)&&Object.assign(L,this.U.get(d)),n.ahHorPos!==
void 0&&(L.Y3=n.ahHorPos),n.apPoint!==void 0&&(L.xA=n.apPoint),n.avVerPos!==void 0&&(L.Y1=n.avVerPos),n.ccCols!==void 0&&(L.je=n.ccCols),n.rcRows!==void 0&&(L.Al=n.rcRows),this.U.set(X++,L);if(V.events){X=[];V=g.r(V.events);for(G=V.next();!G.done;G=V.next()){var h=G.value;n=(h.tStartMs||0)+c;L=h.dDurationMs||0;if(h.id)d=String(h.id),G=M6V(this,h,n,L,d),X.push(G),this.G.set(d,G);else{h.wWinId?d=h.wWinId.toString():(d="_"+xh++,G=M6V(this,h,n,L,d),X.push(G),this.G.set(d,G));G=X;var A=h;L===0&&(L=5E3);
h=this.G.get(d);var Y=!!A.aAppend,H=Y?6:5,a=A.segs,W=null;A.pPenId&&(W=this.J.get(A.pPenId));for(A=0;A<a.length;A++){var w=a[A],F=w.utf8;if(F){var Z=w.tOffsetMs||0,v=null;w.pPenId&&(v=this.J.get(w.pPenId));if((h.params.jI!=null?h.params.jI:h.J.length>1?1:0)===2&&Y&&F==="\n")continue;w=null;var e=[],m;if(m=v&&v.HD===1){m=a;var t=A;if(t+3>=m.length||!m[t+1].pPenId||!m[t+2].pPenId||!m[t+3].pPenId)m=!1;else{var f=m[t+1].pPenId;(f=this.J.get(f))&&f.HD&&f.HD===2?(f=m[t+2].pPenId,f=this.J.get(f),!f||!f.HD||
f.HD<3?m=!1:(f=m[t+3].pPenId,m=(f=this.J.get(f))&&f.HD&&f.HD===2?!0:!1)):m=!1}}if(m)Z=a[A+1].utf8,w=a[A+3].utf8,m=a[A+2].utf8,t=this.J.get(a[A+2].pPenId),F=mjt(F,Z,m,w,t),w=new r9(n,L,H,d,F,Y,v),A+=3;else{if(F.indexOf("<")>-1){var U=void 0;e=v;m=W;t=n;f=L;var C=Z,K=H,nj=Y,yl=[],Xl=g.Bx("<html>"+F+"</html>");if(!Xl.getElementsByTagName("parsererror").length&&((U=Xl.firstChild)==null?0:U.childNodes.length))for(U=g.r(Xl.firstChild.childNodes),Xl=U.next();!Xl.done;Xl=U.next()){Xl=Xl.value;var u=void 0,
q=void 0,Q=(q=(u=Xl.textContent)==null?void 0:u.replace(/\n/g,""))!=null?q:"";if(Xl.nodeType!==3||Q&&Q.match(/^ *$/)==null){u={};Object.assign(u,e||m);q=void 0;switch((q=Xl)==null?void 0:q.tagName){case "b":u.bold=!0;break;case "i":u.italic=!0;break;case "u":u.underline=!0}yl.push(new r9(t+C,f-C,K,h.id,Q,nj,u))}}e=yl}e.length||(e=[new r9(n+Z,L-Z,H,h.id,F,Y,v||W)])}if(e.length)for(Y=g.r(e),v=Y.next();!v.done;v=Y.next())v=v.value,G.push(v),h.J.push(v);else w&&(G.push(w),h.J.push(w))}Y=!0}}}c=X}else c=
[];return c};g.E(t1,g.Eb);t1.prototype.Sw=function(X,c,V){Nnp(this.videoData.videoId,X.vssId,V.Iu)};
t1.prototype.kD=function(X){if(this.audioTrack)for(var c=g.r(this.audioTrack.captionTracks),V=c.next();!V.done;V=c.next())g.Fc(this.G,V.value);X.s_()};g.E(OK,Yh);OK.prototype.hw=function(X){var c=this.G.J;Yh.prototype.hw.call(this,X);for(X=X.length;X<c.length;X++){var V=c[X];if(L&&V.J===n)var G=L;else{G={};Object.assign(G,V.J);Object.assign(G,F27);var n=V.J;var L=G}y5t(this,V,G)}};
var F27={zRO:!0};g.E(lg,J5G);lg.prototype.X=function(X,c,V,G,n){if(V<G){var L="_"+xh++;V=V/1E3-this.B;G=G/1E3-this.B;X=new Zk(V,G-V,5,L,{textAlign:0,xA:0,Y3:c*2.5,Y1:X*5.33});n=new r9(V,G-V,5,L,n);this.G.push(X);this.G.push(n)}};
g.E(fI,QL);fI.prototype.ub=function(X){X=new lg(X,X.byteLength,this.G);if(gEH(X)){for(;X.byteOffset<X.J.byteLength;)for(X.version===0?X.U=g9(X)*(1E3/45):X.version===1&&(X.U=g9(X)*4294967296+g9(X)),X.Z=MS(X);X.Z>0;X.Z--){var c=MS(X),V=MS(X),G=MS(X);c&4&&(c&3)===this.track&&(this.track===0||this.track===1)&&(c=this.J,c.J.push({time:X.U,type:this.track,yU:V,KR:G,order:c.J.length}))}$j7(this.J,X);return X.G}return[]};
fI.prototype.reset=function(){this.J.clear()};g.E(pI,Yh);g.y=pI.prototype;g.y.HB=function(){g.Xn(this.fS)};
g.y.SW=function(){this.LS&&this.element.removeEventListener("transitionend",this.SW,!1);g.YD(this.element,"ytp-rollup-mode");this.M9(this.oZ,!0)};
g.y.UB=function(){return this.U?this.G_:this.C};
g.y.XW=function(){return this.U?this.C:this.G_};
g.y.M9=function(X,c){this.oZ=X;if(this.G.params.Al){for(var V=0,G=0;G<this.D.length&&V<X.length;G++)this.D[G]===X[V]&&V++;V>0&&V<X.length&&(X=this.D.concat(X.slice(V)));this.EM=this.G_;this.C=this.G_=0;Yh.prototype.M9.call(this,X);NWr(this,c)}Yh.prototype.M9.call(this,X)};UjH.prototype.unload=function(){this.Ru!=null&&(this.W.removeEventListener("sabrCaptionsDataLoaded",this.Ru),this.Ru=null);this.lB=[];this.W.publish("sabrCaptionsBufferedRangesUpdated",this.lB)};
UjH.prototype.IA=function(X){return{formatId:g.Gz(X.info.J.info,this.ZQ),Bl:X.info.Bl+(this.ZQ?0:1),startTimeMs:X.info.X*1E3,durationMs:X.info.T*1E3}};g.E(zTA,g.Eb);g.y=zTA.prototype;g.y.Sw=function(X,c,V){this.bb();c=X.getId();c=c!=null&&c in this.J.J?this.J.J[c]:null;c||(c=X.languageCode,c=this.J.isManifestless?K6r(this,c,"386"):K6r(this,c));c&&(this.U=X,this.B=c,Ppi(this.D,V),this.W.publish("sabrCaptionsTrackChanged",g.Gz(c.info,this.J.ZQ)))};
g.y.kD=function(X){var c=this.J.isManifestless?BWA(this,"386"):BWA(this);c=g.r(c);for(var V=c.next();!V.done;V=c.next())g.Fc(this.G,V.value);X.s_()};
g.y.bb=function(){this.U&&(this.U=this.B=null,this.D.unload(),this.W.publish("sabrCaptionsTrackChanged",null))};
g.y.mR=function(){return""};
g.y.Kn=function(){this.W.EH("captions")};g.E(Ie,QL);
Ie.prototype.ub=function(X,c){var V=[];X=X.split(Ec_);for(var G=1;G<X.length;G++){var n=X[G],L=c;if(n!==""&&!ruk.test(n)){var d=Q3i.exec(n);if(d&&d.length>=4){var h=DjU(d[1]),A=DjU(d[2])-h;h+=L;var Y=(d=d[3])?d.split(" "):[];d={};var H=null;var a="";var W=null,w="";Y=g.r(Y);for(var F=Y.next();!F.done;F=Y.next())if(F=F.value.split(":"),F.length===2){var Z=F[1];switch(F[0]){case "line":F=Z.split(",");F[0].endsWith("%")&&(H=F[0],d.Y1=Number.parseInt(H,10),F.length===2&&(a=F[1].trim()));break;case "position":F=
Z.split(",");W=F[0];d.Y3=Number.parseInt(W,10);F.length===2&&(w=F[1].trim());break;case "align":switch(Z){case "start":d.textAlign=0;break;case "middle":d.textAlign=2;break;case "end":d.textAlign=1}}}H||a||(a="end");if(!W)switch(d.textAlign){case 0:d.Y3=0;break;case 1:d.Y3=100;break;case 2:d.Y3=50}if(d.textAlign!=null){H=0;switch(a){case "center":H+=3;break;case "end":H+=6;break;default:H+=0}switch(w){case "line-left":H+=0;break;case "center":H+=1;break;case "line-right":H+=2;break;default:switch(d.textAlign){case 0:H+=
0;break;case 2:H+=1;break;case 1:H+=2}}a=H<0||H>8?7:H;d.xA=a}n=n.substring(Q3i.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=d;d=n;n={};if(d.indexOf("<")<0&&d.indexOf("&")<0)L=S_7(h,A,5,w),A=new r9(h,A,5,L.id,d,!1,g.bU(n)?void 0:n),V.push(L),V.push(A),L.J.push(A);else for(a=d.split(ZBA),a.length===1?(d=5,w=S_7(h,A,d,w)):(H=d=6,w=Object.assign({je:32},w),w=new Zk(h,A,H,"_"+xh++,w)),V.push(w),H=h,W=0;W<a.length;W++)Y=a[W],W%2===0?(F=g.Bx("<html>"+Y+"</html>"),F.getElementsByTagName("parsererror").length?
(Z=F.createElement("span"),Z.appendChild(F.createTextNode(Y))):Z=F.firstChild,Cp_(this,H,A-(H-h),d,w,W>0,Z,n,V)):H=DjU(Y)+L}Q3i.lastIndex=0}}return V};
var ruk=/^NOTE/,Ec_=/(?:\r\n|\r|\n){2,}/,Q3i=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ZBA=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.tG.cA(Ie,{ub:"wvppt"});g.E(NS,g.I);
NS.prototype.ub=function(X,c,V,G){G=G||0;V=q_U(this,X,V||0);X=[];try{for(var n=g.r(V),L=n.next();!L.done;L=n.next()){var d=L.value,h=d.trackData,A=d.QD;if(typeof h!=="string"){V=X;var Y=V.concat,H=c,a=h,W=A,w=G;if(!fct(a))throw Error("Invalid binary caption track data");this.J||(this.J=new fI(w,H));var F=this.J.ub(a,W);var Z=Y.call(V,F)}else{if(h.substring(0,6)==="WEBVTT"){V=X;var v=V.concat;this.J||(this.J=new Ie);var e=this.J.ub(h,A);Math.random()<.01&&g.Ni(Error("Deprecated subtitles format in web player: WebVTT"));var m=
v.call(V,e)}else{V=X;var t=V.concat;a:{H=c;if(h[0]==="{")try{this.J||(this.J=new Re(XUz(H)));var f=this.J.ub(h,A);break a}catch(Xl){g.IJ(Xl);f=[];break a}var U=g.Bx(h);if(!U||!U.firstChild){var C=Error("Invalid caption track data");C.params=h;throw C;}if(U.firstChild.tagName==="timedtext"){if(Number(U.firstChild.getAttribute("format"))===3){a=U;this.J||(this.J=new vm(XUz(H),this.qW));f=this.J.ub(a,A);break a}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=h;throw K;}if(U.firstChild.tagName===
"transcript"){var nj=Error("Unsupported subtitles format in web player (Format1)");nj.params=h;throw nj;}var yl=Error("Invalid caption track data");yl.params=h;throw yl;}m=t.call(V,f)}Z=m}X=Z}return X}catch(Xl){return this.logger.J(187101178,"Captions parsing failed: "+Xl.message+". "),this.clear(),[]}};
NS.prototype.clear=function(){this.J&&this.J.dispose();this.J=null};
NS.prototype.reset=function(){this.J&&this.J.reset()};
NS.prototype.R2=function(){g.I.prototype.R2.call(this);this.clear()};var CI={windowColor:"#080808",windowOpacity:0,textAlign:2,xA:7,Y3:50,Y1:100,isDefault:!0,F4:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.E(UK,g.wh);g.y=UK.prototype;g.y.R2=function(){if(this.Z||this.Pl){var X=this.W.vg();X&&!X.vl()&&X.R5()}else W2H(this,!1);g.wh.prototype.R2.call(this)};
g.y.NI=function(){return this.qW.S("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.y.Ym=function(){if(this.fS)return this.Z||this.Pl;var X=this.getAudioTrack();if(this.NI()){if(!X.captionTracks.length)return!1;if(!this.J)return!0}X=gbV(X,g.Dv(this.qW));return X==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:X==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?TN(this):ncA(this)||TN(this)?!0:L2_(this)};
g.y.load=function(){g.wh.prototype.load.call(this);this.C=this.getAudioTrack();if(this.J)this.G&&(this.T_.clear(),this.Z?yup(this,!0):this.player.getPresentingPlayerType()!==3&&this.J.Sw(this.G,"json3",this.NE),this.Z||this.Pl||zN(this)||this.player.hT("captionschanged",g.Wp(this.G)));else{var X;this.X==="OFFLINE"?X=new t1(this.player,this.videoData,this.getAudioTrack()):this.X==="SABR_LIVE"?X=new zTA(this.videoData.J,this.player):this.X==="LIVE"?X=new A1(this.videoData.J,this.player):this.X==="INNERTUBE"?
X=new g.rh(this.player,this.videoData,this.getAudioTrack()):X=new g.ZL(this.player,this.videoData.YM,this.videoData.videoId,g.QCL(this.videoData),this.videoData.H5,this.videoData.eventId);this.J=X;g.N(this,this.J);this.J.kD(this.NE)}};
g.y.unload=function(){this.Z&&this.G?yup(this,!1):(this.QK&&g.c6(this.QK),this.player.EH("captions"),this.wy=[],this.J&&this.J.bb(),this.T_.clear(),this.G_&&this.player.Gr(this.G_),this.yD());g.wh.prototype.unload.call(this);this.player.Se();this.player.hT("captionschanged",{})};
g.y.create=function(){this.Ym()&&this.load();var X;a:{var c,V,G;if(this.qW.S("web_player_nitrate_promo_tooltip")&&((c=this.videoData.getPlayerResponse())==null?0:(V=c.captions)==null?0:(G=V.playerCaptionsTracklistRenderer)==null?0:G.enableTouchCaptionsNitrate)){var n,L;if(c=(X=this.videoData.getPlayerResponse())==null?void 0:(n=X.captions)==null?void 0:(L=n.playerCaptionsTracklistRenderer)==null?void 0:L.captionTracks)for(X=g.r(c),n=X.next();!n.done;n=X.next())if(n=n.value,n.kind==="asr"&&n.languageCode===
"en"){X=!0;break a}}X=!1}X&&this.W.publish("showpromotooltip",this.D.element)};
g.y.s_=function(){var X=gbV(this.player.getAudioTrack(),g.Dv(this.qW));var c=X==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Pm(this,this.T):X==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&TN(this)?ug(this):ncA(this)||this.T||L2_(this)?Pm(this,this.T):TN(this)?ug(this):null;if(this.Z||this.Pl){var V=g.G$(this.J.G,!0);X=[];for(var G=0;G<V.length;G++){var n=V[G],L=g.cW("TRACK");L.setAttribute("kind","subtitles");L.setAttribute("label",g.$J(n));L.setAttribute("srclang",g.w4(n));L.setAttribute("id",n.toString());
this.Pl||L.setAttribute("src",this.J.mR(n,"vtt"));n===c&&L.setAttribute("default","1");X.push(L)}c=this.W.vg();c.Ct(X);X=c.WP();this.hX&&this.NW.L(X.textTracks,"change",this.DNR)}else!this.G&&c&&sK(this,c),this.player.hT("onCaptionsTrackListChanged"),this.player.DL("onApiChange")};
g.y.DNR=function(){for(var X=this.W.vg().WP().textTracks,c=null,V=0;V<X.length;V++)if(X[V].mode==="showing")a:{c=g.G$(this.J.G,!0);for(var G=0;G<c.length;G++)if(c[G].toString()===X[V].id){c=c[G];break a}c=null}(this.loaded?this.G:null)!==c&&sK(this,c,!0)};
g.y.Umc=function(){!this.G&&this.Z||this.unload()};
g.y.Iu=function(X,c,V,G){if(X){var n;Auz(this,(n=this.G)!=null?n:void 0);this.J.IV()&&(this.wy=[],this.W.EH("captions"),yL(this.Hl),this.T_.reset());if(this.videoData.Pg){var L;V=((L=V)!=null?L:0)+this.videoData.Pg}X=this.T_.ub(X,c,V,G);if(this.yK)for(c=g.r(X),V=c.next();!V.done;V=c.next())V=V.value,V.U=this.videoData.clientPlaybackNonce,V.yq=this.videoData.Pg;c=!this.qW.S("html5_keep_caption_data_after_seek")&&(this.X==="LIVE"||this.X==="SABR_LIVE");this.player.Gr(X,void 0,c);!this.T||this.Pl||zN(this)||
g.tr(this.qW)||g.g0(this.qW)||g.Ty(this.qW)||this.qW.Pl==="shortspage"||this.player.isInline()||(g.c6(this.QK),X=b_h({xA:0,Y3:5,Y1:5,Al:2,textAlign:0,d1:0,lang:"en"}),this.YO=[X],c=["Click "," for settings"],this.qE||(V=new g.WR(g.ld()),g.N(this,V),this.qE=V.element),V=X.end-X.start,(G=g.$J(this.G))&&this.YO.push(new r9(X.start,V,0,X.id,G)),this.YO.push(new r9(X.start,V,0,X.id,c[0]),new r9(X.start,V,0,X.id,this.qE,!0),new r9(X.start,V,0,X.id,c[1],!0)),this.player.Gr(this.YO),g.qR(this.QK));!this.T||
this.Pl||zN(this)||(g.Dv(this.qW)?Bm(this,!0):KI(this,!0),this.C&&(this.C.X=this.G),this.player.Se());this.T=!1}};
g.y.onCueRangeEnter=function(X){this.wy.push(X);yL(this.Hl)};
g.y.onCueRangeExit=function(X){g.iA(this.wy,X);this.J instanceof A1&&this.J.D&&this.player.oT([X]);yL(this.Hl)};
g.y.getCaptionWindowContainerId=function(){return this.D.element.id};
g.y.S5O=function(){$Gi(this,this.YO);this.YO=null};
g.y.lh=function(){var X=this;if(!this.HP||!this.Z){this.Hl.stop();g.KwD(this.LS);this.wy.sort(g.AC);var c=this.wy;if(this.G_){var V=g.j8(c,function(L){return this.G_.indexOf(L)===-1},this);
V.length&&(c=V)}c=g.r(c);for(V=c.next();!V.done;V=c.next())j3M(this,V.value);c=g.r(Object.entries(this.kO));var G=c.next();for(V={};!G.done;V={JB:void 0,UW:void 0},G=c.next()){var n=g.r(G.value);G=n.next().value;n=n.next().value;V.JB=G;V.UW=n;this.LS[V.JB]?(V.UW.element.parentNode||(V.UW instanceof pI||V.UW instanceof OK||g.v1(this.kO,function(L){return function(d,h){h!==L.JB&&d.G.params.xA===L.UW.G.params.xA&&d.G.params.Y3===L.UW.G.params.Y3&&d.G.params.Y1===L.UW.G.params.Y1&&(d.dispose(),delete X.kO[h]);
return h===L.JB}}(V),this),this.D.element.appendChild(V.UW.element)),V.UW.M9(this.LS[V.JB])):(V.UW.dispose(),delete this.kO[V.JB])}}};
g.y.bey=function(){Vmt(this,{},!0);this.player.hT("captionssettingschanged")};
g.y.RRy=function(){var X=CI.F4;X={background:X.background,backgroundOpacity:X.backgroundOpacity,charEdgeStyle:X.charEdgeStyle,color:X.color,fontFamily:X.fontFamily,fontSizeIncrement:X.fontSizeIncrement,fontStyle:X.bold&&X.italic?3:X.bold?1:X.italic?2:0,textOpacity:X.textOpacity,windowColor:CI.windowColor,windowOpacity:CI.windowOpacity};var c=zrr()||{};c.background!=null&&(X.background=c.background);c.backgroundOverride!=null&&(X.backgroundOverride=c.backgroundOverride);c.backgroundOpacity!=null&&
(X.backgroundOpacity=c.backgroundOpacity);c.backgroundOpacityOverride!=null&&(X.backgroundOpacityOverride=c.backgroundOpacityOverride);c.charEdgeStyle!=null&&(X.charEdgeStyle=c.charEdgeStyle);c.charEdgeStyleOverride!=null&&(X.charEdgeStyleOverride=c.charEdgeStyleOverride);c.color!=null&&(X.color=c.color);c.colorOverride!=null&&(X.colorOverride=c.colorOverride);c.fontFamily!=null&&(X.fontFamily=c.fontFamily);c.fontFamilyOverride!=null&&(X.fontFamilyOverride=c.fontFamilyOverride);c.fontSizeIncrement!=
null&&(X.fontSizeIncrement=c.fontSizeIncrement);c.fontSizeIncrementOverride!=null&&(X.fontSizeIncrementOverride=c.fontSizeIncrementOverride);c.fontStyle!=null&&(X.fontStyle=c.fontStyle);c.fontStyleOverride!=null&&(X.fontStyleOverride=c.fontStyleOverride);c.textOpacity!=null&&(X.textOpacity=c.textOpacity);c.textOpacityOverride!=null&&(X.textOpacityOverride=c.textOpacityOverride);c.windowColor!=null&&(X.windowColor=c.windowColor);c.windowColorOverride!=null&&(X.windowColorOverride=c.windowColorOverride);
c.windowOpacity!=null&&(X.windowOpacity=c.windowOpacity);c.windowOpacityOverride!=null&&(X.windowOpacityOverride=c.windowOpacityOverride);return X};
g.y.zV=function(X,c){var V={};Object.assign(V,zrr());Object.assign(V,X);Vmt(this,V,c);this.player.hT("captionssettingschanged")};
g.y.yD=function(){!this.Z&&this.loaded&&(g.Qv(this.kO,function(X,c){X.dispose();delete this.kO[c]},this),this.lh())};
g.y.AC=function(X,c){switch(X){case "fontSize":if(isNaN(c))break;X=g.H1(c,-2,4);this.zV({fontSizeIncrement:X});return X;case "reload":c&&!this.Z&&sK(this,this.G,!0);break;case "stickyLoading":c!==void 0&&this.qW.D&&(g.Dv(this.qW)?Bm(this,!!c):KI(this,!!c));break;case "track":return aer(this,c);case "tracklist":return this.J?g.mi(g.G$(this.J.G,!(!c||!c.includeAsr)),function(V){return g.Wp(V)}):[];
case "translationLanguages":return this.J?this.J.Z.map(function(V){return Object.assign({},V)}):[];
case "sampleSubtitles":this.Z||c===void 0||W2H(this,!!c);break;case "sampleSubtitlesCustomized":this.Z||W2H(this,!!c,c);break;case "recommendedTranslationLanguages":return g.PV();case "defaultTranslationSourceTrackIndices":return this.J?this.J.T:[]}};
g.y.getOptions=function(){var X="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.qW.D&&X.push("stickyLoading");return X};
g.y.Iz=function(){var X=this.G;if(this.W.LN("captions")){if(this.qW.S("html5_modify_caption_vss_logging")){var c;return(X=(c=this.videoData.Lt)!=null?c:null)?{cc:g.NEs(X)}:{}}if(X)return c=X.vssId,X.translationLanguage&&c&&(c="t"+c+"."+g.w4(X)),{cc:c}}return{}};
g.y.zMO=function(){this.isSubtitlesOn()?(g.Dv(this.qW)?Bm(this,!1):KI(this,!1),Auz(this),this.qW.S("html5_report_caption_format_change")?sK(this,null,!0):(this.unload(),TN(this,!0)&&sK(this,ug(this),!1))):this.c6()};
g.y.c6=function(){var X=zN(this)||!this.G?Pm(this,!0):this.G;this.qW.S("html5_report_caption_format_intent")&&X&&this.Vs(X.vssId,"m");this.isSubtitlesOn()||sK(this,zN(this)||!this.G?Pm(this,!0):this.G,!0)};
g.y.isSubtitlesOn=function(){return!!this.loaded&&!!this.G&&!zN(this)};
g.y.P3R=function(){var X=zN(this);TN(this,X)?sK(this,this.getAudioTrack().J,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.NI()&&(this.T=!1,this.G=null,this.J&&(this.J.dispose(),this.J=null)),this.Ym()&&(X?sK(this,Pm(this,!1),!1):this.load()))};
g.y.ej=function(X){X&&(this.A7={top:X.top,right:X.right,bottom:X.bottom,left:X.left,width:1-X.left-X.right,height:1-X.top-X.bottom},this.D.element.style.top=this.A7.top*100+"%",this.D.element.style.left=this.A7.left*100+"%",this.D.element.style.width=this.A7.width*100+"%",this.D.element.style.height=this.A7.height*100+"%",this.D.element.style.position="absolute",X=HBH(this))&&(this.D.element.style.width=X.width+"px",this.D.element.style.height=X.height+"px")};
g.y.onVideoDataChange=function(X,c){X==="newdata"&&(this.videoData=c,this.loaded&&this.unload(),this.T=!1,this.G=null,this.J&&(this.J.dispose(),this.J=null,this.player.hT("captionschanged",{})),this.Ym()&&this.load())};
g.y.getAudioTrack=function(){return this.yK&&this.player.getPresentingPlayerType()===2?this.videoData.SU:this.player.getAudioTrack()};
g.y.JTc=function(){var X=this.W.vg();X&&!X.vl()&&X.R5();this.W.isFullscreen()?(this.Z=this.fS=!0,this.loaded&&this.s_()):(this.fS=this.qW.controlsType==="3",this.Z=cuA(this));sK(this,this.G)};
g.y.Rc=function(){var X,c,V,G=(X=this.videoData.getPlayerResponse())==null?void 0:(c=X.captions)==null?void 0:(V=c.playerCaptionsTracklistRenderer)==null?void 0:V.openTranscriptCommand;G&&this.player.z_("innertubeCommand",G)};
g.y.Uq=function(X,c,V){var G=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,n="";X&&(n=X.vssId,n=n.replace(G,""));var L="";X&&X.getId()&&(L=X.getId()||"");X&&X.getXtags()&&(X=X.getXtags(),X=X.replace(G,""),L=L.concat(";"+X));this.W.Uq(c?n:"",c?L:"",V)};
g.y.Vs=function(X,c){X=(X||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");X.length>0&&this.W.Vs(X,c)};
g.y.Kn=function(){this.J&&this.J.Kn()};
g.tG.cA(UK,{lh:"smucd"});g.Wr("captions",UK);})(_yt_player);
