(function(g){var window=this;'use strict';var K2V=function(X,c){X.z_("onAutonavCoundownStarted",c)},s3t=function(X){var c,V,G;
return X==null?void 0:(c=X.playerOverlays)==null?void 0:(V=c.playerOverlayRenderer)==null?void 0:(G=V.autoplay)==null?void 0:G.playerOverlayAutoplayRenderer},n6=function(X,c,V){g.H6(X.element,"ytp-suggestion-set",!!c.videoId);
var G=c.playlistId;V=c.xz(V?V:"mqdefault.jpg");var n=null,L=null;c instanceof g.kJ&&(c.lengthText?(n=c.lengthText||null,L=c.AA||null):c.lengthSeconds&&(n=g.m8(c.lengthSeconds),L=g.m8(c.lengthSeconds,!0)));var d=!!G;G=d&&g.xJ(G).type==="RD";var h=c instanceof g.kJ?c.isLivePlayback:null,A=c instanceof g.kJ?c.isUpcoming:null,Y=c.author,H=c.shortViewCount,a=c.publishedTimeText,W=[],w=[];Y&&W.push(Y);H&&(W.push(H),w.push(H));a&&w.push(a);V={title:c.title,author:Y,author_and_views:W.join(" \u2022 "),aria_label:c.ariaLabel||
g.ZQ("Watch $TITLE",{TITLE:c.title}),duration:n,timestamp:L,url:c.nK(),is_live:h,is_upcoming:A,is_list:d,is_mix:G,background:V?"background-image: url("+V+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:c.s8};c instanceof g.vp&&(V.playlist_length=c.playlistLength);X.update(V)},L6=function(X){var c=X.j(),V=c.X;
g.z.call(this,{N:"a",Y:"ytp-autonav-suggestion-card",K:{href:"{{url}}",target:V?c.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{N:"div",xO:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],K:{style:"{{background}}"},V:[{N:"div",K:{"aria-label":"{{timestamp}}"},xO:["ytp-autonav-timestamp"],Uy:"{{duration}}"},{N:"div",xO:["ytp-autonav-live-stamp"],Uy:"Live"},{N:"div",
xO:["ytp-autonav-upcoming-stamp"],Uy:"Upcoming"},{N:"div",Y:"ytp-autonav-list-overlay",V:[{N:"div",Y:"ytp-autonav-mix-text",Uy:"Mix"},{N:"div",Y:"ytp-autonav-mix-icon"}]}]},{N:"div",xO:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Uy:"{{title}}"},{N:"div",xO:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Uy:"{{author}}"},{N:"div",xO:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Uy:"{{views_and_publish_time}}"}]});this.W=X;this.suggestion=
null;this.J=V;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},dX=function(X,c){c=c===void 0?!1:c;
g.z.call(this,{N:"div",Y:"ytp-autonav-endscreen-countdown-overlay"});var V=this;this.D=c;this.cancelCommand=this.B=void 0;this.U=0;this.container=new g.z({N:"div",Y:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.uc(this.element);c=X.j();var G=c.X;this.W=X;this.suggestion=null;this.onVideoDataChange("newdata",this.W.getVideoData());this.L(X,"videodatachange",this.onVideoDataChange);this.J=new g.z({N:"div",Y:"ytp-autonav-endscreen-upnext-container",K:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{N:"div",Y:"ytp-autonav-endscreen-upnext-header"},{N:"div",Y:"ytp-autonav-endscreen-upnext-alternative-header",Uy:"{{autoplayAlternativeHeader}}"},{N:"a",Y:"ytp-autonav-endscreen-link-container",K:{href:"{{url}}",target:G?c.C:""},V:[{N:"div",Y:"ytp-autonav-endscreen-upnext-thumbnail",K:{style:"{{background}}"},V:[{N:"div",K:{"aria-label":"{{timestamp}}"},xO:["ytp-autonav-timestamp"],
Uy:"{{duration}}"},{N:"div",xO:["ytp-autonav-live-stamp"],Uy:"Live"},{N:"div",xO:["ytp-autonav-upcoming-stamp"],Uy:"Upcoming"}]},{N:"div",Y:"ytp-autonav-endscreen-video-info",V:[{N:"div",Y:"ytp-autonav-endscreen-premium-badge"},{N:"div",Y:"ytp-autonav-endscreen-upnext-title",Uy:"{{title}}"},{N:"div",Y:"ytp-autonav-endscreen-upnext-author",Uy:"{{author}}"},{N:"div",Y:"ytp-autonav-view-and-date",Uy:"{{views_and_publish_time}}"},{N:"div",Y:"ytp-autonav-author-and-view",Uy:"{{author_and_views}}"}]}]}]});
g.N(this,this.J);this.J.uc(this.container.element);G||this.L(this.J.I2("ytp-autonav-endscreen-link-container"),"click",this.Hm);this.W.createClientVe(this.container.element,this,115127);this.W.createClientVe(this.J.I2("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.z({N:"div",Y:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.uc(this.container.element);this.G=new g.z({N:"div",Y:"ytp-autonav-endscreen-button-container"});g.N(this,this.G);this.G.uc(this.container.element);
this.cancelButton=new g.z({N:"button",xO:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",c.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],K:{"aria-label":"Cancel autoplay"},Uy:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.uc(this.G.element);this.cancelButton.listen("click",this.k7,this);this.W.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.z({N:"a",xO:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
c.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],K:{href:"{{url}}",role:"button","aria-label":"Play next video"},Uy:"Play Now"});g.N(this,this.playButton);this.playButton.uc(this.G.element);this.playButton.listen("click",this.Hm,this);this.W.createServerVe(this.playButton.element,this.playButton,!0);(c=this.W.getVideoData())&&CPH(this,c);this.X=new g.i_(function(){DGz(V)},500);
g.N(this,this.X);this.x$();this.L(X,"autonavvisibility",this.x$);this.W.S("web_autonav_color_transition")&&(this.L(X,"autonavchange",this.X_),this.L(X,"onAutonavCoundownStarted",this.u8_))},yy=function(X){var c=X.W.i4(!0,X.W.isFullscreen());
g.H6(X.container.element,"ytp-autonav-endscreen-small-mode",X.hP(c));g.H6(X.container.element,"ytp-autonav-endscreen-is-premium",!!X.suggestion&&!!X.suggestion.W8y);g.H6(X.W.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!X.W.qJ());g.H6(X.W.getRootNode(),"countdown-running",X.jt());g.H6(X.container.element,"ytp-player-content",X.W.qJ());g.ao(X.overlay.element,{width:c.width+"px"});if(!X.jt()){X.W.qJ()?Sei(X,Math.round(iBz(X)/1E3)):Sei(X);c=!!X.suggestion&&!!X.suggestion.s8;var V=X.W.qJ()||
!c;g.H6(X.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!V&&c);g.H6(X.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",V&&!c);X.G.Ry(X.W.qJ());g.H6(X.element,"ytp-enable-w2w-color-transitions",qek(X))}},DGz=function(X){var c=iBz(X),V=Math,G=V.min;
var n=X.U?Date.now()-X.U:0;V=G.call(V,n,c);Sei(X,Math.ceil((c-V)/1E3));c-V<=500&&X.jt()?X.select(!0):X.jt()&&X.X.start()},iBz=function(X){if(X.W.isFullscreen()){var c;
X=(c=X.W.getVideoData())==null?void 0:c.B8;return X===-1||X===void 0?8E3:X}return X.W.hW()>=0?X.W.hW():g.F1(X.W.j().experiments,"autoplay_time")||1E4},CPH=function(X,c){c=c.getWatchNextResponse();
var V,G;c=(V=s3t(c))==null?void 0:(G=V.nextButton)==null?void 0:G.buttonRenderer;X.B=c==null?void 0:c.navigationEndpoint;V=c==null?void 0:c.trackingParams;X.playButton&&V&&X.W.setTrackingParams(X.playButton.element,V)},qek=function(X){var c;
return!((c=X.W.getVideoData())==null||!c.watchToWatchTransitionRenderer)},Sei=function(X,c){c=c===void 0?-1:c;
X=X.J.I2("ytp-autonav-endscreen-upnext-header");g.n_(X);if(c>=0){c=String(c);var V="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],G="Up next in $SECONDS".indexOf(V);if(G>=0){X.appendChild(g.Vj("Up next in $SECONDS".slice(0,G)));var n=g.cW("span");g.dI(n,"ytp-autonav-endscreen-upnext-header-countdown-number");g.h5(n,c);X.appendChild(n);X.appendChild(g.Vj("Up next in $SECONDS".slice(G+V.length)));return}}g.h5(X,"Up next")},hn=function(X,c){g.z.call(this,{N:"div",
xO:["html5-endscreen","ytp-player-content",c||"base-endscreen"]});this.created=!1;this.player=X},An=function(X){g.z.call(this,{N:"div",
xO:["ytp-upnext","ytp-player-content"],K:{"aria-label":"{{aria_label}}"},V:[{N:"div",Y:"ytp-cued-thumbnail-overlay-image",K:{style:"{{background}}"}},{N:"span",Y:"ytp-upnext-top",V:[{N:"span",Y:"ytp-upnext-header",Uy:"Up Next"},{N:"span",Y:"ytp-upnext-title",Uy:"{{title}}"},{N:"span",Y:"ytp-upnext-author",Uy:"{{author}}"}]},{N:"a",Y:"ytp-upnext-autoplay-icon",K:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{N:"svg",K:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{N:"circle",Y:"ytp-svg-autoplay-circle",K:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{N:"circle",Y:"ytp-svg-autoplay-ring",K:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{N:"path",Y:"ytp-svg-fill",K:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{N:"span",Y:"ytp-upnext-bottom",V:[{N:"span",Y:"ytp-upnext-cancel"},{N:"span",Y:"ytp-upnext-paused",
Uy:"Autoplay is paused"}]}]});this.api=X;this.cancelButton=null;this.B=this.I2("ytp-svg-autoplay-ring");this.U=this.notification=this.J=this.suggestion=null;this.X=new g.i_(this.sS,5E3,this);this.G=0;var c=this.I2("ytp-upnext-cancel");this.cancelButton=new g.z({N:"button",xO:["ytp-upnext-cancel-button","ytp-button"],K:{tabindex:"0","aria-label":"Cancel autoplay"},Uy:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.listen("click",this.F_,this);this.cancelButton.uc(c);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.N(this,this.X);this.api.createClientVe(this.element,this,18788);c=this.I2("ytp-upnext-autoplay-icon");this.L(c,"click",this.IN);this.api.createClientVe(c,this,115130);this.Bm();this.L(X,"autonavvisibility",this.Bm);this.L(X,"mdxnowautoplaying",this.GmK);this.L(X,"mdxautoplaycanceled",this.ATl);g.H6(this.element,"ytp-upnext-mobile",this.api.j().G)},Xaz=function(X,c){if(c)return c;
if(X.api.isFullscreen()){var V;X=(V=X.api.getVideoData())==null?void 0:V.B8;return X===-1||X===void 0?8E3:X}return X.api.hW()>=0?X.api.hW():g.F1(X.api.j().experiments,"autoplay_time")||1E4},c$t=function(X,c){c=Xaz(X,c);
var V=Math,G=V.min;var n=(0,g.bE)()-X.G;V=G.call(V,n,c);c=c===0?1:Math.min(V/c,1);X.B.setAttribute("stroke-dashoffset",""+-211*(c+1));c>=1&&X.jt()&&X.api.getPresentingPlayerType()!==3?X.select(!0):X.jt()&&X.J.start()},YV=function(X){hn.call(this,X,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.z({N:"div",Y:"ytp-suggestion-panel",V:[{N:"div",xO:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Uy:"More videos"}]});this.T=new g.z({N:"div",Y:"ytp-suggestions-container"});this.videos=[];this.U=null;this.B=this.D=!1;this.G=new dX(this.player);g.N(this,this.G);this.G.uc(this.element);X.getVideoData().jX?this.J=this.G:(this.J=new An(X),g.lc(this.player,this.J.element,4),g.N(this,this.J));this.overlay=new g.z({N:"div",
Y:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.uc(this.element);this.X=new g.N_(this);g.N(this,this.X);g.N(this,this.table);this.table.uc(this.element);this.table.show();g.N(this,this.T);this.T.uc(this.table.element);this.hide()},jJ=function(X){var c=X.qJ();
c!==X.B&&(X.B=c,X.player.publish("autonavvisibility"),X.B?(X.G!==X.J&&X.G.hide(),X.table.hide()):(X.G!==X.J&&X.G.show(),X.table.show()))},H_=function(X,c){g.z.call(this,{N:"button",
xO:["ytp-watch-on-youtube-button","ytp-button"],Uy:"{{content}}"});this.W=X;this.buttonType=this.buttonType=c;this.j1();this.buttonType===2&&g.hx(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.j1);this.Ry(!0)},af=function(X,c){hn.call(this,X,"embeds-lite-endscreen");
this.W=X;this.J=c;this.W.createClientVe(this.element,this,156943);this.watchButton=new H_(X,2);g.N(this,this.watchButton);this.watchButton.uc(this.element);this.hide()},VSr=function(X){hn.call(this,X,"subscribecard-endscreen");
this.J=new g.z({N:"div",Y:"ytp-subscribe-card",V:[{N:"img",Y:"ytp-author-image",K:{src:"{{profilePicture}}"}},{N:"div",Y:"ytp-subscribe-card-right",V:[{N:"div",Y:"ytp-author-name",Uy:"{{author}}"},{N:"div",Y:"html5-subscribe-button-container"}]}]});g.N(this,this.J);this.J.uc(this.element);var c=X.getVideoData();this.subscribeButton=new g.DL("Subscribe",null,"Unsubscribe",null,!0,!1,c.F7,c.subscribed,"trailer-endscreen",null,X,!1);g.N(this,this.subscribeButton);this.subscribeButton.uc(this.J.I2("html5-subscribe-button-container"));
this.L(X,"videodatachange",this.pS);this.pS();this.hide()},$V=function(X){var c=X.j(),V=g.gp||g.e3?{style:"will-change: opacity"}:void 0,G=c.X,n=["ytp-videowall-still"];
c.G&&n.push("ytp-videowall-show-text");g.z.call(this,{N:"a",xO:n,K:{href:"{{url}}",target:G?c.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{N:"div",Y:"ytp-videowall-still-image",K:{style:"{{background}}"}},{N:"span",Y:"ytp-videowall-still-info",K:{"aria-hidden":"true"},V:[{N:"span",Y:"ytp-videowall-still-info-bg",V:[{N:"span",Y:"ytp-videowall-still-info-content",K:V,V:[{N:"span",Y:"ytp-videowall-still-info-title",Uy:"{{title}}"},
{N:"span",Y:"ytp-videowall-still-info-author",Uy:"{{author_and_views}}"},{N:"span",Y:"ytp-videowall-still-info-live",Uy:"Live"},{N:"span",Y:"ytp-videowall-still-info-duration",Uy:"{{duration}}"}]}]}]},{N:"span",xO:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:{"aria-hidden":"true"},V:[{N:"span",Y:"ytp-videowall-still-listlabel-icon"},"Playlist",{N:"span",Y:"ytp-videowall-still-listlabel-length",V:[" (",{N:"span",Uy:"{{playlist_length}}"},")"]}]},{N:"span",xO:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],K:{"aria-hidden":"true"},V:[{N:"span",Y:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{N:"span",Y:"ytp-videowall-still-listlabel-length",Uy:" (50+)"}]}]});this.suggestion=null;this.G=G;this.api=X;this.J=new g.N_(this);g.N(this,this.J);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.J.L(X,"videodatachange",this.onVideoDataChange);X.createServerVe(this.element,this);this.onVideoDataChange()},W_=function(X){hn.call(this,X,"videowall-endscreen");
var c=this;this.W=X;this.U=0;this.stills=[];this.X=this.videoData=null;this.B=this.T=!1;this.C=null;this.G=new g.N_(this);g.N(this,this.G);this.D=new g.i_(function(){g.hx(c.element,"ytp-show-tiles")},0);
g.N(this,this.D);var V=new g.z({N:"button",xO:["ytp-button","ytp-endscreen-previous"],K:{"aria-label":"Previous"},V:[g.kT()]});g.N(this,V);V.uc(this.element);V.listen("click",this.P9,this);this.table=new g.WR({N:"div",Y:"ytp-endscreen-content"});g.N(this,this.table);this.table.uc(this.element);V=new g.z({N:"button",xO:["ytp-button","ytp-endscreen-next"],K:{"aria-label":"Next"},V:[g.o_()]});g.N(this,V);V.uc(this.element);V.listen("click",this.W9,this);X.getVideoData().jX?this.J=new dX(X,!0):this.J=
new An(X);g.N(this,this.J);g.lc(this.player,this.J.element,4);X.createClientVe(this.element,this,158789);this.hide()},wX=function(X){return g.M$(X.player)&&X.Ga()&&!X.X},FZ=function(X){var c=X.qJ();
c!==X.T&&(X.T=c,X.player.publish("autonavvisibility"))},Es=function(X){hn.call(this,X,"watch-again-on-youtube-endscreen");
this.watchButton=new H_(X,1);g.N(this,this.watchButton);this.watchButton.uc(this.element);g.VD_(X)&&(this.J=new g.s0(X),g.N(this,this.J),this.G=new g.z({N:"div",xO:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],K:{tabIndex:"-1"},V:[this.J]}),g.N(this,this.G),this.J.uc(this.G.element),this.G.uc(this.element));X.createClientVe(this.element,this,156914);this.hide()},d4r=function(X){g.wh.call(this,X);
var c=this;this.endScreen=null;this.G=this.J=this.U=this.X=!1;this.listeners=new g.N_(this);g.N(this,this.listeners);var V=X.j(),G=X.getVideoData();G=G&&G.limitedPlaybackDurationInSeconds!==0;g.al(g.pL(V))&&G&&!g.Rx(X)?(this.G=!0,this.endScreen=new af(X,g.WO(X))):X.isEmbedsShortsMode()?this.endScreen=new Es(X):Gri(X)?(this.X=!0,npU(this),this.J?this.endScreen=new YV(X):this.endScreen=new W_(X)):V.jX?this.endScreen=new VSr(X):this.endScreen=new hn(X);g.N(this,this.endScreen);g.lc(X,this.endScreen.element,
4);L_k(this);this.listeners.L(X,"videodatachange",this.onVideoDataChange,this);this.listeners.L(X,g.Ya("endscreen"),function(n){c.onCueRangeEnter(n)});
this.listeners.L(X,g.jw("endscreen"),function(n){c.onCueRangeExit(n)})},npU=function(X){var c=X.player.getVideoData();
if(!c||X.J===c.uV&&X.U===c.jX)return!1;X.J=c.uV;X.U=c.jX;return!0},Gri=function(X){X=X.j();
return X.gm&&!X.jX&&!X.disableOrganicUi},L_k=function(X){X.player.EH("endscreen");
var c=X.player.getVideoData();c=new g.hC(Math.max((c.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var V=new g.hC(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});X.player.Gr([c,V])};
g.ox.prototype.hW=g.Gt(14,function(){return this.app.hW()});
g.Wn.prototype.hW=g.Gt(13,function(){return this.getVideoData().uC});
g.Z6.prototype.kV=g.Gt(12,function(X){this.bF().kV(X)});
g.aK.prototype.kV=g.Gt(11,function(X){this.J!==X&&(this.J=X,this.pS())});
g.eY.prototype.kV=g.Gt(10,function(X){this.overflowButton&&this.overflowButton.kV(X)});
g.Z6.prototype.Fb=g.Gt(9,function(X){this.bF().Fb(X)});
g.rO.prototype.Fb=g.Gt(8,function(X){this.G!==X&&(this.G=X,this.pS())});
g.eY.prototype.Fb=g.Gt(7,function(X){this.shareButton&&this.shareButton.Fb(X)});
g.Z6.prototype.dE=g.Gt(6,function(X){this.bF().dE(X)});
g.uV.prototype.dE=g.Gt(5,function(X){this.Kv!==X&&(this.Kv=X,this.Y8())});
g.Z6.prototype.T9=g.Gt(4,function(X){this.bF().T9(X)});
g.eY.prototype.T9=g.Gt(3,function(X){this.yW!==X&&(this.yW=X,this.rh())});g.E(L6,g.z);L6.prototype.select=function(){this.W.Tf(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ta||void 0)&&this.W.logClick(this.element)};
L6.prototype.onClick=function(X){g.Lz(X,this.W,this.J,this.suggestion.sessionData||void 0)&&this.select()};
L6.prototype.onKeyPress=function(X){switch(X.keyCode){case 13:case 32:X.defaultPrevented||(this.select(),X.preventDefault())}};g.E(dX,g.z);g.y=dX.prototype;g.y.fQ=function(X){this.suggestion!==X&&(this.suggestion=X,n6(this.J,X),this.playButton.updateValue("url",this.suggestion.nK()),yy(this))};
g.y.jt=function(){return this.U>0};
g.y.qH=function(){this.jt()||(this.U=Date.now(),DGz(this),K2V(this.W,iBz(this)),g.H6(this.W.getRootNode(),"countdown-running",this.jt()))};
g.y.Ln=function(){this.wh();DGz(this);var X=this.J.I2("ytp-autonav-endscreen-upnext-header");X&&g.h5(X,"Up next")};
g.y.wh=function(){this.jt()&&(this.X.stop(),this.U=0)};
g.y.select=function(X){this.W.nextVideo(!1,X===void 0?!1:X);this.wh()};
g.y.Hm=function(X){g.Lz(X,this.W)&&(X.currentTarget===this.playButton.element?this.W.logClick(this.playButton.element):X.currentTarget===this.J.I2("ytp-autonav-endscreen-link-container")&&(X=this.J.I2("ytp-autonav-endscreen-link-container"),this.W.logVisibility(X,!0),this.W.logClick(X)),this.B?(this.W.z_("innertubeCommand",this.B),this.wh()):this.select())};
g.y.k7=function(){this.W.logClick(this.cancelButton.element);g.Jt(this.W,!0);this.cancelCommand&&this.W.z_("innertubeCommand",this.cancelCommand)};
g.y.onVideoDataChange=function(X,c){CPH(this,c);X=c.getWatchNextResponse();var V,G;X=(V=s3t(X))==null?void 0:(G=V.cancelButton)==null?void 0:G.buttonRenderer;this.cancelCommand=X==null?void 0:X.command};
g.y.u8_=function(X){if(qek(this)){var c=this.W.getVideoData().watchToWatchTransitionRenderer,V=c==null?void 0:c.fromColorPaletteDark;c=c==null?void 0:c.toColorPaletteDark;if(V&&c){var G=this.element;G.style.setProperty("--w2w-start-background-color",g.PB(V.surgeColor));G.style.setProperty("--w2w-start-primary-text-color",g.PB(V.primaryTitleColor));G.style.setProperty("--w2w-start-secondary-text-color",g.PB(V.secondaryTitleColor));G.style.setProperty("--w2w-end-background-color",g.PB(c.surgeColor));
G.style.setProperty("--w2w-end-primary-text-color",g.PB(c.primaryTitleColor));G.style.setProperty("--w2w-end-secondary-text-color",g.PB(c.secondaryTitleColor));G.style.setProperty("--w2w-animation-duration",X+"ms")}g.H6(this.element,"ytp-w2w-animate",!0)}};
g.y.X_=function(X){this.W.S("web_autonav_color_transition")&&X!==2&&g.H6(this.element,"ytp-w2w-animate",!1)};
g.y.x$=function(){var X=this.W.qJ();this.D&&this.aZ!==X&&this.Ry(X);yy(this);this.W.logVisibility(this.container.element,X);this.W.logVisibility(this.cancelButton.element,X);this.W.logVisibility(this.J.I2("ytp-autonav-endscreen-link-container"),X);this.W.logVisibility(this.playButton.element,X)};
g.y.hP=function(X){return X.width<400||X.height<459};g.E(hn,g.z);g.y=hn.prototype;g.y.create=function(){this.created=!0};
g.y.destroy=function(){this.created=!1};
g.y.Ga=function(){return!1};
g.y.qJ=function(){return!1};
g.y.bY=function(){return!1};g.E(An,g.z);g.y=An.prototype;g.y.sS=function(){this.notification&&(this.X.stop(),this.Hd(this.U),this.U=null,this.notification.close(),this.notification=null)};
g.y.fQ=function(X){this.suggestion=X;n6(this,X,"hqdefault.jpg")};
g.y.Bm=function(){this.Ry(this.api.qJ());this.api.logVisibility(this.element,this.api.qJ());this.api.logVisibility(this.I2("ytp-upnext-autoplay-icon"),this.api.qJ());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.qJ())};
g.y.agO=function(){window.focus();this.sS()};
g.y.qH=function(X){var c=this;this.jt()||(g.j_("a11y-announce","Up Next "+this.suggestion.title),this.G=(0,g.bE)(),this.J=new g.i_(function(){c$t(c,X)},25),c$t(this,X),K2V(this.api,Xaz(this,X)));
g.YD(this.element,"ytp-upnext-autoplay-paused")};
g.y.hide=function(){g.z.prototype.hide.call(this)};
g.y.jt=function(){return!!this.J};
g.y.Ln=function(){this.wh();this.G=(0,g.bE)();c$t(this);g.hx(this.element,"ytp-upnext-autoplay-paused")};
g.y.wh=function(){this.jt()&&(this.J.dispose(),this.J=null)};
g.y.select=function(X){X=X===void 0?!1:X;if(this.api.j().S("autonav_notifications")&&X&&window.Notification&&typeof document.hasFocus==="function"){var c=Notification.permission;c==="default"?Notification.requestPermission():c!=="granted"||document.hasFocus()||(this.sS(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.xz()}),this.U=this.L(this.notification,"click",this.agO),this.X.start())}this.wh();this.api.nextVideo(!1,X)};
g.y.IN=function(X){!g.yj(this.cancelButton.element,X.target)&&g.Lz(X,this.api)&&(this.api.qJ()&&this.api.logClick(this.I2("ytp-upnext-autoplay-icon")),this.select())};
g.y.F_=function(){this.api.qJ()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Jt(this.api,!0)};
g.y.GmK=function(X){this.api.getPresentingPlayerType();this.show();this.qH(X)};
g.y.ATl=function(){this.api.getPresentingPlayerType();this.wh();this.hide()};
g.y.R2=function(){this.wh();this.sS();g.z.prototype.R2.call(this)};g.E(YV,hn);g.y=YV.prototype;g.y.create=function(){hn.prototype.create.call(this);this.X.L(this.player,"appresize",this.TO);this.X.L(this.player,"onVideoAreaChange",this.TO);this.X.L(this.player,"videodatachange",this.onVideoDataChange);this.X.L(this.player,"autonavchange",this.wv);this.X.L(this.player,"onAutonavCancelled",this.aN);this.onVideoDataChange()};
g.y.show=function(){hn.prototype.show.call(this);(this.D||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.Jt(this.player,!1);g.M$(this.player)&&this.Ga()&&!this.U?(jJ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.J.select(!0):this.J.qH():this.videoData.autonavState===3&&this.J.Ln()):(g.Jt(this.player,!0),jJ(this));this.TO()};
g.y.hide=function(){hn.prototype.hide.call(this);this.J.Ln();jJ(this)};
g.y.TO=function(){var X=this.player.i4(!0,this.player.isFullscreen());jJ(this);yy(this.G);g.H6(this.element,"ytp-autonav-cancelled-small-mode",this.hP(X));g.H6(this.element,"ytp-autonav-cancelled-tiny-mode",this.eb(X));g.H6(this.element,"ytp-autonav-cancelled-mini-mode",X.width<=400||X.height<=360);this.overlay&&g.ao(this.overlay.element,{width:X.width+"px"});if(!this.B)for(X=0;X<this.videos.length;X++)g.H6(this.videos[X].element,"ytp-suggestion-card-with-margin",X%2===1)};
g.y.onVideoDataChange=function(){var X=this.player.getVideoData();if(this.videoData!==X&&X){this.videoData=X;if((X=this.videoData.suggestions)&&X.length||this.player.S("web_player_autonav_empty_suggestions_fix")){var c=g.qV(this.videoData);c&&(this.J.fQ(c),this.J!==this.G&&this.G.fQ(c))}if(X&&X.length)for(c=0;c<y$A.length;++c){var V=y$A[c];if(X&&X[V]){this.videos[c]=new L6(this.player);var G=this.videos[c];V=X[V];G.suggestion!==V&&(G.suggestion=V,n6(G,V));g.N(this,this.videos[c]);this.videos[c].uc(this.T.element)}}this.TO()}};
g.y.wv=function(X){X===1?(this.D=!1,this.U=this.videoData.clientPlaybackNonce,this.J.wh(),this.aZ&&this.TO()):(this.D=!0,this.qJ()&&(X===2?this.J.qH():X===3&&this.J.Ln()))};
g.y.aN=function(X){X?this.wv(1):(this.U=null,this.D=!1)};
g.y.Ga=function(){return this.videoData.autonavState!==1};
g.y.hP=function(X){return(X.width<910||X.height<459)&&!this.eb(X)&&!(X.width<=400||X.height<=360)};
g.y.eb=function(X){return X.width<800&&!(X.width<=400||X.height<=360)};
g.y.qJ=function(){return this.aZ&&g.M$(this.player)&&this.Ga()&&!this.U};
var y$A=[1,3,2,4];g.E(H_,g.z);g.y=H_.prototype;g.y.j1=function(){switch(this.buttonType){case 1:var X="Watch again on YouTube";var c=156915;break;case 2:X="Continue watching on YouTube";c=156942;break;default:X="Continue watching on YouTube",c=156942}this.update({content:X});this.W.hasVe(this.element)&&this.W.destroyVe(this.element);this.W.createClientVe(this.element,this,c)};
g.y.onClick=function(X){this.W.S("web_player_log_click_before_generating_ve_conversion_params")&&this.W.logClick(this.element);g.dZ(this.getVideoUrl(),this.W,X);this.W.S("web_player_log_click_before_generating_ve_conversion_params")||this.W.logClick(this.element)};
g.y.getVideoUrl=function(){var X=!0;switch(this.buttonType){case 1:X=!0;break;case 2:X=!1}X=this.W.getVideoUrl(X,!1,!1,!0);var c=this.W.j();if(g.mA(c)){var V={};g.mA(c)&&g.Yz(this.W,"addEmbedsConversionTrackingParams",[V]);X=g.BU(X,V)}return X};
g.y.logVisibility=function(){this.W.logVisibility(this.element,this.aZ&&this.Z)};
g.y.show=function(){g.z.prototype.show.call(this);this.logVisibility()};
g.y.hide=function(){g.z.prototype.hide.call(this);this.logVisibility()};
g.y.iB=function(X){g.z.prototype.iB.call(this,X);this.logVisibility()};g.E(af,hn);af.prototype.show=function(){this.player.getPlayerState()!==3&&(hn.prototype.show.call(this),this.J.T9(!0),this.J.Fb(!0),this.W.j().gs||this.J.kV(!0),this.W.logVisibility(this.element,!0),this.watchButton.iB(!0))};
af.prototype.hide=function(){hn.prototype.hide.call(this);this.J.T9(!1);this.J.Fb(!1);this.J.kV(!1);this.W.logVisibility(this.element,!1);this.watchButton.iB(!1)};g.E(VSr,hn);VSr.prototype.pS=function(){var X=this.player.getVideoData();this.J.update({profilePicture:X.profilePicture,author:X.author});this.subscribeButton.channelId=X.F7;var c=this.subscribeButton;X.subscribed?c.J():c.G()};g.E($V,g.z);$V.prototype.select=function(){this.api.Tf(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ta||void 0)&&this.api.logClick(this.element)};
$V.prototype.onClick=function(X){if(g.mA(this.api.j())&&this.api.S("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var c=this.suggestion.nK(),V={};g.bc(this.api,V);c=g.BU(c,V);g.dZ(c,this.api,X)}else g.Lz(X,this.api,this.G,this.suggestion.sessionData||void 0)&&this.select()};
$V.prototype.onKeyPress=function(X){switch(X.keyCode){case 13:case 32:X.defaultPrevented||(this.select(),X.preventDefault())}};
$V.prototype.onVideoDataChange=function(){var X=this.api.getVideoData(),c=this.api.j();this.G=X.O5?!1:c.X};g.E(W_,hn);g.y=W_.prototype;g.y.create=function(){hn.prototype.create.call(this);var X=this.player.getVideoData();X&&(this.videoData=X);this.jB();this.G.L(this.player,"appresize",this.jB);this.G.L(this.player,"onVideoAreaChange",this.jB);this.G.L(this.player,"videodatachange",this.onVideoDataChange);this.G.L(this.player,"autonavchange",this.XF);this.G.L(this.player,"onAutonavCancelled",this.Np);X=this.videoData.autonavState;X!==this.C&&this.XF(X);this.G.L(this.element,"transitionend",this.e8y)};
g.y.destroy=function(){g.O1(this.G);g.Ap(this.stills);this.stills=[];hn.prototype.destroy.call(this);g.YD(this.element,"ytp-show-tiles");this.D.stop();this.C=this.videoData.autonavState};
g.y.Ga=function(){return this.videoData.autonavState!==1};
g.y.show=function(){var X=this.aZ;hn.prototype.show.call(this);g.YD(this.element,"ytp-show-tiles");this.player.j().G?g.Xn(this.D):this.D.start();(this.B||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.Jt(this.player,!1);wX(this)?(FZ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.J.select(!0):this.J.qH():this.videoData.autonavState===3&&this.J.Ln()):(g.Jt(this.player,!0),FZ(this));X!==this.aZ&&this.player.logVisibility(this.element,!0)};
g.y.hide=function(){var X=this.aZ;hn.prototype.hide.call(this);this.J.Ln();FZ(this);X!==this.aZ&&this.player.logVisibility(this.element,!1)};
g.y.e8y=function(X){X.target===this.element&&this.jB()};
g.y.jB=function(){var X,c,V,G;var n=((X=this.videoData)==null?0:(c=X.suggestions)==null?0:c.length)?(V=this.videoData)==null?void 0:V.suggestions:[(G=this.videoData)==null?void 0:g.qV(G)];if(n.length){g.hx(this.element,"ytp-endscreen-paginate");var L=this.W.i4(!0,this.W.isFullscreen());if(X=g.WO(this.W))X=X.jO()?48:32,L.width-=X*2;var d=L.width/L.height;G=96/54;c=X=2;var h=Math.max(L.width/96,2),A=Math.max(L.height/54,2);V=n.length;var Y=V*4;for(Y-=4;Y>0&&(X<h||c<A);){var H=X/2,a=c/2,W=X<=h-2&&Y>=
a*4,w=c<=A-2&&Y>=H*4;if((H+1)/a*G/d>d/(H/(a+1)*G)&&w)Y-=H*4,c+=2;else if(W)Y-=a*4,X+=2;else if(w)Y-=H*4,c+=2;else break}G=!1;Y>=12&&V*4-Y<=6&&(c>=4||X>=4)&&(G=!0);Y=X*96;h=c*54;d=Y/h<d?L.height/h:L.width/Y;d=Math.min(d,2);Y=Math.floor(Math.min(L.width,Y*d));h=Math.floor(Math.min(L.height,h*d));L=this.table.element;L.ariaLive="polite";g.JS(L,Y,h);g.ao(L,{marginLeft:Y/-2+"px",marginTop:h/-2+"px"});this.J.fQ(g.qV(this.videoData));this.J instanceof dX&&yy(this.J);g.H6(this.element,"ytp-endscreen-takeover",
wX(this));FZ(this);Y+=4;h+=4;d=0;L.ariaBusy="true";for(A=0;A<X;A++)for(H=0;H<c;H++)if(a=d,w=0,G&&A>=X-2&&H>=c-2?w=1:H%2===0&&A%2===0&&(H<2&&A<2?H===0&&A===0&&(w=2):w=2),a=g.am(a+this.U,V),w!==0){W=this.stills[d];W||(W=new $V(this.player),this.stills[d]=W,L.appendChild(W.element));var F=Math.floor(h*H/c),Z=Math.floor(Y*A/X),v=Math.floor(h*(H+w)/c)-F-4,e=Math.floor(Y*(A+w)/X)-Z-4;g.rS(W.element,Z,F);g.JS(W.element,e,v);g.ao(W.element,"transitionDelay",(H+A)/20+"s");g.H6(W.element,"ytp-videowall-still-mini",
w===1);g.H6(W.element,"ytp-videowall-still-large",w>2);w=Math.max(e,v);g.H6(W.element,"ytp-videowall-still-round-large",w>=256);g.H6(W.element,"ytp-videowall-still-round-medium",w>96&&w<256);g.H6(W.element,"ytp-videowall-still-round-small",w<=96);a=n[a];W.suggestion!==a&&(W.suggestion=a,w=W.api.j(),F=g.yO(W.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",n6(W,a,F),g.mA(w)&&!W.api.S("web_player_log_click_before_generating_ve_conversion_params")&&(w=a.nK(),F={},g.Yz(W.api,"addEmbedsConversionTrackingParams",
[F]),w=g.BU(w,F),W.updateValue("url",w)),(a=(a=a.sessionData)&&a.itct)&&W.api.setTrackingParams(W.element,a));d++}L.ariaBusy="false";g.H6(this.element,"ytp-endscreen-paginate",d<V);for(n=this.stills.length-1;n>=d;n--)X=this.stills[n],g.dW(X.element),g.hp(X);this.stills.length=d}};
g.y.onVideoDataChange=function(){var X=this.player.getVideoData(1);this.videoData!==X&&(X!=null&&g.qV(X)?(this.U=0,this.videoData=X,this.jB()):this.player.Oy("missg",{vid:(X==null?void 0:X.videoId)||"",cpn:(X==null?void 0:X.clientPlaybackNonce)||""}))};
g.y.W9=function(){this.U+=this.stills.length;this.jB()};
g.y.P9=function(){this.U-=this.stills.length;this.jB()};
g.y.bY=function(){return this.J.jt()};
g.y.XF=function(X){X===1?(this.B=!1,this.X=this.videoData.clientPlaybackNonce,this.J.wh(),this.aZ&&this.jB()):(this.B=!0,this.aZ&&wX(this)&&(X===2?this.J.qH():X===3&&this.J.Ln()))};
g.y.Np=function(X){if(X){for(X=0;X<this.stills.length;X++)this.W.logVisibility(this.stills[X].element,!0);this.XF(1)}else this.X=null,this.B=!1;this.jB()};
g.y.qJ=function(){return this.aZ&&wX(this)};g.E(Es,hn);Es.prototype.hasSuggestions=function(){var X;return(X=this.J)==null?void 0:X.hasSuggestions()};
Es.prototype.show=function(){if(this.player.getPlayerState()!==3){hn.prototype.show.call(this);var X=this.G;if(X){var c=this.J.hasSuggestions();g.H6(this.element,"ytp-shorts-branded-ui",c);c?X.show():X.hide()}var V;(V=g.WO(this.player))==null||V.dE(!0);this.player.logVisibility(this.element,!0);this.watchButton.iB(!0)}};
Es.prototype.hide=function(){hn.prototype.hide.call(this);var X;(X=g.WO(this.player))==null||X.dE(!1);this.player.logVisibility(this.element,!1);this.watchButton.iB(!1)};g.E(d4r,g.wh);g.y=d4r.prototype;g.y.Ym=function(){var X=this.player.getVideoData(),c=X.mutedAutoplay&&(X.limitedPlaybackDurationInSeconds>0||X.endSeconds>0||X.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.G)&&!c)return!0;var V;var G=!!((X==null?0:g.qV(X))||(X==null?0:(V=X.suggestions)==null?0:V.length));G=!Gri(this.player)||G;X=X.JZ;V=this.player.OL();return G&&!X&&!V&&!c};
g.y.qJ=function(){return this.endScreen.qJ()};
g.y.ho_=function(){return this.qJ()?this.endScreen.bY():!1};
g.y.R2=function(){this.player.EH("endscreen");g.wh.prototype.R2.call(this)};
g.y.load=function(){var X=this.player.getVideoData();var c=X.transitionEndpointAtEndOfStream;if(c&&c.videoId){var V=this.player.X2().UN.get("heartbeat"),G=g.qV(X);!G||c.videoId!==G.videoId||X.UP?(this.player.Tf(c.videoId,void 0,void 0,!0,!0,c),V&&V.jb("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),X=!0):X=!1}else X=!1;X||(g.wh.prototype.load.call(this),this.endScreen.show())};
g.y.unload=function(){g.wh.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.y.onCueRangeEnter=function(X){this.Ym()&&(this.endScreen.created||this.endScreen.create(),X.getId()==="load"&&this.load())};
g.y.onCueRangeExit=function(X){X.getId()==="load"&&this.loaded&&this.unload()};
g.y.onVideoDataChange=function(){L_k(this);this.X&&npU(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.J?this.endScreen=new YV(this.player):this.endScreen=new W_(this.player),g.N(this,this.endScreen),g.lc(this.player,this.endScreen.element,4))};g.Wr("endscreen",d4r);})(_yt_player);
