(function(g){var window=this;'use strict';var Os=function(X,c){g.z.call(this,{N:"button",xO:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],K:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{N:"svg",K:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{N:"g",K:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{N:"g",K:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{N:"path",K:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.W=X;this.listen("click",this.onClick,this);this.updateValue("title",g.kz(X,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.xz(c.ai(),this.element))},LYU=function(X){g.z.call(this,
{N:"div",
Y:"ytp-miniplayer-ui"});this.B=!1;this.player=X;this.L(X,"minimized",this.ZO);this.L(X,"onStateChange",this.Zl7);this.L(X,"documentpictureinpicturechange",this.iMc)},dX_=function(X,c){g.H6(X.player.getRootNode(),"ytp-player-minimized",c)},yW_=function(X){g.wh.call(this,X);
this.G=new g.N_(this);this.J=new LYU(this.player);this.J.hide();g.lc(this.player,this.J.element,4);X.isMinimized()&&(this.load(),g.H6(X.getRootNode(),"ytp-player-minimized",!0))};
g.E(Os,g.z);Os.prototype.onClick=function(){this.W.z_("onExpandMiniplayer")};g.E(LYU,g.z);g.y=LYU.prototype;
g.y.show=function(){this.J=new g.Sn(this.B9,null,this);this.J.start();if(!this.B){this.tooltip=new g.oZ(this.player,this);g.N(this,this.tooltip);g.lc(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.nE=new g.Br(this.player);g.N(this,this.nE);this.progressBar=new g.IK(this.player,this);g.N(this,this.progressBar);g.lc(this.player,this.progressBar.element,4);this.G=new g.z({N:"div",Y:"ytp-miniplayer-scrim"});g.N(this,this.G);this.G.uc(this.element);this.L(this.G.element,"click",this.a4);
var X=new g.z({N:"button",xO:["ytp-miniplayer-close-button","ytp-button"],K:{"aria-label":"Close"},V:[g.eB()]});g.N(this,X);X.uc(this.G.element);this.L(X.element,"click",this.Qb);X=new Os(this.player,this);g.N(this,X);X.uc(this.G.element);this.U=new g.z({N:"div",Y:"ytp-miniplayer-controls"});g.N(this,this.U);this.U.uc(this.G.element);this.L(this.U.element,"click",this.a4);var c=new g.z({N:"div",Y:"ytp-miniplayer-button-container"});g.N(this,c);c.uc(this.U.element);X=new g.z({N:"div",Y:"ytp-miniplayer-play-button-container"});
g.N(this,X);X.uc(this.U.element);var V=new g.z({N:"div",Y:"ytp-miniplayer-button-container"});g.N(this,V);V.uc(this.U.element);this.T=new g.l8(this.player,this,!1);g.N(this,this.T);this.T.uc(c.element);c=new g.O4(this.player,this);g.N(this,c);c.uc(X.element);this.nextButton=new g.l8(this.player,this,!0);g.N(this,this.nextButton);this.nextButton.uc(V.element);this.D=new g.wF(this.player,this,0);g.N(this,this.D);this.D.uc(this.G.element);this.X=new g.z({N:"div",Y:"ytp-miniplayer-buttons"});g.N(this,
this.X);g.lc(this.player,this.X.element,4);X=new g.z({N:"button",xO:["ytp-miniplayer-close-button","ytp-button"],K:{"aria-label":"Close"},V:[g.eB()]});g.N(this,X);X.uc(this.X.element);this.L(X.element,"click",this.Qb);X=new g.z({N:"button",xO:["ytp-miniplayer-replay-button","ytp-button"],K:{"aria-label":"Close"},V:[g.Od()]});g.N(this,X);X.uc(this.X.element);this.L(X.element,"click",this.d6y);X=new Os(this.player,this);g.N(this,X);X.uc(this.X.element);this.L(this.player,"presentingplayerstatechange",
this.c9);this.L(this.player,"appresize",this.Ky);this.L(this.player,"fullscreentoggled",this.Ky);this.Ky();this.B=!0}this.player.getPlayerState()!==0&&g.z.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.y.hide=function(){this.J&&(this.J.dispose(),this.J=void 0);g.z.prototype.hide.call(this);this.player.isMinimized()||(this.B&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.y.R2=function(){this.J&&(this.J.dispose(),this.J=void 0);g.z.prototype.R2.call(this)};
g.y.Qb=function(){this.player.S("kevlar_watch_while_v2")||this.player.stopVideo();this.player.z_("onCloseMiniplayer")};
g.y.d6y=function(){this.player.playVideo()};
g.y.a4=function(X){if(X.target===this.G.element||X.target===this.U.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.y.ZO=function(){dX_(this,this.player.isMinimized())};
g.y.iMc=function(){dX_(this,this.player.eU());g.H6(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.eU())};
g.y.E5=function(){this.progressBar.er();this.D.er()};
g.y.B9=function(){this.E5();this.J&&this.J.start()};
g.y.c9=function(X){g.B(X.state,32)&&this.tooltip.hide()};
g.y.Ky=function(){var X=this.player.CS().getPlayerSize().width;g.kUs(this.progressBar,0,X,!1);g.Nb(this.progressBar)};
g.y.Zl7=function(X){this.player.isMinimized()&&(X===0?this.hide():this.show())};
g.y.ai=function(){return this.tooltip};
g.y.sz=function(X,c,V,G,n){var L=0,d=0,h=0,A=g.mn(X);G=c&&(g.yO(c,"ytp-prev-button")||g.yO(c,"ytp-next-button"));if(c){V=g.yO(c,"ytp-play-button");var Y=g.yO(c,"ytp-miniplayer-expand-watch-page-button");G?L=h=12:V?(c=g.xv(c,this.element),h=c.x,L=c.y-12):Y&&(h=g.yO(c,"ytp-miniplayer-button-top-left"),L=g.xv(c,this.element),c=g.mn(c),h?(h=8,L=L.y+40):(h=L.x-A.width+c.width,L=L.y-20))}else h=V-A.width/2,d=25+(n||0);c=this.player.CS().getPlayerSize();n=L+(n||0);A=g.H1(h,0,c.width-A.width-12);n?(X.style.top=
n+"px",X.style.bottom=""):(X.style.top="",X.style.bottom=d+"px");X.style.left=A+"px";d=g.yO(X,"ytp-preview");X.style.visibility=G&&d&&c.height<225?"hidden":""};g.E(yW_,g.wh);g.y=yW_.prototype;g.y.onVideoDataChange=function(){if(this.player.getVideoData()){var X=this.player.getVideoAspectRatio(),c=16/9;X=X>c+.1||X<c-.1;g.H6(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",X)}};
g.y.create=function(){g.wh.prototype.create.call(this);this.G.L(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.y.Ut=function(){return!1};
g.y.load=function(){this.player.hideControls();this.J.show()};
g.y.unload=function(){this.player.showControls();this.J.hide()};g.Wr("miniplayer",yW_);})(_yt_player);
